Hình_ảnh mới của ông Bush ở Đông_Á 
Ông G_H_Bush tới châu Á lần đầu_tiên với tư_cách là tổng_thống chỉ hai tháng sau sự_kiện 11/9 , không có nhiều thời_gian và lòng kiên_nhẫn cho các chủ_đề truyền_thống của APEC , vốn tập_trung vào thương_mại và toàn_cầu_hoá . 
Nhưng năm nay thì khác . 
Khi Bush tới cố_đô cổ_kính của Nhật_Bản đêm 15/11 , điểm dừng chân đầu_tiên trong chuyến công_du 4 nước châu Á và dự hội_nghị cấp cao APEC , ông nói về những công_việc của mình ở đây giống như cha_ông hay người tiền_nhiệm Bill_Clinton từng làm . 
Cố_vấn an_ninh quốc_gia Mỹ Stephen_Hadley , người có trách_nhiệm quan_trọng trong các vấn_đề an_ninh và chống khủng_bố của nước Mỹ , lại chính là người phát_biểu nhấn_mạnh rằng ông Bush lần này tới châu Á để đề_cao quyền_lợi của các công_nhân , doanh_nhân và doanh_nghiệp Mỹ . 
Các chủ_đề từng được ưu_tiên trong các chuyến đi trước của Bush tới châu Á như chống khủng_bố , vấn_đề hạt_nhân Triều_Tiên , cũng được đưa ra , nhưng không được chú_trọng như trước , Hadley nói thêm . 
Ngay bên trong Nhà_Trắng cũng có sự ngạc_nhiên trước thay_đổi này , một_số người còn ngờ rằng : với sức_ép đang mạnh trở_lại ngay trong nước Mỹ về chuyện chiến_tranh Iraq , không hiểu ông Bush có_thể kiên_quyết nói về kinh_tế hay không . 
Một trợ_lý của tổng_thống còn phát_biểu rằng  ông ấy thậm_chí không thích nói_chuyện toàn_cầu_hoá  và hầu_như chẳng bao_giờ bàn_luận về những chuyện phức_tạp rối_rắm trong thương_mại . 
Nhưng sau chuyến công_du hai tuần trước tới Nam_Mỹ , nơi ông Bush cố sức để tạo_lập một khu_vực mậu_dịch tự_do liên_Mỹ nhưng lại thất_bại cay_đắng , đồng_thời với tỷ_lệ ủng_hộ thấp ở trong nước , có_lẽ ông_chủ Nhà_Trắng không có lựa_chọn nào khả_dĩ hơn là nói_chuyện thương_mại và kinh_tế . 
Thêm nữa , trong số các nước đón_tiếp ông Bush ở châu Á tuần này , đang xuất_hiện một tâm_lý cho rằng chính việc Mỹ quá chú_trọng tới vấn_đề Iraq và chống khủng_bố đã khiến chính_sách của Washington đối_với khu_vực này bị đưa xuống hàng thứ_yếu . 
Vậy là có nhiều khả_năng ông phải  chuyển tông  . 
Ngay_cả việc tổng_thống Mỹ chỉ_trích Trung_Quốc về vấn_đề nhân_quyền và dân_chủ cũng mất đi độ sắc trước_kia , do ngày_nay sự phụ_thuộc của Washington vào quan_hệ mậu_dịch với Bắc_Kinh ngày_càng lớn . 
Nói_tóm_lại , điều khó_khăn đối_với ông Bush là làm_sao thay_đổi hình_ảnh một người chỉ chăm_chăm vào vấn_đề Iraq và cuộc_chiến chống khủng_bố , nhất_định muốn rằng sự lớn_mạnh của Trung_Quốc không làm ảnh_hưởng đến cân_bằng lực_lượng an_ninh khu_vực và điều_khiển sự xuất_hiện trở_lại mối căng_thẳng giữa Nhật_Bản với các cựu_thù trong thế_chiến II - Hàn_Quốc và Trung_Quốc . 
 Người_ta đã quá mệt_mỏi với vấn_đề duy_nhất phát ra từ chính_quyền của ông Bush trong suốt nhiều năm nay , đặc_biệt là chuyện chống khủng_bố  , Edward_Lincoln , một học_giả nghiên_cứu về Nhật_Bản nói . 
 Họ cho rằng có nhiều thứ đáng nói ở khu_vực này hơn là câu_chuyện đó  . 
Tuy_nhiên , để duy_trì sự ủng_hộ trong nước , ông Bush vẫn phải giữ thăng_bằng : trong khi ủng_hộ mở_cửa thị_trường , ông phải đảm_bảo rằng sẽ không từ_bỏ quan_điểm của mình trong giải_quyết chuyện công_ăn_việc_làm trong ngành sản_xuất chế_tạo đua nhau chạy sang châu Á . 
Vì thế , ông Bush chọn cách nói về ký_ức thời mọi chuyện còn đơn_giản hơn : chuyến thăm Trung_Quốc của ông cách đây 30 năm , khi quan_hệ Trung - Mỹ đang ở giai_đoạn tan băng và Bush cha là một trong các thành_viên cấp cao đại_diện cho Mỹ ở Trung_Quốc . 
 Ai_ai cũng đi xe_đạp  , ông nhớ lại trong khi nói_chuyện với đài_truyền_hình Phượng_Hoàng của Trung_Quốc . 
 Tôi cũng cưỡi một chiếc đi khắp Bắc_Kinh . 
Thật là tuyệt  , Bush kể và nói thêm rằng  chắc người_ta nghĩ là trông tôi buồn_cười lắm  . 
�i lắm " . 
