Ukraine chính_thức giành vé sang Đức Ukraine - đội bóng đầu_tiên của khu_vực châu Âu giành vé sang Đức Trận hoà 2-2 của Thổ_Nhĩ_Kỳ trước Đan_Mạch đã giúp Ukraine đã làm nên lịch_sử với lần đầu_tiên ghi tên vào một VCK World_Cup . 
Lợi_thế của Ukraine trước lượt trận này là quá rõ_ràng , tuy_nhiên , trận hoà 1-1 trên SVĐ không người tại Tblisi trước Georgia không đủ giúp đội bóng đông Âu giành vé . 
Phải chờ đến khi trận_đấu muộn của bảng 2 kết_thúc , trận_đấu mà chủ_nhà Thổ_Nhĩ_Kỳ bị đội khách Đan_Mạch gỡ hoà vào phút chót , Ukraine mới chính_thức trở_thành đội bóng đầu_tiên tại châu Âu vượt_qua vòng loại để ghi tên vào danh_sách sang Đức trong mùa hè 2006 . 
Đáng_lẽ ra trước đó Ukraine đã có_thể tự mình giành vé đi Đức nếu_như không có bàn_thắng gỡ hoà của Gakhokidze ở phút 89 của trận_đấu . 
Tiền_vệ Gakhokidze của Georgia đã có pha sút phạt tuyệt đẹp từ cự_ly khoảng 25 mét hạ_gục thủ_thành Shovkovskyi_san bằng tỉ_số 1-1 . 
Trước đó , phút 44 , tiền_vệ Rotan đã đưa Ukraine vươn lên dẫn_điểm với pha dứt_điểm cận thành . 
Những_tưởng kết_quả hoà 1-1 sẽ khiến Ukraine phải chờ thêm một vòng đấu nữa mới có_thể giành vé . 
Tuy_nhiên , bất_ngờ cũng đã đến trong trận_cầu sau đó tại Istanbul khi Đan_Mạch cầm_chân chủ_nhà Thổ_Nhĩ_Kỳ , đội bóng xếp thứ 3 tại World_Cup 2002 với tỉ_số 2-2 . 
Claus_Jensen đưa Đan_Mạch dẫn_điểm ở phút 41 trước khi tiền_vệ vào sân thay người Okan_Buruk gõ hoà ngay đầu hiệp 2 . 
Đội chủ_nhà Thổ_Nhĩ_Kỳ dồn_ép Đan_Mạch trong suốt thời_gian thi_đấu của hiệp 2 và có được bàn_thắng vươn lên dẫn diểm 2-1 của Metin ở phút 81 . 
Nhưng trong phút thi_đấu cuối_cùng , pha dứt_điểm lạnh_lùng của tiền_đạo đang thi_đấu tại CLB Schalke_04 của Soren_Larsen đã đưa trận_đấu đến một kết_quả hoà 2-2 và giúp Ukraine chính_thức giành vé sang Đức . 
Với kết_quả này , Thổ_Nhĩ_Kỳ sẽ phải tiếp_tục  chiến_đấu  với Đan_Mạch ( 13 điểm ) và đội bóng nhì bảng Hy_Lạp ( 15 điểm ) để giành một suất tham_gia trận Play-off . 
Hai bàn_thắng của Mateja_Kezman ( 18 ' ) và Sasa_Ilic ( 75 ' ) giúp Serbia và Montenegro giành chiến_thắng 2-0 trước Lithuania , vượt_qua Tây_Ban_Nha để trở_thành đội dẫn_đầu bảng 7 ( hơn Tây_Ban_Nha , đội không thi_đấu tại vòng này 2 điểm ) . 
Ngoài niềm vui chiến_thắng và giành lại ngôi đầu từ Tây_Ban_Nha , Serbia và Montenegro còn lập thêm một kỷ_lục mới tại một vòng loại World_Cup với 7 trận_đấu không để thủng lưới ( thắng 4 , hoà 3 với hiệu_số 12/0 ) . 
Đáng ra Serbia và Montenegro phải giành được trận thắng đậm hơn nữa với những gì mà họ đã thể_hiện với những cơ_hội được tạo ra trước khung_thành Lithuania . 
Đội_trưởng Savo_Milosevic không_thể chiến_thắng thủ_môn Lithuania_Zydrunas_Karcemarskas trong tình_huống sút phạt 11 mét và pha dứt_điểm của tiền_vệ Stankovic ở cự_ly khoảng 6 mét sau đó bị một hậu_vệ Lithuania cản_phá ngay trên vạch vôi là 2 trong số rất nhiều cơ_hội  ngon_ăn  bị bỏ_lỡ . 
Tuy_nhiên , trận thắng 2-0 cũng đủ giúp Serbia và Montenegro tạo lợi_thế về điểm_số và cả chỉ_số phụ ( 12/0 ) . 
Với thành_tích này , đội bóng đông Âu hoàn_toàn tự_tin trước chuyến làm khách tại Madrid trước đội chủ_nhà Tây_Ban_Nha vào 7-9 tới , trận_đấu chắc_chắn sẽ ảnh_hưởng rất lớn tới tham_vọng tới Đức của đội bóng đông Âu . 
 Các cầu_thủ đã thi_đấu rất tuyệt trong trận_đấu này . 
Serbia và Montenegro đã trở_lại với vị_trí đầu_bảng và đây là điều đáng mừng . 
Tuy_nhiên , một thử_thách nữa đang chờ_đợi Serbia và Montenegro tại Madrid và chúng_tôi đã sẵn_sàng vượt_qua thử_thách này  - HLV_trưởng Ilija_Petkovic tự_tin cho_biết . 
�t . 
