Cuộc chạy_đua thu_hút khách của các bảo_tàng ở châu Âu 
Vì nếu_như Prado ở Madrid lần đầu cho công_chúng chiêm_ngưỡng những bộ sưu_tập ảnh thế_kỷ 19 thì British_Museum ở London cũng đã khánh_thành thêm gian Enlightenment_Gallery vinh_danh vai_trò của viện_bảo_tàng là những trung_tâm học_thuật . 
Trong những vật được trưng_bày ở gian này có cả những catalog sưu_tập thực_vật thế_kỷ 17 . 
Ông John_Lewis , chủ_tịch Wallace_Collection , một gallery ở London chuyên trưng_bày tranh , đồ sành_sứ và đồ gỗ thế_kỷ 17 và thế_kỷ 18 , nhận_xét . 
 Ngành bảo_tàng đang đi dần đến chỗ trở_thành một cánh_tay của các công_nghiệp giáo_dục và giải_trí , không còn chỉ giữ vai_trò gìn_giữ , bảo_quản đồ cổ nữa  . 
Bảo_tàng Victoria và Albert ở London nay mỗi ngày mở cửa đến 10 giờ đêm vì trong đó đã có thêm quán cà_phê , nhạc_sống , còn trong Bảo_tàng Berlin có cả sân_khấu biểu_diễn jazz , nhạc hoà_tấu và  rạp  chiếu phim ngoài trời . 
Một trong những nguyên_nhân dẫn đến sự bùng_nổ cuộc_chiến mới_lạ này là sự  phá bỏ  biên_giới giữa các nước đã giúp cư_dân Liên_minh châu Âu ( EU ) có nhiều điều_kiện đi_lại dễ_dàng hơn nên ngành du_lịch nội_địa EU đã thực_sự bùng_nổ mạnh . 
Khách du_lịch cũng có lúc vào thăm viện_bảo_tàng . 
Muốn hút được du_khách , mỗi bảo_tàng phải có  hàng quý_hiếm  riêng . 
Madrid tin rằng với tổng_vốn đầu_tư lên đến 226 triệu USD , cụm các bảo_tàng Prado , Reina_Sofia ( nghệ_thuật hiện_đại ) và Thyssen-Bornemisza ( sở_hữu bức Những thợ gặt của Picasso ) sẽ tăng thêm phần giá_trị mà sánh ngang bằng với British_Museum ở London . 
Nhưng không có công_cuộc mở_rộng , tân_trang bảo_tàng quy_mô lớn đầy tham_vọng nào bằng công_trình trùng_tu_Đảo Bảo_tàng ở trung_tâm thủ_đô Berlin . 
Được UNESCO công_nhận là một di_sản thế_giới ,  hòn đảo  này hiện thuộc dự_án trùng_tu có kinh_phí 2,1 tỉ USD . 
Bảo_tàng Louvre của Pháp Theo kế_hoạch thì khi hoàn_thành vào năm 2015 , Museum_Island sẽ trở_thành khu phức_hợp nghệ_thuật rộng_lớn nhất châu Âu và thuộc tốp 5 bảo_tàng lớn nhất thế_giới ( gồm Louvre ; Prado , British_Museum , Smithsonian ở Washington_D.C và Metropolitan_Museum ở New_York ) , trưng_bày đủ mọi nghệ phẩm của mọi nền văn_hoá với không_gian trưng_bày cộng chung là 88.000 m² . 
Ở bên kia bờ biển Manche , số tiền 243 triệu USD cũng đã được tiêu vào công_trình trùng_tu một trạm phát_điện cũ_kỹ thành một gallery nghệ_thuật đương_đại nằm sát cạnh Bảo_tàng Tate lừng_danh thế_giới ở London . 
Năm 2001 , tức chỉ một năm sau ngày khánh_thành , hiệu_quả kinh_tế mà Tate_Modern tạo ra cho nền kinh_tế địa_phương là rất rõ : thu_hút đám_đông đến tham_quan , tiêu_xài hết 200 triệu USD . 
Bộ_trưởng Văn_hoá Italia , ông Giuliano_Urbani có kế_hoạch đổi_mới Uffizi_Gallery ở Florence thành một điểm đến văn_hoá cấp thế_giới . 
Không_gian triển_lãm nghệ phẩm có kiểu kiến_trúc hình móng ngựa , được xây_dựng từ năm 1560 , sẽ được mở_rộng từ 6.000 m2 lên thành 13.000 m² , đủ chỗ cho việc trưng_bày 800 nghệ phẩm quý , trong đó có cả đầu của Goliath của Guido_Reni . 
Sau khi hoàn_tất vào năm 2006 và tiêu hết 72 triệu USD ,  Nuovo_Uffizi ( Uffizi mới ) sẽ đón 7.000 khách mỗi ngày , sẽ qua_mặt cả Louvre  - bộ_trưởng Urbani khoe . 
Nhưng Louvre vẫn còn ẩn_chứa những bí_mật . 
Chẳng_hạn như ngay lúc Kim_tự_tháp kính bắt_đầu được xây_dựng giữa khoảng sân lớn dẫn vào bảo_tàng khổng_lồ này vào năm 1989 , người_ta đồn rằng nó được dựng nên với 666 panô kính mà 666 chính là con_số biểu_trưng của quỷ Satan . 
Cuối_cùng , ông Jean-Bruno_Renard - một chuyên_gia xã_hội_học thành_thị đã phải mở cuộc điều_tra với kết_quả là tác_phẩm theo đơn đặt_hàng của ông Mitterrand thực_ra được ráp nên với 875 panô kính hình_thoi . 
�nh_thoi . 
