Đề_tài tự_do 
Tìm , chọn nội_dung đề_tài 
Có nhiều đề_tài để vẽ tranh như : 
Vui_chơi : nhảy_dây , đá_cầu , ... 
Lao_động : trồng cây , vệ_sinh trường lớp , đường_phố , ... 
Học_tập trên lớp , học nhóm , ... 
Hội đua thuyền , đấu vật , chọi gà , kéo_co , rước đèn , ... 
Cách vẽ tranh 
Vẽ các hình_ảnh chính làm rõ nội_dung . 
Tìm hình_dáng để thể_hiện được các hoạt_động . 
Vê các hình_ảnh phụ cho tranh thêm sinh_động . 
Vẽ màu theo ý_thích ( có màu đậm , màu nhạt ) . 
