Bảo_vệ bầu_không_khí trong_sạch 
Chúng_ta có_thể sử_dụng một_số cách chống ô_nhiễm không_khí như : thu_gom và xử_lí phân , rác hợp_lí , giảm lượng khí thải độc_hại của xe có động_cơ và của nhà_máy , giảm bụi , khói đun bếp , bảo_vệ rừng và trồng nhiều cây_xanh ... 
