Đổi_mới chương_trình đào tao ngành giáo_dục chính_trị ở các trường đại_học sư_phạm 
Nghị_quyết Trung_ương 8 khoá XI về đổi_mới căn_bản , toàn_diện giáo_dục - đào_tạo có ý_nghĩa vô_cùng to_lớn , đã thổi một luồng gió mới trong đời_sống chính_trị - xã_hội của nước ta hiện_nay . 
Nghị_quyết đặt ra hàng_loạt nhiệm_vụ bức_bách cần phải giải_quyết về giáo_dục - đào_tạo mà xã_hội đang quan_tâm , trong đó có các vấn_đề liên_quan trực_tiếp đến các trường đại_học sư_phạm , nơi đào_tạo đội_ngũ nhà_giáo , cán_bộ quản_lý giáo_dục phục_vụ sự_nghiệp giáo_dục của nước_nhà . 
Các vấn_đề đặt ra cần phải đổi_mới là : Đổi_mới mô_hình các trường sư_phạm , chương_trình , giáo_trình , phương_pháp giảng_dạy , cách_thức kiểm_tra , đánh_giá , công_tác đào_tạo , bồi_dưỡng giảng_viên ; ... ở tất_cả các ngành đào_tạo . 
Bài viết tập_trung trao_đổi về xây_dựng chương_trình đào_tạo ngành giáo_dục chính_trị ở các trường đại_học sư_phạm . 
Trước_hết , sản_phẩm của ngành giáo_dục chính_trị , các trường đại_học sư_phạm là những cử_nhân có_thể giảng_dạy môn giáo_dục_công_dân trong các trường trung_học_phổ_thông , các môn lý_luận chính_trị trong các trường trung_học nghề , trung_học_chuyên_nghiệp hoặc các trường cao_đẳng , đại_học ; có_thể tham_gia giảng_dạy , công_tác ở các cơ_sở đào_tạo , nghiên_cứu khoa_học , các cơ_quan lý_luận , tổ_chức chính_trị - xã_hội , ... 
Vì vậy , chương_trình đào_tạo ngành giáo_dục chính_trị ở các trường đại_học sư_phạm cần bảo_đảm mục_tiêu ấy . 
1 . 
Thực_trạng chương_trình ngành giáo_dục chính_trị ở các trường đại_học sư_phạm hiện_nay 
Ưu_điểm : 
Nội_dung chương_trình đã quán_triệt đường_lối về đổi_mới công_tác tư_tưởng , lý_luận của Đảng Cộng_sản Việt_Nam và đáp_ứng được nhu_cầu thực_tiễn đổi_mới của sự_nghiệp giáo_dục - đào_tạo . 
Về cơ_bản , mục_tiêu chương_trình đã đáp_ứng đúng quy_định của Luật Giáo_dục và đã được cụ_thể_hoá ở ba bình_diện : kiến_thức , kỹ_năng và thái_độ của người học , đã xác_định được chuẩn kiến_thức , kỹ_năng và thái_độ làm cơ_sở cho việc biên_soạn giáo_trình , cũng như kiểm_tra đánh_giá kết_quả học_tập của sinh_viên . 
Nội_dung chương_trình cũng đã đề_cập đến giáo_dục các giá_trị , chuẩn_mực chính_trị , chuẩn_mực đạo_đức , chuẩn_mực pháp_luật gắn liền với quyền và nghĩa_vụ cơ_bản của công_dân - sinh_viên , đã phần_nào thể_hiện được nguyên_tắc tích_hợp trong lĩnh_vực giảng_dạy . 
Kết_cấu chương_trình có phần mở , mang tính định_hướng , gợi_mở để người học có_thể liên_hệ lý_luận với thực_tiễn cuộc_sống của bản_thân và thực_tiễn đổi_mới đất_nước hiện_nay . 
Chương_trình đã bao_quát những nội_dung cơ_bản của chủ_nghĩa_Mác - Lênin , tư_tưởng Hồ_Chí_Minh và đường_lối cách_mạng của Đảng Cộng_sản Việt_Nam , bao_gồm những vấn_đề về văn_hoá và văn_minh , giáo_dục chính_trị với giáo_dục đạo_đức và giáo_dục pháp_luật , những vấn_đề về phương_pháp giảng_dạy và thực_hành sư_phạm , những vấn_đề kinh_tế , chính_trị , xã_hội khác , đáp_ứng đầy_đủ mục_tiêu của từng môn_học đã được đặt ra . 
Giáo_trình các môn_học thuộc ngành giáo_dục chính_trị , về cơ_bản , đã bám sát và cụ_thể_hoá mục_tiêu chương_trình , được biên_soạn một_cách công_phu , nghiêm_túc , bảo_đảm tính khoa_học và tính chính_trị , tính hệ_thống và lôgíc chặt_chẽ ; nội_dung chương_trình , giáo_trình phù_hợp với trình_độ của sinh_viên . 
Chính vì thế , chương_trình góp_phần quan_trọng vào việc xây_dựng thế_giới_quan , phương_pháp_luận khoa_học , nhân_sinh_quan cách_mạng , xây_dựng niềm tin và lý_tưởng cách_mạng cho sinh_viên , để từ đó họ nỗ_lực rèn_luyện và tu_dưỡng đạo_đức , trau_dồi chuyên_môn , phục_vụ công_tác dạy_học môn giáo_dục_công_dân ở các trường trung_học_phổ_thông , các môn lý_luận chính_trị trong các trường trung_học nghề , trung_học_chuyên_nghiệp hoặc các trường cao_đẳng , đại_học , đáp_ứng yêu_cầu đào_tạo nguồn nhân_lực trong sự_nghiệp công_nghiệp_hoá , hiện_đại_hoá đất_nước . 
Hạn_chế : 
Nội_dung chương_trình còn mang nặng tính kinh_viện , hàn_lâm với những lý_luận trừu_tượng , chưa bám sát thực_tiễn nóng_bỏng của thời_đại , của đất_nước . 
Chương_trình nặng về giáo_dục chính_trị , nhẹ về giáo_dục đạo_đức , pháp_luật và kỹ_năng sống ; trọng lý_thuyết , nhẹ thực_hành , ít liên_hệ với thực_tiễn cuộc_sống của bản_thân và đất_nước . 
Chẳng_hạn , trong các chương_trình còn dành nhiều thời_lượng cho các học_phần về các tác_phẩm kinh_điển , về lịch_sử triết_học , lịch_sử các học_thuyết kinh_tế , lịch_sử tư_tưởng xã_hội_chủ_nghĩa , ... 
Nội_dung chương_trình chưa chú_trọng đến việc hướng_dẫn tự học , tự nghiên_cứu và rèn_luyện kỹ_năng sư_phạm cho sinh_viên , chưa chú_trọng đến việc xây_dựng và bồi_dưỡng năng_lực khoa_học và phẩm_chất sư_phạm của sinh_viên , chưa cập_nhật được những thay_đổi của đất_nước và thời_đại . 
Nhiều nội_dung trong các học_phần có sự trùng_lặp . 
Thí_dụ : Những nguyên_lý cơ_bản của chủ_nghĩa_Mác - Lênin với triết_học Mác - Lênin , kinh_tế chính_trị Mác - Lênin và chủ_nghĩa_xã_hội khoa_học , đường_lối cách_mạng của Đảng Cộng_sản Việt_Nam với lịch_sử Đảng Cộng_sản Việt_Nam , lịch_sử các học_thuyết kinh_tế với lịch_sử kinh_tế quốc_dân , lịch_sử triết_học với lịch_sử tư_tưởng xã_hội_chủ_nghĩa , cơ_sở văn_hoá Việt_Nam với văn_hoá_học , ... 
Khối_lượng kiến_thức các môn_học quá lớn , thời_lượng dành cho các môn này lại không nhiều , trong khi việc tự học của sinh_viên lại chưa được phát_huy đã ảnh_hưởng đến chất_lượng và hiệu_quả của việc dạy các môn_học này . 
Nguồn kinh_phí đầu_tư riêng cho việc nghiên_cứu khoa_học trong lĩnh_vực giáo_dục chính_trị còn khiêm_tốn , trong khi đội_ngũ giảng_viên phải dạy quá nhiều giờ , vì vậy , ít có_điều_kiện đầu_tư nghiên_cứu khoa_học , đặc_biệt là những công_trình nghiên_cứu về đổi_mới nội_dung , chương_trình , giáo_trình chuyên_ngành giáo_dục chính_trị . 
Từ thực_trạng trên đây , việc đổi_mới chương_trình ngành giáo_dục chính_trị trong các trường đại_học sư_phạm đang được đặt ra một cách bức_thiết . 
2 . 
Định_hướng đổi_mới chương_trình ngành giáo_dục chính_trị ở các trường đại_học sư_phạm 
Chương_trình , giáo_trình ở các trường đại_học sư_phạm hiện_nay không_thể phủ_định sạch_trơn chương_trình , giáo_trình cũ , đồng_thời cũng không_thể lắp_ráp , rập_khuôn toàn_bộ chương_trình , giáo_trình cũ . 
Việc xây_dựng chương_trình , giáo_trình phải xuất_phát từ thực_tế đời_sống , từ nhu_cầu xã_hội , đáp_ứng yêu_cầu CNH , HĐH trong điều_kiện kinh_tế_thị_trường định_hướng XHCN và hội_nhập quốc_tế . 
Ở nhiều nước trên thế_giới , việc đổi_mới chương_trình , giáo_trình đại_học và chương_trình , sách_giáo_khoa phổ_thông được diễn_ra đồng_thời ; hoặc đổi_mới chương_trình , giáo_trình đại_học là cơ_sở , là hình_mẫu cho việc đổi_mới chương_trình , sách_giáo_khoa phổ_thông . 
Ở nước ta hiện_nay , do điều_kiện lịch_sử cụ_thể của đất_nước , với thực_tế giáo_dục phổ_thông có nhiều vấn_đề bức_xúc cần giải_quyết , cho_nên phải có bước đột_phá ngay trong việc xây_dựng chương_trình , sách_giáo_khoa phổ_thông . 
Có_thể nói , các cách thực_hiện trên đây cho_dù có khác_biệt về trình_tự , nhưng đều thống_nhất với nhau ở nguồn_gốc , đó là nội_dung chương_trình , giáo_trình , sách_giáo_khoa phải xuất_phát từ thực_trạng xã_hội , nhu_cầu xã_hội , từ yêu_cầu phát_triển của quốc_gia và thời_đại . 
Xuất_phát từ thực_trạng xã_hội , nhu_cầu xã_hội để xác_định mục_tiêu giáo_dục của các cấp học . 
Chẳng_hạn , ở cấp tiểu_học là phát_triển thói_quen về học_tập cơ_bản ; ở cấp trung_học_cơ_sở là bồi_dưỡng năng_lực cơ_bản và tố_chất của học_sinh ; ở cấp trung_học_phổ_thông là phát_triển năng_lực hướng_nghiệp phù_hợp với tố_chất của học_sinh . 
Trên cơ_sở mục_tiêu đã xác_định sẽ xây_dựng chương_trình và sách_giáo_khoa phổ_thông bằng cách tiếp_cận năng_lực và phẩm_chất của học_sinh ( tức_là giáo_dục cho học_sinh không phải chủ_yếu là nhồi_nhét kiến_thức mà là làm_sao cho học_sinh biết làm theo năng_lực và phẩm_chất của mình , thông_qua đó phát_triển năng_lực và phẩm_chất của mình . 
Xuất_phát từ mục_tiêu , chương_trình , sách_giáo_khoa phổ_thông để xác_định mục_tiêu , chương_trình , giáo_trình của trường đại_học sư_phạm . 
Cụ_thể là , mục_tiêu đào_tạo của trường đại_học sư_phạm là phát_triển các năng_lực khoa_học và phẩm_chất sư_phạm của sinh_viên - những giáo_viên tương_lai . 
Do vậy , chương_trình , giáo_trình của trường đại_học sư_phạm phải gắn_kết với chương_trình , sách_giáo_khoa phổ_thông , tức_là phải dạy những cái gì để sau này họ có_thể vận_dụng trong công_việc giáo_dục của mình . 
Do vậy , chương_trình , giáo_trình đối_với tất_cả các ngành nói_chung , ngành giáo_dục chính_trị nói_riêng phải được xây_dựng theocách tiếp_cận phát_triển năng_lực khoa_học ( tư_duy , nghiên_cứu , tự_chủ , sáng_tạo , ... ) và phẩm_chất sư_phạm ( ứng_xử , giao_tiếp , tổ_chức thực_hiện , ... ) của những giáo_viên tương_lai . 
Cho_nên , chương_trình ngành giáo_dục chính_trị không_chỉ phải khắc_phục tính hàn_lâm , kinh_viện , giáo_điều , mà_còn cần gia_tăng tính nghiệp_vụ , kỹ_năng sư_phạm cho sinh_viên . 
Mặt_khác , chương_trình cũng cần bảo_đảm tính tích_hợp và tính phân_hoá trong các môn_học . 
Như vậy , chương_trình sẽ rút_gọn được những môn_học không thực_sự quan_trọng , xa_rời thực_tiễn cuộc_sống , đồng_thời bổ_sung thêm những môn_học thiết_thực , nhất_là hình_thành các môn_học mang tính tích_hợp , tránh sự trùng_lắp , chồng_chéo giữa các môn_học . 
3 . 
Một_số nội_dung cơ_bản về đổi_mới chương_trình ngành giáo_dục chính_trị ở trường Đại_học Sư_phạm TP. Hồ_Chí_Minh 
Từ thực_trạng chương_trình ngành giáo_dục chính_trị hiện_nay nói_chung với những ưu_điểm và hạn_chế của nó , cùng với những định_hướng chủ_yếu trong việc xây_dựng chương_trình mới đáp_ứng việc bồi_dưỡng , phát_triển năng_lực khoa_học và phẩm_chất sư_phạm của sinh_viên , nêu một_số nội_dung cơ_bản trong việc đổi_mới chương_trình ngành giáo_dục chính_trị ở Trường Đại_học Sư_phạm TP. Hồ_Chí_Minh : 
Giảm bớt hoặc bỏ một_số học_phần mang tính_chất hàn_lâm , như tác_phẩm kinh_điển của chủ_nghĩa_Mác - Lênin , triết_học trong khoa_học tự_nhiên , lôgíc biện_chứng , lịch_sử kinh_tế quốc_dân , kinh_tế phát_triển , lịch_sử phong_trào cộng_sản và công_nhân quốc_tế , ... 
Tăng thời_lượng cho các học_phần đạo_đức_học , pháp_luật học , văn_hoá_học , lý_luận và phương_pháp dạy_học , ... 
Bổ_sung một_số học_phần mới như : giáo_dục kỹ_năng sống , giáo_dục sức_khoẻ vị_thành_niên , giáo_dục gia_đình , nghệ_thuật giao_tiếp , nghệ_thuật hùng_biện , các chuyên_đề đáp_ứng yêu_cầu của thực_tiễn cuộc_sống , ... 
Kết_hợp chương_trình giáo_dục chính_khoá với giáo_dục ngoài giờ , nghiên_cứu thực_tế ; kết_hợp truyền_bá kiến_thức với quá_trình rèn_luyện , hoạt_động thực_tiễn của sinh_viên , ... 
Bổ_sung thêm nội_dung về rèn_luyện phẩm_chất đạo_đức , coi kết_quả rèn_luyện phẩm_chất đạo_đức như là một trong những nội_dung học_tập , ... 
Bổ_sung những vấn_đề mới của thời_đại , những thành_tựu nghiên_cứu về khoa_học của nhân_loại , những vấn_đề thực_tiễn xã_hội để làm phong_phú thêm nội_dung chương_trình . 
Để đổi_mới chương_trình , giáo_trình ngành giáo_dục chính_trị trong các trường đại_học sư_phạm , vấn_đề có ý_nghĩa quyết_định là có sự quan_tâm của toàn xã_hội và các cơ_quan_chức_năng ; tinh_thần hợp_tác của các nhà hoạt_động giáo_dục ; đặc_biệt , mỗi giảng_viên thực_sự có trách_nhiệm với bản_thân mình , với nhà_trường , với xã_hội , với đất_nước , với người học và đặc_biệt phải có tấm lòng , có tình thương_yêu sâu_sắc và trách_nhiệm với các thế_hệ tương_lai . 
