Quan_hệ đặc_biệt Việt - Lào về quân_sự trong kháng_chiến chống thực_dân Pháp và đế_quốc Mỹ ( 1945-1975 ) 
Trong suốt chiều dài lịch_sử , hai đất_nước , hai dân_tộc Việt - Lào đã có mối quan_hệ gắn_bó khăng_khít . 
Đặc_biệt , từ tháng 8-1945 , khi nhân_dân và các lực_lượng vũ_trang hai nước , dưới sự lãnh_đạo chung của Đảng Cộng_sản Đông_Dương ( ở Lào do Xứ_uỷ lâm_thời Lào mới được lập lại giữa năm 1945 ) , đã nhất_tề đứng lên khởi_nghĩa giành chính_quyền , thì mối quan_hệ này có_điều_kiện phát_triển mạnh_mẽ và hiệu_quả . 
Trong những năm quân và dân hai nước chiến_đấu chống kẻ_thù chung là thực_dân Pháp , Đảng , Chính_phủ và Quân_đội nhân_dân Việt_Nam đã cử nhiều cán_bộ , chiến_sỹ quân_tình_nguyện sát_cánh cùng lực_lượng vũ_trang và nhân_dân các bộ_tộc Lào hoạt_động xây_dựng cơ_sở kháng_chiến , xây_dựng căn_cứ_địa , tổ_chức các đơn_vị vũ_trang địa_phương , phối_hợp đánh địch . 
Đó là các Đoàn 81 ( ở khu_vực Xiêng_Khoảng ) , Đoàn 82 ( ở khu_vực Bắc_Lào ) , Đoàn 83 ( ở khu_vực Viêng_Chăn ) và Đoàn 280 ( ở khu_vực Trung_Lào ) ... 
Sự hợp_tác về quân_sự trong cuộc kháng_chiến chống Pháp , giữa quân_đội và nhân_dân hai nước được_thể_hiện rõ_rệt và cụ_thể nhất là việc lãnh_đạo hai nước quyết_định phối_hợp mở chiến_dịch Thượng_Lào ( từ 13-4 đến 3-5-1953 ) . 
Tham_gia Bộ Chỉ_huy chiến_dịch là các đồng_chí lãnh_đạo cao nhất của Quân_đội Việt_Nam : Võ_Nguyên_Giáp , Nguyễn_Chí_Thanh , Hoàng_Văn_Thái ... 
Phía Lào có Hoàng_thân Xuphanuvông , đồng_chí Cayxỏn_Phômvihản . 
Trước khi vào chiến_dịch , ngày 3-4-1953 , Chủ_tịch Hồ_Chí_Minh đã gửi thư động_viên cán_bộ chiến_sĩ Việt_Nam tham_gia chiến_dịch : " ... 
Lần này là lần đầu_tiên các chú nhận một nhiệm_vụ quan_trọng và vẻ_vang ... tức_là giúp nhân_dân nước bạn . 
Mà giúp nhân_dân nước bạn tức_là mình tự giúp mình . 
Để làm_tròn nhiệm_vụ chiến_đấu , từ trên xuống dưới , các chú cần phải : Vượt mọi khó_khăn , thi_đua diệt địch , chiến_đấu anh_dũng ở bên đó cũng như bên ta ; Nêu cao tinh_thần quốc_tế , tôn_trọng chủ_quyền , tôn_trọng phong_tục tập_quán , kính_yêu nhân_dân nước bạn ; Tuyệt_đối giữ_gìn kỷ_luật , giữ_gìn danh_tiếng của Quân_đội nhân_dân Việt_Nam " ( 1 ) . 
Trải_qua 20 ngày_đêm sát_cánh chiến_đấu , Chiến_dịch Thượng_Lào đã giành được thắng_lợi to_lớn . 
Lực_lượng vũ_trang của hai nước đã loại khỏi vòng chiến_đấu khoảng 1/5 tổng_số lực_lượng địch ở Lào , giải_phóng hơn 4.000 km2 , gồm toàn_bộ tỉnh Sầm_Nưa , một phần tỉnh Xiêng_Khoảng và Phongxalỳ với hàng vạn dân . 
Lực_lượng kháng_chiến Lào mở_rộng địa_bàn đứng_chân . 
Từ đây , hậu_phương kháng_chiến của cách_mạng Lào đã nối thông với vùng tự_do của Việt_Nam . 
Lực_lượng vũ_trang Pathét_Lào ngày_càng được tôi_luyện trong chiến_đấu và trưởng_thành . 
Về phía Việt_Nam , chiến_thắng Thượng_Lào đã tạo ra thế_chiến lược mới cho cuộc kháng_chiến , mở_rộng quyền chủ_động chiến_lược không_chỉ ở khu_vực Bắc_bộ mà trên toàn miền Bắc Đông_Dương . 
Trong Đông Xuân 1953-1954 , bộ_đội và quân_tình_nguyện Việt_Nam tiếp_tục phối_hợp với bộ_đội Pathét_Lào mở các đòn tiến_công địch ở Trung_Lào , Hạ Lào , Thượng_Lào , phân_tán , xé_lẻ khối cơ_động chiến_lược đang tập_trung ở đồng_bằng Bắc_bộ của địch , góp_phần quan_trọng vào chiến_thắng Điện_Biên_Phủ lịch_sử , kết_thúc chiến_tranh . 
Sự phối_hợp chiến_đấu có hiệu_quả của quân_đội , nhân_dân hai nước Việt_Nam - Lào trong cuộc kháng_chiến chống thực_dân Pháp đã chứng_minh lời khẳng_định của Chủ_tịch Hồ_Chí_Minh tại Hội_nghị cán_bộ liên_minh Việt - Lào - Campuchia lần thứ nhất tháng 9-1952 : " Kháng_chiến của Việt_Nam , của Miên , của Lào là của chung của chúng_ta . 
Việt_Nam có kháng_chiến thành công thì Miên , Lào mới thắng_lợi và Miên , Lào có thắng_lợi thì Việt_Nam mới hoàn_toàn thắng_lợi . 
Việt_Nam , Miên , Lào như anh_em ruột_thịt trong nhà ... " . 
Sau khi cuộc kháng_chiến chống thực_dân Pháp kết_thúc thắng_lợi , nhân_dân và quân_đội hai nước Việt , Lào lại phải đương_đầu với một thế_lực đế_quốc hùng_mạnh và tàn_bạo nhất thế_giới là đế_quốc Mỹ âm_mưu chia_cắt lâu_dài , phá_hoại sự thống_nhất của Việt_Nam , áp_đặt chủ_nghĩa_thực_dân mới ở miền Nam Việt_Nam và Lào . 
Đảng , Chính_phủ và quân_đội Việt_Nam tiếp_tục cử các đơn_vị , cán_bộ , chiến_sĩ giúp Chính_phủ kháng_chiến Lào củng_cố vùng giải_phóng , xây_dựng lực_lượng vũ_trang Pathét_Lào , đấu_tranh với Chính_phủ Vương_quốc Lào thân Mỹ thực_hiện Hiệp_định Giơnevơ năm 1954 về Lào . 
Do Hiệp_định Giơnevơ 1954 quy_định , các đơn_vị Quân_tình_nguyện Việt_Nam từ tháng 11 - 1954 lần_lượt rút về nước . 
Từ đây , phương_thức hợp_tác , giúp_đỡ của Việt_Nam với cách_mạng Lào cũng thay_đổi cho phù_hợp với tình_hình mới . 
Trên cơ_sở trao_đổi , thống_nhất với Chính_phủ kháng_chiến và Bộ Quốc_phòng Lào về các vấn_đề chiến_lược cách_mạng và chiến_lược quân_sự , Đảng Lao_động Việt_Nam chủ_trương chuyển từ chế_độ Quân_tình_nguyện sang chế_độ cố_vấn quân_sự ( từ năm 1955 đổi gọi là chuyên_gia quân_sự ) và thực_hiện ở 3 cấp : Bộ Quốc_phòng giúp chung mọi mặt ; Trường Quân_chính giúp đào_tạo , huấn_luyện cán_bộ ; các đơn_vị địa_phương mỗi nơi có một tổ cố_vấn gồm một cán_bộ cấp tiểu_đoàn và một_số cán_bộ cấp đại_đội . 
Trung_ương Đảng ta xác_định phương_châm giúp bạn là : đoàn_kết , bình_đẳng , tôn_trọng chủ_quyền của bạn . 
Hết_sức đề_cao tinh_thần độc_lập , tự_chủ của bạn , ra_sức giúp_đỡ , bồi_dưỡng cán_bộ bạn tự đảm_đương nhiệm_vụ theo tinh_thần " cách_mạng Lào do nhân_dân , cán_bộ , chiến_sĩ Lào tự làm lấy là chủ_yếu ; tránh bao_biện làm thay , tránh chủ_quan , hấp_tấp " . 
Đoàn cố_vấn quân_sự của Bộ Quốc_phòng Việt_Nam , mang phiên_hiệu Đoàn 100 , được thành_lập tháng 7-1954 , có nhiệm_vụ giúp quân_đội Pathét_Lào trong tình_hình cách_mạng mới của bạn . 
Cán_bộ , thành_viên của Đoàn 100 được tuyển_chọn từ các cơ_quan thuộc Bộ_Tổng_tư_lệnh , các đại_đoàn chủ_lực ( đến giữa 1955 gọi là các sư_đoàn ) 308 , 304 , 312 , 316 , 320 , 351 , Trung_đoàn chủ_lực 42 của Liên_khu 3 và các tỉnh_đội Hải_Dương , Hà_Đông . 
Ngoài_ra , một_số cán_bộ Quân_tình_nguyện từng hoạt_động lâu_năm trên đất Lào , thuộc Bộ_Tư_lệnh Quân_tình_nguyện Mặt_trận Thượng_Lào ( sau khi rút về nước đổi thành_Bộ tư_lệnh Biên_phòng ) và một_số đồng_chí giỏi tiếng Lào làm phiên_dịch . 
Bên cạnh việc phối_hợp , giúp_đỡ về tổ_chức , biên_chế , giáo_dục chính_trị , trong huấn_luyện quân_sự , cán_bộ Đoàn 100 hướng_dẫn các đơn_vị chủ_lực của Lào luyện_tập thành_thạo 4 kỹ_thuật cơ_bản , nhất_là kỹ_thuật bắn súng ; nắm vững nguyên_tắc và vận_dụng tốt các hình_thức chiến_thuật từ tổ 3 người , tiểu_đội , trung_đội , đại_đội đến tiểu_đoàn . 
Ngày 22-3-1955 , Đại_hội thành_lập Đảng Nhân_dân Lào được triệu_tập , thông_qua đường_lối tiếp_tục lãnh_đạo nhân_dân các bộ_tộc Lào đoàn_kết đấu_tranh hoàn_thành nhiệm_vụ giải_phóng dân_tộc , xây_dựng một nước Lào hoà_bình , độc_lập , thống_nhất và phồn_vinh . 
Đại_hội đã bầu Ban lãnh_đạo Đảng toàn_quốc ( mang tính_chất một Ban Chấp_hành Trung_ương ) gồm 5 người , do đồng_chí Cayxỏn_Phômvihản làm Tổng_Bí_thư . 
Tháng 4-1955 , Ban lãnh_đạo Đảng toàn_quốc ra Nghị_quyết thành_lập Đảng_uỷ Quân_sự Trung_ương gồm 3 người , do đồng_chí Cayxỏn_Phômvihản làm Bí_thư và kiêm Chỉ_huy tối_cao các lực_lượng Pathét_Lào . 
Đây là điều_kiện thuận_lợi để Quân_uỷ hai nước Việt - Lào cùng hợp_tác , đoàn_kết giúp_đỡ lẫn nhau trong việc xây_dựng quân_đội và phối_hợp tác_chiến giữa Việt_Nam và Lào . 
Trong thời_gian từ năm 1955 đến năm 1958 , được sự chỉ_đạo trực_tiếp , chặt_chẽ của Trung_ương Đảng và Tổng_Quân_uỷ , các lực_lượng tham_gia hợp_tác , phối_hợp với phía Lào , đặc_biệt là Đoàn 100 , đã giúp bạn tiếp_tục xây_dựng lực_lượng , xây_dựng phương_án tác_chiến nhằm đánh_bại các cuộc tiến_công và lấn_chiếm của quân phái hữu_Viêng_Chăn , thực_hiện hoà_hợp dân_tộc ở Lào . 
Đầu năm 1958 , sau khi hoàn_thành nhiệm_vụ , Đoàn 100 được lệnh rút về nước , kết_thúc một giai_đoạn lịch_sử giúp bạn theo phương_thức mới của quân_đội ta trong những năm đầu sau Hiệp_định Giơnevơ về Lào . 
Đồng_chí Cayxỏn_Phômvihản đã chủ_trì tổ_chức trọng_thể Lễ tiễn Đoàn 100 . 
Đồng_chí đánh_giá cao sự hợp_tác , giúp_đỡ của Đoàn cố_vấn quân_sự đối_với cách_mạng Lào , đồng_thời khẳng_định Đảng Nhân_dân , quân_đội Pathét_Lào và nhân_dân các bộ_tộc Lào " mãi_mãi biết_ơn Đảng , nhân_dân và quân_đội Việt_Nam ; biết_ơn cán_bộ cố_vấn Đoàn 100 đã hết_lòng , hết_sức giúp_đỡ cách_mạng và quân_đội Lào ... 
Thời_gian sẽ đi qua nhưng tình_nghĩa Lào - Việt vẫn mãi_mãi sáng_ngời trong lịch_sử " ( 2 ) . 
Trong năm 1958 , tình_hình Lào có những diễn_biến phức_tạp . 
Đế_quốc Mỹ từng bước can_thiệp vào nội_bộ Lào , lập ra " Mặt_trận liên_minh chống cộng " , thành_lập " Đảng Tập_hợp Lào " . 
Tháng 8-1958 , Mỹ tổ_chức lật_đổ Chính_phủ Liên_hiệp có Pathét_Lào tham_gia , dựng lên chính_quyền thân Mỹ , đồng_thời tăng_cường xây_dựng đội quân nguỵ Lào từ 25 nghìn lên 40 nghìn người . 
Tháng 5-1959 , đế_quốc Mỹ huy_động 3 tiểu_đoàn bao_vây hòng tước vũ_khí của Tiểu_đoàn 2 Pathét_Lào ở Cánh_đồng Chum và Tiểu_đoàn 1 ở Xiêng_Ngân . 
Cán_bộ , chiến_sĩ Tiểu_đoàn 2 đã tìm cách vượt vòng_vây , tiến về hướng Đông , bắt liên_lạc được với các đơn_vị Việt_Nam . 
Hầu_hết lực_lượng Tiểu_đoàn 1 cũng đã bí_mật phân_tán , rút từng bộ_phận khỏi Xiêng_Ngân , chuyển đến vùng biên_giới Lào - Việt an_toàn . 
Trước tình_hình phức_tạp ở Lào , Đảng ta quyết_định thành_lập Đoàn cán_bộ Việt_Nam bên cạnh Trung_ương Đảng Nhân_dân Lào , đồng_thời tiếp_nhận lực_lượng Tiểu_đoàn 2 của bạn về đứng_chân ở miền Tây Nghệ_An . 
Đoàn cán_bộ Việt_Nam xây_dựng kế_hoạch giúp bạn chỉnh_đốn lực_lượng , bổ_sung quân_số , vũ_khí , lấy Tiểu_đoàn 2 làm nòng_cốt , phát_triển thành ba tiểu_đoàn mới , quân_số mỗi tiểu_đoàn khoảng 200 người . 
Trước yêu_cầu , nhiệm_vụ mới của cách_mạng Lào , theo đề_nghị của Đảng Nhân_dân Lào , ngày 12-9-1959 , Bộ Quốc_phòng - Tổng_tư_lệnh ra Quyết_định số 446/QĐ thành_lập Đoàn 959 ( còn gọi là Đoàn công_tác miền Tây ) trực_thuộc Bộ Quốc_phòng . 
Nhiệm_vụ của Đoàn là trực_tiếp làm chuyên_gia về quân_sự cho Quân_uỷ_Trung_ương và Bộ Chỉ_huy tối_cao quân_đội Pathét_Lào , tổ_chức chi_viện vật_chất cho cách_mạng Lào , trực_tiếp chỉ_huy các đơn_vị bộ_đội Việt_Nam hoạt_động ở khu_vực Sầm_Nưa , Xiêng_Khoảng và Viêng_Chăn . 
Đầu năm 1960 , đế_quốc Mỹ tiến_hành chiến_lược " Chiến_tranh đặc_biệt " ở Lào . 
Đoàn 959 đã cùng cơ_quan Trung_ương Đảng Nhân_dân Lào , Quân_uỷ và Bộ chỉ_huy tối_cao Pathét_Lào đang đứng_chân trên đất Việt_Nam trở_lại Lào . 
Hệ_thống tổ_chức chuyên_gia quân_sự Việt_Nam giúp bạn được tổ_chức lại gồm bộ_phận giúp Trung_ương Đảng và Quân_uỷ_Trung_ương Lào , các quân_khu , tỉnh và các đơn_vị quân_đội Pathét_Lào . 
Theo yêu_cầu của bạn , chuyên_gia quân_sự Việt_Nam tổ_chức thành hai bộ_phận : bộ_phận cơ_quan gồm có chuyên_gia tham_mưu , chính_trị , hậu_cần và công_tác hậu_phương ; bộ_phận trực_tiếp giúp bạn gồm chuyên_gia các khu , tỉnh_đội , các tiểu_đoàn , bệnh_viện và nhà_trường . 
Đoàn 959 đã tham_gia cùng các lực_lượng của bạn bố_trí đón và đưa Hoàng_thân Xuphanuvông và các vị lãnh_tụ Neo_Lào_Hắc_Xạt được giải_cứu khỏi trại_giam Phôn_Khêng , về căn_cứ an_toàn ( ngày 24-5-1960 ) . 
Phối_hợp tiến_công địch ở Sầm_Nưa giành thắng_lợi , tạo chỗ_đứng chân cho cơ_quan Trung_ương Đảng Nhân_dân Lào , Quân_uỷ và Bộ Chỉ_huy tối_cao quân_đội Pathét_Lào , xây_dựng căn_cứ_địa kháng_chiến . 
Đầu năm 1961 , đại_diện lãnh_đạo Đảng Lao_động Việt_Nam và Đảng Nhân_dân Lào tiến_hành hội_đàm , thống_nhất quan_hệ giữa hai Đảng theo 5 nguyên_tắc chung : sự_nghiệp cách_mạng Lào do nhân_dân các bộ_tộc Lào tiến_hành dưới sự lãnh_đạo của Đảng Nhân_dân Lào ; quan_hệ giữa hai Đảng là quan_hệ đồng_chí , bình_đẳng , đoàn_kết , tôn_trọng độc_lập , chủ_quyền , không can_thiệp vào công_việc nội_bộ của nhau ; chống tư_tưởng dân_tộc nước lớn và tư_tưởng dân_tộc hẹp_hòi ; chống bao_biện làm thay . 
Chống ỷ_lại , tự_ti và mọi biểu_hiện làm phương_hại đến tình đoàn_kết giữa hai Đảng và nhân_dân hai nước ( 3 ) . 
Trước tình_hình mới ở Lào , Quân_uỷ_Trung_ương và Bộ_Tổng_tư_lệnh xác_định nhiệm_vụ quốc_tế đối_với cách_mạng Lào trong 5 năm 1961-1965 : " Giúp_đỡ các lực_lượng cách_mạng Lào về chuyên_gia quân_sự , đào_tạo cán_bộ , củng_cố , xây_dựng vùng giải_phóng và phát_triển lực_lượng vũ_trang của bạn . 
Khi bạn có yêu_cầu , tổ_chức bộ_đội tình_nguyện Việt_Nam phối_hợp chiến_đấu với bộ_đội bạn " ( 4 ) . 
Giữa năm 1961 , phái_đoàn Chính_phủ Vương_quốc Lào do Thủ_tướng Xuvana_Phuma , Chủ_tịch Neo Lào_Hắc_Xạt_Xuphanuvông sang Hà_Nội hội_đàm với Chính_phủ Việt_Nam Dân_chủ Cộng_hoà . 
Hai bên đã ký Hiệp_định về việc Việt_Nam viện_trợ quân_sự giúp Lào . 
Theo đó , Việt_Nam cử_nhân_viên quân_sự sang giúp quân_đội Vương_quốc Lào , nhận đào_tạo tại Việt_Nam_sỹ quan và nhân_viên kỹ_thuật , đưa quân_tình_nguyện sang chiến_đấu khi cần_thiết . 
Sự hợp_tác , phối_hợp , giúp_đỡ về quân_sự giữa hai nước ngày_càng chặt_chẽ , hiệu_quả trong bối_cảnh đế_quốc Mỹ tiếp_tục can_thiệp mạnh vào Lào , huy_động cả quân Thái_Lan , quân Việt_Nam Cộng_hoà hỗ_trợ quân_đội phái hữu Lào . 
Sự lớn_mạnh của các lực_lượng vũ_trang và của cách_mạng Lào là nhân_tố quan_trọng thúc_đẩy việc các bên ở Lào ký Hiệp_định Cánh_đồng Chum ( 12-6-1962 ) , thành_lập Chính_phủ Liên_hiệp ba phái do Hoàng_thân Xuvana_Phuma làm Thủ_tướng , Hoàng_thân Xuphanuvông làm Phó_Thủ_tướng . 
Ngày 23-7-1962 , Hội_nghị quốc_tế Giơnevơ về Lào gồm 14 nước tham_dự đã ký Hiệp_định Giơnevơ về Lào . 
Các nước tham_gia ký Hiệp_định thừa_nhận tôn_trọng nền độc_lập , chủ_quyền , thống_nhất và toàn_vẹn lãnh_thổ của Lào . 
Ngày 5-9-1962 , hai nước Việt_Nam - Lào chính_thức thiết_lập quan_hệ ngoại_giao . 
Sự_kiện lịch_sử này đã mở ra một chương mới trong quan_hệ giữa hai nước . 
Nhân_dân và các lực_lượng vũ_trang yêu nước Lào đã phối_hợp chặt_chẽ với nhân_dân và quân_đội Việt_Nam kháng_chiến , chống kẻ_thù chung là đế_quốc Mỹ và tay_sai . 
Giai_đoạn 1960-1965 , thực_hiện sự thoả_thuận giữa hai Đảng , hai Chính_phủ , hai Quân_đội , Quân_uỷ_Trung_ương và Bộ_Tổng_tư_lệnh đã điều_động các Đoàn chuyên_gia quân_sự 959 , 463 ( khu_vực Cánh_đồng Chum - Xiêng_Khoảng ) , 763 ( khu_vực Hạ_Lào ) , các đơn_vị thuộc các Sư_đoàn 312 , 316 , 335 , 325 , 330 , 324 , 304 trực_thuộc Bộ , Quân_khu Tây_Bắc , Quân_khu 4 làm nhiệm_vụ quốc_tế tại Lào . 
Quân_tình_nguyện và chuyên_gia quân_sự Việt_Nam đã giúp bạn phát_triển lực_lượng chính_trị và vũ_trang , xây_dựng căn_cứ kháng_chiến , tạo nên bước phát_triển quan_trọng cho cách_mạng Lào ( 1962 ) và thế phối_hợp , chi_viện lẫn nhau giữa chiến_trường hai nước . 
Giai_đoạn từ năm 1965 đến năm 1968 , các đơn_vị quân_tình_nguyện và chuyên_gia quân_sự Việt_Nam tiếp_tục giúp bạn xây_dựng lực_lượng vũ_trang , đẩy_mạnh việc phối_hợp mở các chiến_dịch đánh địch , củng_cố vùng giải_phóng , góp_phần đánh_bại một bước quan_trọng chiến_lược " Chiến_tranh đặc_biệt " của đế_quốc Mỹ và tay_sai . 
Tiếp_theo , các lực_lượng vũ_trang hai nước đã phối_hợp chặt_chẽ , vượt_qua mọi khó_khăn , thử_thách , cùng chiến_đấu đánh_bại chiến_lược " Chiến_tranh đặc_biệt tăng_cường " của Mỹ ở Lào , chiến_lược " Việt_Nam_hoá chiến_tranh " ở Việt_Nam , biểu_hiện bằng thắng_lợi to_lớn trong chiến_dịch Đường 9 - Nam_Lào ( 2-1971 ) . 
Mỹ và chính_quyền Viêng_Chăn buộc phải ký Hiệp_định Viêng_Chăn ( 21-2-1973 ) về lập lại hoà_bình , hoà_hợp dân_tộc ở Lào . 
Từ năm 1973 đến năm 1975 , được sự phối_hợp và giúp_đỡ hiệu_quả của bộ_đội Việt_Nam , các lực_lượng vũ_trang yêu nước Lào đã đấu_tranh buộc kẻ_thù phải thực_hiện Hiệp_định Viêng_Chăn , giữ vững hoà_bình , tạo thế , tạo lực tiến_lên thực_hiện thắng_lợi 3 đòn chiến_lược , kết_thúc thắng_lợi cuộc kháng_chiến chống Mỹ ở Lào cuối năm 1975 . 
Thắng_lợi của cuộc kháng_chiến chống Mỹ tại Lào là thắng_lợi của tình đoàn_kết chiến_đấu đặc_biệt Việt - Lào . 
Sự phối_hợp , giúp_đỡ lẫn nhau giữa các đơn_vị Quân_tình_nguyện Việt_Nam và các đoàn chuyên_gia quân_sự với các đơn_vị thuộc lực_lượng vũ_trang yêu nước Lào trong suốt cuộc kháng_chiến là minh_chứng sống_động và tiêu_biểu về mối quan_hệ đặc_biệt giữa quân_đội hai nước . 
Hàng vạn cán_bộ , chiến_sĩ Việt_Nam đã hy_sinh trên chiến_trường Lào vì độc_lập , tự_do , thống_nhất của cả hai nước . 
Sự hợp_tác của quân_đội và nhân_dân các bộ_tộc Lào trong việc mở đường , bảo_vệ tuyến đường vận_tải chiến_lược Hồ_Chí_Minh phía Tây Trường_Sơn , việc các đơn_vị Quân_đội nhân_dân Lào phối_hợp mở các chiến_dịch tiến_công , phòng_ngự trên các mặt_trận ở Lào , việc các đơn_vị Việt_Nam được sử_dụng đất Lào làm căn_cứ bàn_đạp về hậu_cần , lực_lượng cho cuộc_chiến_đấu ở miền Nam Việt_Nam ... là biểu_tượng cao_đẹp của mối quan_hệ đoàn_kết , giúp_đỡ lẫn nhau trong kháng_chiến . 
Sự hợp_tác về quân_sự giữa Việt_Nam và Lào trong hai cuộc kháng_chiến chống Pháp , chống Mỹ là một tất_yếu khách_quan và trở_thành điển_hình mẫu_mực về quan_hệ đoàn_kết , liên_minh chiến_đấu giữa quân_đội hai nước có độc_lập , chủ_quyền , tôn_trọng và tin_cậy lẫn nhau . 
Tổng_Bí_thư Lê_Duẩn đã đánh_giá mối quan_hệ chiến_đấu đặc_biệt giữa quân_đội hai nước Việt - Lào là " mối quan_hệ mẫu_mực hiếm có , vô_cùng trong_sáng , rất_mực thuỷ_chung , gian_khó không đổi_thay , đạn bom không lay_chuyển " . 
Trong bối_cảnh mới , sau chiến_tranh , nhận_thức sâu_sắc về ý_nghĩa và tầm quan_trọng của mối quan_hệ đặc_biệt Việt_Nam - Lào , ngày 18-7-1977 , hai nước đã ký Hiệp_định Hữu_nghị và Hợp_tác , khẳng_định tình đoàn_kết đặc_biệt trước_sau_như_một , hợp_tác , ủng_hộ , giúp_đỡ lẫn nhau trong sự_nghiệp xây_dựng và bảo_vệ Tổ_quốc của mỗi nước . 
Sự hợp_tác về quân_sự , quốc_phòng , an_ninh giữa Việt_Nam và Lào tiếp_tục được tăng_cường chặt_chẽ và hiệu_quả , góp_phần đảm_bảo vững_chắc sự ổn_định chính_trị , trật_tự an_toàn xã_hội của mỗi nước , làm thất_bại mọi âm_mưu và hành_động của các thế_lực thù_địch đang tìm cách xuyên_tạc , chia_rẽ quan_hệ giữa hai Đảng , hai Nhà_nước , hai Quân_đội và nhân_dân hai nước . 
