Hợp_tác giáo_dục và phát_triển nguồn nhân_lực Việt_Nam - Lào 
Trong 7 năm gần đây đã có 5.234 lưu_học_sinh Lào đang học_tập tại các cơ_sở giáo_dục và đào_tạo Việt_Nam . 
Trong đó có 1.982 người thuộc diện được hưởng học_bổng của hai Chính_phủ , 914 người diện tự_túc kinh_phí , 2.099 người học theo học_bổng trao_đổi giữa các địa_phương , các ngành , 61 người đi học theo học_bổng của các tổ_chức quốc_tế tài_trợ và 177 người nhận học_bổng của các dự_án , công_ty . 
Việt_Nam - Lào là hai nước láng_giềng thân_thiện gần_gũi , có chung hàng nghìn kilômét đường biên_giới , cùng dùng chung dòng nước Mêkông , cùng dựa lưng vào dãy Trường_Sơn hùng_vĩ và có truyền_thống đoàn_kết anh_em từ lâu_đời để làm_ăn sinh_sống . 
Quan_hệ đoàn_kết gắn_bó đặc_biệt , giúp_đỡ lẫn nhau trên tình đồng_chí anh_em trong_sáng , thuỷ_chung trong suốt hơn nửa thế_kỷ qua , là tài_sản quý_giá của hai Đảng , hai Nhà_nước và nhân_dân hai nước Việt_Nam - Lào . 
Trong lĩnh_vực giáo_dục - đào_tạo , sự hợp_tác giúp_đỡ lẫn nhau giữa hai nước Việt - Lào cũng đã có bề dày lịch_sử . 
Từ buổi ban_đầu của thời_kỳ cách_mạng , hai nước cùng chiến_đấu chung trong một chiến_hào , bộ_đội tình_nguyện Việt_Nam đã dạy chữ cho các chiến_sỹ cách_mạng Lào , giúp cho nhiều người sau này trở_thành những cán_bộ ưu_tú , những người chỉ_huy tài_năng . 
Tại vùng giải_phóng Lào , nhiều cán_bộ giáo_dục tình_nguyện Việt_Nam đã sang giúp bạn phát_triển giáo_dục , từ bậc tiểu_học , phổ_thông_trung_học , trung_học_chuyên_nghiệp , đến cao_đẳng và đại_học . 
Cùng với việc xây_dựng hệ_thống giáo_dục tại vùng giải_phóng Lào , ngay từ năm 1958 , Việt_Nam đã đón_nhận hàng trăm con_em các bộ_tộc Lào sang học_tập tại các trường dân_tộc nội_trú . 
Dù trong khói_lửa ác_liệt của cuộc đấu_tranh giải_phóng dân_tộc , Việt_Nam đã xây_dựng một_số trường phổ_thông dân_tộc nội_trú , trường trung_cấp chuyên_nghiệp và các trường đào_tạo cán_bộ cho Lào . 
Từ năm 1958 đến 1964 , Việt_Nam đã đào_tạo cho Lào 3.104 lưu_học_sinh , chủ_yếu theo học hệ bổ_túc_văn_hoá . 
Sau khi tốt_nghiệp , một phần lưu_học_sinh trở_về công_tác tại vùng giải_phóng của Lào , số còn_lại được tiếp_tục gửi đi học ở các trường sư_phạm của Việt_Nam để trở_thành giáo_viên cấp II. Từ năm 1965 đến 1974 , khi cuộc kháng_chiến chống đế_quốc Mỹ xâm_lược bước vào thời_kỳ ác_liệt nhất , mặc_dù gặp rất nhiều khó_khăn , Việt_Nam vẫn tiếp_tục nuôi_dưỡng và đào_tạo lưu_học_sinh Lào với tinh_thần " hạt gạo cắn đôi , cọng rau bẻ nửa " . 
Trong thời_gian này , Việt_Nam đã đào_tạo được 4 nghìn học_sinh từ các vùng giải_phóng Lào sang theo học cấp I , cấp II và cấp III._Sau khi cuộc kháng_chiến chống Mỹ cứu nước giành thắng_lợi hoàn_toàn , cả hai nước bước vào công_cuộc xây_dựng CNXH , ngày 18-7-1977 Việt_Nam và Lào đã ký Hiệp_ước Hữu_nghị và Hợp_tác , trong đó quan_tâm rất nhiều đến nội_dung về giáo_dục và đào_tạo . 
Trong giai_đoạn này , Chính_phủ Lào chủ_trương giảm số học sinh cấp I , II và tăng_cường đào_tạo học_sinh cấp III , đào_tạo đại_học và trung_học_chuyên_nghiệp tại Việt_Nam . 
Các chương_trình hợp_tác trong lĩnh_vực giáo_dục giai_đoạn này mang tính_chất " ngành giúp ngành " và Việt_Nam đã đáp_ứng mọi yêu_cầu của Lào cả về số_lượng , trình_độ , ngành_nghề đào_tạo . 
Từ năm 1992 đến nay , trên cơ_sở Hiệp_định hợp_tác về kinh_tế , văn_hoá , giáo_dục và khoa_học - kỹ_thuật được ký_kết giữa Chính_phủ Việt_Nam và Chính_phủ Lào , Bộ Giáo_dục và Đào_tạo Việt_Nam , Bộ Giáo_dục và Thể_thao Lào đã ký_kết các kế_hoạch hợp_tác về giáo_dục - đào_tạo , nhằm giúp Lào phát_triển các cơ_sở giáo_dục , đào_tạo cán_bộ ( trong đó chủ_yếu tập_trung trình_độ đại_học và sau_đại_học ) , trao_đổi đoàn công_tác để học_tập kinh_nghiệm về công_tác quản_lý giáo_dục và nâng_cao trình_độ đội_ngũ cán_bộ , giáo_viên . 
Trong 10 năm gần đây , mỗi năm số_lượng học_sinh , học_viên Lào được gửi sang đào_tạo tại Việt_Nam theo diện Hiệp_định được duy_trì từ 550 đến 650 người . 
Từ năm 2005 đến nay , với chủ_trương mở_rộng và đa_dạng_hoá các chương_trình hợp_tác giáo_dục - đào_tạo như : hợp_tác đào_tạo bằng nhiều kênh , nhiều hình_thức , coi_trọng hợp_tác đào_tạo giữa các địa_phương , các cơ_sở đào_tạo và các doanh_nghiệp nhằm xây_dựng nền_tảng mới cho sự phát_triển nguồn nhân_lực phục_vụ nhu_cầu hợp_tác và phát_triển kinh_tế - xã_hội của mỗi nước . 
Vì vậy , học_sinh , học_viên Lào được gửi sang đào_tạo tại Việt_Nam ngày_càng trở_nên đa_dạng và phong_phú về hình_thức cũng như quy_mô đào_tạo . 
Trong 7 năm gần đây đã có 5.234 lưu_học_sinh Lào đang học_tập tại các cơ_sở giáo_dục và đào_tạo Việt_Nam . 
Trong đó có 1.982 người thuộc diện được hưởng học_bổng của hai Chính_phủ , 914 người diện tự_túc kinh_phí , 2.099 người học theo học_bổng trao_đổi giữa các địa_phương , các ngành , 61 người đi học theo học_bổng của các tổ_chức quốc_tế tài_trợ và 177 người nhận học_bổng của các dự_án , công_ty . 
Từ năm 1958 đến nay , gần 30 nghìn lưu_học_sinh Lào được đào_tạo tại Việt_Nam , trong đó có hàng trăm thạc_sĩ , tiến_sĩ đã tốt_nghiệp các ngành , nghề khác nhau . 
Đội_ngũ cán_bộ quản_lý và chuyên_gia trong nhiều lĩnh_vực khoa_học - công_nghệ của Lào được đào_tạo tại Việt_Nam đã và đang có những đóng_góp to_lớn vào sự_nghiệp xây_dựng và bảo_vệ đất_nước Lào . 
Nhiều đồng_chí sau khi học_tập , bồi_dưỡng tại Việt_Nam , trở_về nước công_tác đã trở_thành những cán_bộ lãnh_đạo chủ_chốt trong nhiều ngành , nhiều lĩnh_vực quan_trọng từ Trung_ương đến địa_phương . 
Bên cạnh công_tác đào_tạo và phát_triển nguồn nhân_lực , ngành giáo_dục Việt_Nam còn giúp_đỡ bạn trong đầu_tư xây_dựng cơ_sở vật_chất , hệ_thống trường_học . 
Bộ Giáo_dục và Đào_tạo Việt_Nam đã và đang giúp Lào xây_dựng hệ_thống trường dân_tộc nội_trú gồm 7 trường được trải dài từ Bắc đến Nam , với tổng_mức đầu_tư hàng trăm tỷ đồng bằng nguồn viện_trợ không hoàn lại của Chính_phủ Việt_Nam . 
Ngoài_ra , còn xây_dựng 2 trường phổ_thông , 1 ký_túc_xá cho Đại_học Quốc_gia Lào , 1 trường nghề tại tỉnh Bokẹo . 
Tại Việt_Nam , Chính_phủ đã đầu_tư xây_dựng 9 ký_túc_xá dành riêng cho lưu_học_sinh Lào ở các trường đại_học , học_viện , với tổng_kinh_phí 84,715 tỷ đồng . 
Việc cung_cấp , hỗ_trợ sách , giúp_đỡ biên_soạn chương_trình , tài_liệu giảng_dạy , biên_soạn Bộ từ_điển Việt - Lào , Lào - Việt ; hỗ_trợ chuyên_gia trong hợp_tác nghiên_cứu khoa_học và liên_kết đào_tạo giữa các cơ_sở đào_tạo hai nước cũng được quan_tâm . 
Về phía Lào , trong điều_kiện còn nhiều khó_khăn , ngay từ năm 1982 Chính_phủ Lào đã dành một_số học_bổng cho cán_bộ , học_sinh Việt_Nam sang học_tập về ngôn_ngữ , văn_học Lào . 
Đến nay đã có 449 lưu_học_sinh Việt_Nam được sang học_tập tại nước bạn Lào bằng học_bổng do Chính_phủ Lào cấp . 
Trước yêu_cầu phát_triển của hai nước trong giai_đoạn mới , việc nâng_cao chất_lượng và hiệu_quả đào_tạo nguồn nhân_lực chất_lượng cao cho Lào là nhiệm_vụ chính_trị quan_trọng , có ý_nghĩa chiến_lược của hợp_tác giáo_dục và đào_tạo trong giai_đoạn 2011 - 2020 . 
Chính_phủ hai nước đã thống_nhất giao Bộ Giáo_dục và Đào_tạo Việt_Nam và Bộ Giáo_dục và Thể_thao Lào xây_dựng Đề_án " Nâng_cao chất_lượng và hiệu_quả hợp_tác Việt - Lào trong lĩnh_vực giáo_dục phát_triển nguồn nhân_lực giai_đoạn 2011 - 2020 " với nội_dung căn_bản là : nâng_cao chất_lượng đầu_vào tuyển_sinh theo các chương_trình hợp_tác ; bồi_dưỡng trình_độ tiếng Việt , trình_độ văn_hoá cơ_bản cho lưu_học_sinh Lào để đáp_ứng được yêu_cầu học_tập và nghiên_cứu khoa_học ; sắp_xếp ngành_nghề đào_tạo lưu_học_sinh xuất_phát từ nhu_cầu phát_triển kinh_tế - xã_hội và quy_hoạch cán_bộ của Lào ; phối_hợp giúp_đỡ lưu_học_sinh Lào vượt_qua khó_khăn trong học_tập và sinh_hoạt ; tăng_cường cơ_sở vật_chất của các trường có lưu_học_sinh Lào để đáp_ứng được yêu_cầu nâng_cao chất_lượng đào_tạo . 
Sau khi Đề_án được phê_duyệt , Bộ Giáo_dục và Đào_tạo Việt_Nam đã khẩn_trương triển_khai các dự_án . 
Đến nay đã hoàn_thành và tổ_chức tổng_kết , bàn_giao bộ Từ_điển Việt - Lào , Lào - Việt , bàn_giao cho Bộ Giáo_dục và Thể_thao Lào bộ giáo_trình dạy tiếng Việt để sử_dụng chính_thức từ năm_học 2011 - 2012 . 
Khởi_công xây_dựng Khoa Tiếng Việt của Trường Đại_học quốc_gia Lào , Trường phổ_thông_trung_học tỉnh Luôngphabăng , Trường phổ_thông dân_tộc nội_trú tỉnh Xiêngkhoảng ; Dự_án tăng_cường năng_lực giai_đoạn 2 xây_dựng Trường phổ_thông_trung_học Hữu_nghị Lào - Việt ( quà_tặng của Đảng Cộng_sản Việt_Nam cho Thủ_đô Viêng_Chăn ) cũng đang được gấp_rút hoàn_thành , dự_kiến sẽ khánh_thành vào quý III năm 2012 . 
Nhận_thức được tầm quan_trọng và ý_nghĩa đặc_biệt trong mối quan_hệ hợp_tác giữa hai nước , Bộ Giáo_dục và Đào_tạo Việt_Nam luôn coi_trọng chất_lượng và hiệu_quả trong mỗi chương_trình hợp_tác . 
Điều này đã được quán_triệt và thấm_nhuần tới từng đơn_vị , từng cơ_sở đào_tạo đang làm nhiệm_vụ giúp bạn . 
Trong thời_gian tới , nhằm nâng_cao chất_lượng và hiệu_quả hợp_tác Việt_Nam - Lào trong lĩnh_vực giáo_dục và phát_triển nguồn nhân_lực giai_đoạn 2011 - 2020 , Bộ Giáo_dục và Đào_tạo Việt_Nam cùng với Bộ Giáo_dục và Thể_thao Lào nghiêm_túc thực_hiện Nghị_định_thư về hợp_tác đào_tạo giữa hai nước và tiếp_tục triển_khai có hiệu_quả các chương_trình hợp_tác về giáo_dục , với các nội_dung cơ_bản sau : 
Thứ nhất , quan_tâm đào_tạo cán_bộ quản_lý , cán_bộ thực_hiện các dự_án , chương_trình hợp_tác giữa hai nước ; có chính_sách đào_tạo lại , đào_tạo sau_đại_học và đào_tạo đại_học chất_lượng cao phù_hợp với xu_thế phát_triển kinh_tế và hội_nhập quốc_tế của Lào . 
Tăng số_lượng đào_tạo lưu_học_sinh diện Hiệp_định giữa hai Chính_phủ ( trung_bình 10 % năm ) . 
Thứ hai , đổi_mới phương_pháp tuyển_sinh và đào_tạo dự_bị đại_học , nâng_cao trình_độ tiếng Việt cho lưu_học_sinh Lào . 
Bắt_đầu từ năm 2012 , lưu_học_sinh sang học tại Việt_Nam được Bộ Giáo_dục và Thể_thao Lào xét_tuyển trong số các sinh_viên đang học năm thứ nhất của 5 trường đại_học của Lào và các học_sinh xuất_sắc tốt_nghiệp trung_học_phổ_thông của các trường dân_tộc nội_trú , các trường phổ_thông_trung_học do Việt_Nam giúp xây_dựng . 
Từ năm 2012 đến năm 2020 , Bộ Giáo_dục và Đào_tạo Việt_Nam sẽ cử 28 đến 40 giáo_viên sang giảng_dạy và bồi_dưỡng phương_pháp dạy tiếng Việt cho các giáo_viên tại các trường dân_tộc nội_trú và trường phổ_thông do Việt_Nam giúp_đỡ xây_dựng . 
Học_sinh Lào trúng_tuyển đi học đại_học hoặc sau_đại_học tại Việt_Nam sẽ được học dự_bị tiếng Việt cơ_sở 1 năm tại Khoa Tiếng Việt của Đại_học Quốc_gia Lào ; sau đó học tiếng Việt nâng_cao và dự_bị kiến_thức chuyên_ngành 1 năm ở Việt_Nam trước khi vào các trường đại_học hay học_viện . 
Thứ ba , thống_nhất quản_lý đào_tạo dài hạn chính_quy các ngành chính_trị , kinh_tế , văn_hoá , giáo_dục và khoa_học - kỹ_thuật vào một đầu_mối nhằm đảm_bảo chất_lượng đào_tạo và hiệu_quả sử_dụng sau đào_tạo . 
Nhìn lại chặng đường lịch_sử hợp_tác Việt_Nam - Lào từ khi hai nước thiết_lập quan_hệ ngoại_giao , mối quan_hệ giữa hai Đảng , hai Nhà_nước và nhân_dân hai dân_tộc Việt - Lào luôn được gìn_giữ và phát_triển cả về chiều rộng lẫn chiều sâu , được_thể_hiện qua nhiều lĩnh_vực , trong đó rất đáng trân_trọng là sự hợp_tác chặt_chẽ và hiệu_quả trong lĩnh_vực giáo_dục và đào_tạo . 
Những kết_quả đó đã minh_chứng cho tình đoàn_kết , hữu_nghị , gắn_bó , thuỷ_chung , bền_vững , ngày_càng phát_triển , trở_thành tài_sản vô_giá của hai dân_tộc . 
Năm 2012 , Năm Đoàn_kết Hữu_nghị Việt_Nam - Lào , Kỷ_niệm 50 năm thiết_lập quan_hệ ngoại_giao và 35 năm ngày ký Hiệp_ước hữu_nghị hợp_tác Việt_Nam - Lào , lãnh_đạo Đảng , Chính_phủ hai nước khẳng_định tiếp_tục duy_trì , đẩy_mạnh quan_hệ hợp_tác trên tất_cả các lĩnh_vực từ chính_trị , đối_ngoại , quốc_phòng , an_ninh đến kinh_tế , thương_mại , đầu_tư , văn_hoá , giáo_dục ... 
Với quyết_tâm cao của Bộ Giáo_dục và Đào_tạo Việt_Nam và Bộ Giáo_dục và Thể_thao Lào trong việc nâng_cao chất_lượng và hiệu_quả trong hợp_tác giáo_dục - đào_tạo giai_đoạn 2011 - 2020 , chúng_ta tin_tưởng sâu_sắc rằng hợp_tác giáo_dục đào_tạo giữa hai nước sẽ ngày_càng phát_triển , góp_phần tích_cực phục_vụ sự_nghiệp đổi_mới , phát_triển kinh_tế và hội_nhập quốc_tế , không ngừng vun_đắp cho truyền_thống đoàn_kết hữu_nghị đặc_biệt và hợp_tác toàn_diện Việt_Nam - Lào ngày_càng đơm hoa kết trái . 
