Một_số giải_pháp về công_tác tư_tưởng nhằm ngăn_chặn , đẩy_lùi sự suy_thoái trong cán_bộ , đảng_viên hiện_nay 
Trong 30 năm đổi_mới , công_tác tư_tưởng được Đảng và Nhà_nước ta đặc_biệt coi_trọng và tăng_cường , góp_phần tạo sự thống_nhất trong Đảng , sự đồng_thuận xã_hội về các chủ_trương , đường_lối của Đảng , chính_sách , pháp_luật của Nhà_nước ; trong đó đã coi_trọng rèn_luyện phẩm_chất đạo_đức cách_mạng ; chống chủ_nghĩa_cá_nhân ; chỉ_đạo , tổ_chức triển_khai đạt kết_quả bước_đầu trong thực_hiện Cuộc vận_động học_tập và làm theo tấm gương đạo_đức Hồ_Chí_Minh vàTiếp tục đẩy_mạnh việc học tập và làm theo tấm gương đạo_đức Hồ_Chí_Minh gắn với nhiệm_vụ xây_dựng Đảng . 
Tuy_vậy , công_tác tư_tưởng còn thiếu sắc_bén , sức thuyết_phục chưa cao , tính chiến_đấu còn hạn_chế ; công_tác giáo_dục tư_tưởng chính_trị chưa đạt hiệu_quả cao . 
Tình_trạng suy_thoái về tư_tưởng chính_trị , đạo_đức , lối sống trong một bộ_phận không nhỏ cán_bộ , đảng_viên , trong đó có những đảng_viên giữ vị_trí lãnh_đạo , quản_lý , kể_cả một_số cán_bộ cao_cấp còn ở mức nghiêm_trọng . 
Mặc_dù vấn_đề này được Nghị_quyết Trung_ương 4 khoá XI xác_định là một trong ba vấn_đề cấp_bách , cần làm ngay để củng_cố niềm tin của cán_bộ , đảng_viên và nhân_dân , song , cho đến nay " Tình_trạng suy_thoái về tư_tưởng chính_trị , đạo_đức , lối sống của một bộ_phận cán_bộ , đảng_viên chưa được đẩy_lùi ; có mặt , có bộ_phận còn diễn_biến phức_tạp hơn " ( 1 ) . 
Trước yêu_cầu của cuộc đấu_tranh ngăn_chặn , đẩy_lùi tình_trạng suy_thoái về đạo_đức , lối sống trong Đảng , cần kiên_quyết , kiên_trì thực_hiện các giải_pháp đồng_bộ mà Nghị_quyết Trung_ương 4 khoá XI đã nêu . 
Dưới đây xin đề_xuất một_số giải_pháp sau : 
Thứ nhất , đẩy_mạnh công_tác nghiên_cứu lý_luận về đạo_đức và tổng_kết thực_tiễn việc ngăn_chặn , đẩy_lùi sự suy_thoái về đạo_đức , lối sống của cán_bộ , đảng_viên 
Nghiên_cứu , phát_triển lý_luận đạo_đức cách_mạng phải xuất_phát từ thực_tiễn , tổng_kết thực_tiễn . 
Vì đây là cách tốt nhất để bổ_sung , phát_triển lý_luận đạo_đức cách_mạng . 
Hiện_nay , lý_luận đạo_đức cách_mạng của chúng_ta còn lạc_hậu , chưa theo kịp với sự phát_triển của hoàn_cảnh thực_tiễn , nhiều quan_niệm đạo_đức đã trở_thành lạc_hậu , nhiều chuẩn_mực đạo_đức đã mất đi chân_giá_trị và không còn phù_hợp trong điều_kiện mới . 
Sự lạc_hậu của lý_luận đạo_đức và sự yếu_kém trong công_tác nghiên_cứu phát_triển lý_luận đạo_đức , vô_hình_trung đã làm cái cũ , lạc_hậu vẫn bền_bỉ tồn_tại một_cách dai_dẳng ; cái mới chưa_thể hiện được một cách rõ_nét , chưa có chỗ_đứng chắc_chắn trong cuộc_sống . 
Bên cạnh đó , đạo_đức , lối sống phương Tây đang có_điều_kiện thuận_lợi xâm_nhập và tác_động mạnh_mẽ tới đời_sống xã_hội ta , nhất_là đối_với lớp trẻ . 
Do đó , cần thường_xuyên sơ_kết , tổng_kết việc ngăn_chặn , đẩy_lùi sự suy_thoái về đạo_đức , lối sống ; tổng_kết và truyền_bá rộng_rãi những giá_trị mới của con_người Việt_Nam trong thời_kỳ CNH , HĐH . 
Thực_tiễn mới đòi_hỏi phải có tư_duy lý_luận mới . 
Tuy_nhiên , trên thực_tế lý_luận và thực_tiễn còn khoảng_cách quá lớn , nói và làm , học và hành về đạo_đức cách_mạng còn có nhiều sự khác_biệt . 
Để rèn_luyện , nâng_cao đạo_đức , lối sống và ngăn_chặn , đẩy_lùi sự suy_thoái về đạo_đức , lối sống trong Đảng , ngay trong công_tác lý_luận của Đảng phải lý_giải một_cách thấu_đáo những vấn_đề như : đạo_đức cách_mạng ngày_nay là gì ? 
Hành_vi đạo_đức đúng_đắn của cán_bộ , đảng_viên là những hành_vi nào ? 
Chống suy_thoái đạo_đức , lối sống là chống những gì ? 
v .v . . 
Vì đó không_chỉ là những vấn_đề của đạo_đức mà chính là vấn_đề tư_tưởng trong cán_bộ , đảng_viên cần giải_đáp , tháo_gỡ . 
Đồng_thời , công_tác tư_tưởng trong tình_hình hiện_nay cần phân_tích , đánh_giá , dự_báo được những tác_động của biến_đổi chính_trị - xã_hội trong nước , quốc_tế để định_hướng tư_tưởng , đạo_đức , lối sống cho cán_bộ , đảng_viên và nhân_dân kịp_thời , phù_hợp . 
Thứ hai , đổi_mới công_tác tuyên_truyền , cổ_động về đạo_đức , lối sống 
Trong công_tác tuyên_truyền , cổ_động , cần chú_trọng việc nêu gương những người tốt , việc tốt ; tuyên_truyền , phổ_biến những tấm gương tiêu_biểu , đi đầu của đội_ngũ cán_bộ , đảng_viên , nhất_là đội_ngũ cán_bộ , người đứng đầu trong các cơ_quan , tổ_chức , đơn_vị ( theo đúng tinh_thần Quy_định 101-QĐ / TW của Ban Bí_thư về " Trách_nhiệm nêu gương của cán_bộ , đảng_viên , nhất_là cán_bộ lãnh_đạo chủ_chốt các cấp " ) rộng khắp trong nhân_dân , nhằm tạo niềm tin trong nhân_dân , biến nhận_thức tư_tưởng thành hành_động cách_mạng cụ_thể , thành phong_trào quần_chúng rộng khắp . 
Thực_hiện tuyên_truyền mạnh_mẽ phong_trào Thực_hành tiết_kiệm , chống lãng_phí gắn liền với đẩy_mạnh việc học tập và làm theo tấm gương , đạo_đức Hồ_Chí_Minh nhằm tạo hiệu_ứng hành_động tích_cực , sôi_nổi , rộng khắp và thiết_thực của các tổ_chức , ở mọi cấp , mọi ngành và toàn xã_hội . 
Kịp_thời biểu_dương và nhân rộng ra toàn xã_hội những nhân_tố , mô hìnhmới , cách làm hay , các gương tập_thể và cá_nhân điển_hình tiên_tiến thực_sự tiêu_biểu , mang tính thuyết_phục cao được đa_số các tầng_lớp nhân_dân thừa_nhận để tạo sức lan_toả kịp_thời . Qua đó lấy nhân_tố tích_cực đẩy_lùi tiêu_cực ; phê_phán , đấu_tranh với những biểu_hiện sa_sút về tư_tưởng chính_trị , vô_trách_nhiệm , vụ_lợi cá_nhân , vi_phạm những chuẩn_mực đạo_đức , lối sống ; chấn_chỉnh , phê_bình những cá_nhân , tập_thể yếu_kém . 
Phát_huy vai_trò của các phương_tiện truyền_thông nhằm phổ_biến tiêu_chuẩn đạo_đức cán_bộ , đảng_viên , các quy_định , quan_điểm , chủ_trương và biện_pháp của Đảng về ngăn_chặn và đẩy_lùi sự suy_thoái về tư_tưởng chính_trị , đạo_đức , lối sống trong cán_bộ , đảng_viên ; giúp cán_bộ , đảng_viên và nhân_dân hiểu đúng về phòng , chống suy_thoái đạo_đức , lối sống . 
Thứ ba , phải thật_sự coi_trọng và tiến_hành có hiệu_quả các biện_pháp giáo_dục đạo_đức , lối sống cho cán_bộ , đảng_viên 
Để góp_phần ngăn_chặn và đẩy_lùi suy_thoái đạo_đức , lối sống của cán_bộ , đảng_viên hiện_nay đòi_hỏi phải phát_huy được sức_mạnh tổng_hợp , đề_cao trách_nhiệm của cả hệ_thống chính_trị và toàn dân , trong đó trước_hết phảithật sự coi_trọng và đổi_mới việc giáo_dục đạo_đức , lối sống cho cán_bộ , đảng_viên , tạo niềm tin của nhân_dân đối_với Đảng . 
Những tài_liệu phục_vụ công_tác giáo_dục đạo_đức , lối sống cho cán_bộ , đảng_viên cần phải phù_hợp với điều_kiện phát_triển kinh_tế_thị_trường định_hướng XHCN và hội_nhập quốc_tế . 
Bổ_sung và hoàn_thiện thang giá_trị đạo_đức với các phẩm_chất đạo_đức cơ_bản của cán_bộ , đảng_viên theo các tiêu_chí : cần , kiêm , liêm , chính , chí_công , vô_tư ; năng_động , sáng_tạo , dám nghĩ , dám làm , dám chịu trách_nhiệm ; ham học_hỏi , cầu_tiến bộ , biết trọng_dụng hiền_tài ; nói đi_đôi với làm , gương_mẫu trong công_việc ; có tinh_thần tự_phê_bình và phê_bình , dũng_cảm đấu_tranh chống lại cái sai , bảo_vệ cái đúng . 
Phương_châm giáo_dục cơ_bản phải hướng đến biến giáo_dục thành tự giáo_dục . 
Hoạt_động tự giáo_dục , rèn_luyện đạo_đức của cán_bộ , đảng_viên luôn mang tính chủ_thể cao . 
Do đó , cần phải thường_xuyên động_viên , khích_lệ nhu_cầu tự hoàn_thiện ở mỗi người và thường_xuyên bồi_dưỡng năng_lực tự giáo_dục , rèn_luyện . 
Để nâng_cao chất_lượng và hiệu_quả tự giáo_dục , rèn_luyện đạo_đức , lối sống của cán_bộ , đảng_viên hiện_nay , cần tạo ra các điều_kiện và môi_trường thuận_lợi để họ phát huytính chủ_động , tự_giác của cán_bộ , đảng_viên trong việc tự_tu dưỡng , rèn_luyện , trau_dồi đạo_đức , lối sống , tạo_dựng môi_trường tinh_thần tích_cực đấu_tranh với cái xấu , bảo_vệ cái tốt . 
Đồng_thời phải đưa vào nền_nếp việc bồi_dưỡng đạo_đức , lối sống , cập_nhật kiến_thức mới cho cán_bộ , đảng_viên , nhất_là cán_bộ lãnh_đạo , quản_lý các cấp , đặc_biệt là cán_bộ cao_cấp . 
Thứ tư , đặc_biệt coi_trọng công_tác văn_hoá , văn_nghệ trong tuyên_truyền , giáo_dục đạo_đức , lối sống cho cán_bộ , đảng_viên 
Công_tác văn_hoá , văn_nghệ một mặt góp_phần thoả_mãn nhu_cầu tinh_thần của cán_bộ , đảng_viên và nhân_dân , mặt_khác góp_phần giáo_dục đạo_đức , lối sống , xây_dựng đời_sống văn_hoá đạo_đức cách_mạng trong Đảng . 
Văn_hoá đạo_đức , văn_hoá ứng_xử và văn_hoá chính_trị là những mục_tiêu trực_tiếp cần hướng đến trong công_tác văn_hoá , văn_nghệ . 
Văn_hoá , văn_nghệ phải biết trân_trọng , biểu_dương bằng nghệ_thuật những tấm gương hy_sinh vì xã_hội , phê_phán cái xấu , cái ác trong mỗi con_người và cuộc_sống . 
Đó là mục_tiêu chân_chính của cái chân - thiện - mỹ . 
Muốn vậy , công_tác tư_tưởng cần động_viên , khuyến_khích người sáng_tác , nhất_là người sáng_tác văn_học , nghệ_thuật lựa_chọn đề_tài , đối_tượng phản_ánh ... nhằm hướng tới đề_cao , tôn_vinh những giá_trị nhân_văn , nhân_ái : lòng vị_tha , biết sống vì mọi người . 
Các ngành , các địa_phương cần tạo điều_kiện quảng_bá các sáng_tác văn_học , nghệ_thuật về đạo_đức Hồ_Chí_Minh và những tấm gương điển_hình học_tập và làm theo đạo_đức Hồ_Chí_Minh . 
Thứ năm , kiên_quyết , kiên_trì đấu_tranh làm thất_bại mọi âm_mưu và hoạt_động " diễn_biến_hoà_bình " của các thế_lực thù_địch trên lĩnh_vực tư_tưởng , đạo_đức , lối sống 
Đấu_tranh chống " diễn_biến_hoà_bình " về tư_tưởng , đạo_đức , lối sống của cán_bộ , đảng_viên cần nâng_cao khả_năng tự đề_kháng , đủ sức chống lại " tự suy_thoái " , " tự diễn_biến " , " tự chuyển_hoá " về tư_tưởng chính_trị , đạo_đức , lối sống ; chủ_động phòng_ngừa , đấu_tranh , phê_phán những biểu_hiện " tự suy_thoái " , " tự diễn_biến " , " tự chuyển_hoá " trong nội_bộ Đảng . 
Đấu_tranh ngăn_chặn và đẩy_lùi sự suy_thoái về đạo_đức , lối sống trong một bộ_phận cán_bộ , đảng_viên là nhiệm_vụ trọng_tâm , xuyên_suốt và cấp_bách hiện_nay . 
Để ngăn_chặn , đẩy_lùi tình_trạng này , các giải_pháp về tư_tưởng là hết_sức quan_trọng và cần_thiết , nhưng chưa đủ . 
Như C.Mác nói : tư_tưởng căn_bản là bằng không , muốn thực_hành tư_tưởng thì cần có con_người sử_dụng lực_lượng thực_tiễn . 
Do đó , để không rơi vào tình_trạng " chỉ làm cách_mạng trong tư_tưởng " , cần kết_hợp đồng_bộ các giải_pháp về giáo_dục chính_trị , tư_tưởng tự_phê_bình và phê_bình , nêu cao tính tiền_phong gương_mẫu của cấp_trên với công_tác tổ_chức , cán_bộ và sinh_hoạt Đảng . 
