Sự phát_triển tư_duy lý_luận của Đảng về phát_huy sức_mạnh đại_đoàn_kết toàn dân_tộc 
Đại_đoàn_kết là truyền_thống quý_báu được hun_đúc trong suốt quá_trình dựng nước và giữ nước của dân_tộc ; là một trong những bài_học lớn xuyên_suốt tiến_trình lịch_sử cách_mạng nước ta . 
Ngay từ khi ra_đời , Đảng ta đã nhận_thức rõ vị_trí , vai_trò của sức_mạnh đại_đoàn_kết toàn dân đối_với sự phát_triển của cách_mạng . 
Cùng với sự vận_động của thực_tiễn , để đáp_ứng yêu_cầu nhiệm_vụ của mỗi giai_đoạn , tư_duy lý_luận của Đảng về phát_huy sức_mạnh đại_đoàn_kết toàn dân_tộc không ngừng được bổ_sung và phát_triển , góp_phần to_lớn vào những thắng_lợi của sự_nghiệp xây_dựng và bảo_vệ Tổ_quốc . 
Đại_hội VI của Đảng ( 1986 ) đã nêu lên 4 bài_học kinh_nghiệm lớn , trong đó , bài_học thứ nhất là : " Trong toàn_bộ hoạt_động của mình , Đảng phải quán_triệt tư_tưởng " lấy dân làm gốc " ( 1 ) , xây_dựng và phát_huy quyền làm chủ của nhân_dân lao_động . 
Thực_hiện Nghị_quyết Đại_hội VI , Hội_nghị Trung_ương 8 đã ra Nghị_quyết 8B về đổi_mới công_tác quần_chúng của Đảng , tăng_cường mối quan_hệ giữa Đảng và nhân_dân , nhấn_mạnh quan_điểm : cách_mạng là sự_nghiệp của dân , do dân , vì dân . 
Trong điều_kiện cuộc cách_mạng khoa_học và công_nghệ phát_triển mạnh_mẽ , kinh_tế tri_thức có vai_trò ngày_càng quan_trọng trong quá_trình phát_triển lực_lượng_sản_xuất , Đảng ta nhận_thức rõ hơn vị_trí , vai_trò của các giai_tầng trong xã_hội , nhất_là của tầng_lớp trí_thức . 
Tại Đại_hội VII , lần đầu_tiên trong Cương_lĩnh xây_dựng đất_nước trong thời_kỳ quá_độ lên CNXH , Đảng ta khẳng_định lấy khối liên_minh công_nhân - nông_dân - trí_thức làm nền_tảng cho khối đại_đoàn_kết toàn dân_tộc . 
Cương_lĩnh đã nêu 5 bài_học lớn , trong đó có bài_học : Sự_nghiệp cách_mạng là của nhân_dân và vì nhân_dân ; chính nhân_dân là người làm nên thắng_lợi lịch_sử ; không ngừng củng_cố , tăng_cường đoàn_kết : đoàn_kết toàn Đảng , đoàn_kết toàn dân , đoàn_kết dân_tộc , đoàn_kết quốc_tế . 
Đại_hội VIII tiếp_tục khẳng_định tinh_thần Đại_hội VII và nêu cao phương_châm : tăng_cường khối đại_đoàn_kết toàn dân_tộc trên cơ_sở lấy liên_minh công_nhân - nông_dân - trí_thức làm nền_tảng , đoàn_kết mọi người trong đại_gia_đình dân_tộc Việt_Nam dù sống ở trong nước hay định_cư ở nước_ngoài ; có cơ_chế và cách làm cụ_thể để thực_hiện phương_châm dân biết , dân bàn , dân làm , dân kiểm_tra . 
Tổng_kết 10 năm đổi_mới , Đại_hội cũng rút ra một trong những nguyên_nhân trọng_yếu dẫn đến thành_công của Đảng trong hoạch_định và thực_hiện đường_lối đổi_mới : " Chính những ý_kiến , nguyện_vọng và sáng_kiến của nhân_dân là nguồn_gốc hình_thành đường_lối đổi_mới của Đảng . 
Cũng do nhân_dân hưởng_ứng đường_lối đổi_mới , dũng_cảm phấn_đấu , vượt_qua biết_bao khó_khăn , thử_thách mà công_cuộc đổi_mới đạt được những thành_tựu hôm_nay " ( 2 ) .Từ tư_duy mới về vai_trò của nhân_dân , về vấn_đề dân_tộc trong thời_kỳ mới , Đảng ta xác_định đại_đoàn_kết toàn dân_tộc là đường_lối chiến_lược , là nguồn sức_mạnh và động_lực chủ_yếu của cách_mạng Việt_Nam . 
Tư_tưởng này là sự kế_thừa , phát_huy tư_tưởng Hồ_Chí_Minh về đại_đoàn_kết toàn dân_tộc : " Đoàn_kết của ta không_những rộng_rãi mà_còn đoàn_kết lâu_dài ... 
Không phải là một thủ_đoạn chính_trị ... 
Ai có tài , có đức , có sức , có lòng phụng_sự Tổ_quốc và phục_vụ nhân_dân thì ta đoàn_kết với họ " ( 3 ) . 
Kế_thừa và phát_huy nguồn sức_mạnh của khối đại_đoàn_kết toàn dân trong sự_nghiệp đổi_mới , đặc_biệt là thời_kỳ đẩy_mạnh CNH , HĐH đất_nước , Đại_hội Đảng lần thứ IX đã lấy chủ_đề : " Phát_huy sức_mạnh toàn dân_tộc , tiếp_tục đổi_mới , đẩy_mạnh công_nghiệp_hoá , hiện_đại_hoá , xây_dựng và bảo_vệ Tổ_quốc Việt_Nam xã_hội_chủ_nghĩa " .Đại hội đã có bước phát_triển và cụ_thể hơn nữa quan_điểm về phát_huy sức_mạnh đại_đoàn_kết toàn dân : thực_hiện đại_đoàn_kết các dân_tộc , tôn_giáo , giai_cấp , tầng_lớp , mọi giới , mọi lứa tuổi , mọi vùng của đất_nước , người trong Đảng và người_ngoài Đảng , người đang công_tác và người đã nghỉ hưu , mọi thành_viên trong đại_gia_đình Việt_Nam dù sống trong nước hay ở nước_ngoài ; lấy mục_tiêu giữ vững độc_lập , thống_nhất , vì dân giàu , nước mạnh , xã_hội công_bằng , dân_chủ , văn_minh làm điểm tương_đồng . 
Đại_hội khẳng_định : " Động_lực chủ_yếu để phát_triển đất_nước là đại_đoàn_kết toàn dân trên cơ_sở liên_minh giữa công_nhân với nông_dân và trí_thức do Đảng lãnh_đạo , kết_hợp hài_hoà các lợi_ích cá_nhân , tập_thể và xã_hội , phát_huy mọi tiềm_năng và nguồn_lực của các thành_phần kinh_tế , của toàn xã_hội " ( 4 ) . 
Như vậy , so với các động_lực khác , đại_đoàn_kết toàn dân_tộc là động_lực tổng_hợp và là động_lực to_lớn nhất . 
Nhằm cụ_thể_hoá tinh_thần Nghị_quyết Đại_hội IX , Nghị_quyết Hội_nghị Trung_ương 7 khoá IX đãnêu bật 4 quan_điểm , trong đó nhấn_mạnh bảo_đảm công_bằng và bình_đẳng xã_hội , chăm_lo lợi_ích thiết_thực , chính_đáng và hợp_pháp của các giai_cấp và tầng_lớp nhân_dân vànhận định đại_đoàn_kết toàn dân_tộc là nhân_tố có ý_nghĩa quyết_định bảo_đảm thắng_lợi bền_vững của sự_nghiệp xây_dựng và bảo_vệ Tổ_quốc . 
Nghị_quyết chỉ rõ : xoá bỏ_mặc cảm , định_kiến , phân_biệt đối_xử về quá_khứ , thành_phần giai_cấp , xây_dựng tinh_thần cởi_mở , tin_cậy lẫn nhau , cùng hướng tới tương_lai . 
Hơn_nữa , cụm từ " đại_đoàn_kết toàn dân " đã được bổ_sung , hoàn_chỉnh thành " đại_đoàn_kết toàn dân_tộc " với ý_nghĩa mở_rộng đại_đoàn_kết , đoàn_kết không_chỉ ở trong nước mà_còn với cả cộng_đồng người Việt_Nam định_cư ở nước_ngoài . 
Đại_hội X của Đảng ( tháng 4-2006 ) một mặt khẳng_định lại những quan_điểm cơ_bản của Đại_hội IX , đồng_thời đã phát_triển hoàn_chỉnh hệ_thống các chủ_trương , chính_sách nhằm phát_huy sức_mạnh đại_đoàn_kết toàn dân_tộc và nhấn_mạnh đại_đoàn_kết toàn dân_tộc là đường_lối chiến_lược , là nguồn sức_mạnh , động_lực chủ_yếu và là nhân_tố có ý_nghĩa quyết_định bảo_đảm thắng_lợi bền_vững của sự_nghiệp xây_dựng và bảo_vệ Tổ_quốc . 
Lấy mục_tiêu giữ vững độc_lập , thống_nhất của Tổ_quốc , vì dân giàu , nước mạnh , xã_hội công_bằng , dân_chủ , văn_minh làm điểm tương_đồng để gắn_bó đồng_bào các dân_tộc , các tôn_giáo , các tầng_lớp nhân_dân ở trong nước và người Việt_Nam định_cư ở nước_ngoài ; xoá_bỏ mọi mặc_cảm , định_kiến , phân_biệt đối_xử về quá_khứ , thành_phần giai_cấp . 
Tôn_trọng những ý_kiến khác nhau không trái với lợi_ích của dân_tộc . 
Đề_cao truyền_thống nhân_nghĩa , khoan_dung , xây_dựng tinh_thần cởi_mở , tin_cậy lẫn nhau vì sự ổn_định và đồng_thuận xã_hội . 
Cụ_thể_hoá tinh_thần Đại_hội X của Đảng , Hội_nghị Trung_ương 6 khoá X ( tháng 1-2008 ) ra Nghị_quyết về tiếp_tục xây_dựng giai_cấp công_nhân Việt_Nam thời_kỳ đẩy_mạnh công_nghiệp_hoá , hiện_đại_hoá đất_nước và Hội_nghị Trung_ương 7 khoá X ( tháng 7-2008 ) đã ban_hành Nghị_quyết về tăng_cường sự lãnh_đạo của Đảng đối_với công_tác thanh_niên , Nghị_quyết về xây_dựng đội_ngũ trí_thức và Nghị_quyết về nông_nghiệp , nông_dân , nông_thôn . 
Đó chính là hệ_thống các quan_điểm của Đảng tiếp_tục khẳng_định vai_trò và sự cần_thiết phải tăng_cường , phát_huy sức_mạnh của khối đại_đoàn_kết toàn dân_tộc trong giai_đoạn mới . 
Sau 25 năm tiến_hành công_cuộc đổi_mới và 20 năm thực_hiện Cương_lĩnh xây_dựng đất_nước trong thời_kỳ quá_độ lên CNXH , Đại_hội XI của Đảng tiếp_tục khẳng_định : phát_huy sức_mạnh toàn dân_tộc là thành_tố thứ hai , sau thành_tố về tiếp_tục nâng_cao năng_lực lãnh_đạo và sức chiến_đấu của Đảng . 
Đây chính là hai thành_tố quan_trọng có ý_nghĩa quyết_định để thực_hiện thành_công những nhiệm_vụ chủ_yếu của toàn Đảng , toàn dân , toàn quân ta đẩy_mạnh toàn_diện công_cuộc đổi_mới , tạo nền_tảng để đến năm 2020 nước ta cơ_bản trở_thành nước công_nghiệp theo hướng hiện_đại . 
Sức_mạnh của đại_đoàn_kết toàn dân_tộc được hiểu là sức_mạnh tổng_hợp của cả kinh_tế , chính_trị , văn_hoá , xã_hội , quốc_phòng , an_ninh , đối_ngoại ; sức_mạnh của các thành_phần kinh_tế , các lực_lượng chính_trị , xã_hội , các dân_tộc , tôn_giáo , các tầng_lớp nhân_dân trong nước và cộng_đồng người Việt_Nam định_cư ở nước_ngoài có cùng " mục_tiêu xây_dựng một nước Việt_Nam hoà_bình , độc_lập , thống_nhất , toàn_vẹn lãnh_thổ , dân giàu , nước mạnh , dân_chủ , công_bằng , văn_minh làm điểm tương_đồng ; xoá bỏ_mặc cảm , định_kiến về quá_khứ , thành_phần giai_cấp , chấp_nhận những điểm khác nhau không trái với lợi_ích chung của dân_tộc ; đề_cao tinh_thần dân_tộc , truyền_thống nhân_nghĩa , khoan_dung ... để tập_hợp , đoàn_kết mọi người vào mặt_trận chung , tăng_cường đồng_thuận xã_hội " ( 5 ) . 
Nghị_quyết Đại_hội XI của Đảng là sự kết_tinh trí_tuệ và ý_chí của toàn Đảng , toàn dân và toàn quân ta , thể_hiện sự nhất_quán kiên_định tư_tưởng chính_trị và phương_pháp cách_mạng Hồ_Chí_Minh - tư_tưởng chính_trị và phương_pháp cách_mạng dựa trên sự bố_trí các lực_lượng xã_hội , trên cơ_sở vận_dụng nhuần_nhuyễn quan_điểm giai_cấp , quan_điểm dân_tộc vào thực_tiễn Việt_Nam . 
Chủ_tịch Hồ_Chí_Minh từng chỉ rõ : " vận_động tất_cả lực_lượng của mỗi_một người dân không để sót một người dân nào , góp thành lực_lượng toàn dân " ( 6 ) . 
Điều đáng lưu_ý là quá_trình đổi_mới tư_duy lý_luận của Đảng về đại_đoàn_kết toàn dân_tộc cũng đồng_thời với sự nhận_thức đúng về vị_trí của yếu_tố lợi_ích . 
Ngay từ Nghị_quyết Trung_ương 8 khoá VI Đảng đã nêu quan_điểm : động_lực thúc_đẩy phong_trào quần_chúng là đáp_ứng lợi_ích thiết_thực của nhân_dân và kết_hợp hài_hoà các lợi_ích thống_nhất quyền_lợi và nghĩa_vụ công_dân . 
Yếu_tố quan_trọng đầu_tiên , có tính quyết_định bảo_đảm thực_hiện đại_đoàn_kết toàn dân_tộc chính là phải bảo_đảm công_bằng xã_hội , chăm_lo lợi_ích thiết_thực , chính_đáng của các giai_cấp , các tầng_lớp nhân_dân , kết_hợp hài_hoà lợi_ích cá_nhân , lợi_ích tập_thể và lợi_ích xã_hội . 
Cùng với việc giải_quyết đúng_đắn , hợp_lý quan_hệ lợi_ích , phát_huy chủ_nghĩa_yêu_nước , thực_hiện dân_chủ là những yếu_tố quan_trọng để củng_cố và phát_triển khối đại_đoàn_kết toàn dân_tộc . 
Tư_duy về dân_chủ của Đảng ta cũng có sự phát_triển trong mối quan_hệ với tư_duy đoàn_kết toàn dân_tộc khi nhấn_mạnh kết_hợp nguyên_tắc tập_trung_dân_chủ với nguyên_tắc hiệp_thương dân_chủ để làm phong_phú thêm nền dân_chủ ở nước ta . 
Để phát_huy sức_mạnh toàn dân_tộc , Đảng ta đặt vấn_đề phải xây_dựng sự đồng_thuận xã_hội . 
Đồng_thuận trong xã_hội ta hiện_nay là sự nhất_trí trên những điểm tương_đồng . 
Về chính_trị , điểm tương_đồng là mục_tiêu chung : giữ vững độc_lập thống_nhất , vì dân giàu , nước mạnh , dân_chủ , công_bằng , văn_minh . 
Về kinh_tế , là sự phát_triển hài_hoà các lợi_ích ( cá_nhân , tập_thể , cộng_đồng , xã_hội ) vì sự phát_triển chung của đất_nước . 
Về tinh_thần là chủ_nghĩa_yêu_nước chân_chính . 
Về mặt văn_hoá là sự hướng_thiện , tôn_trọng những giá_trị văn_hoá , đạo_đức mang tính nhân_bản ; là giữ_gìn và phát_huy văn_hoá thờ_cúng tổ_tiên , tôn_vinh và nhớ ơn những người có công với Tổ_quốc , dân_tộc và cộng_đồng ; là sự tôn_trọng tự_do tôn_giáo , tín_ngưỡng . 
Trong thời_kỳ đổi_mới , dưới sự lãnh_đạo sáng_suốt của Đảng , toàn dân , toàn quân ta đã tận_dụng thời_cơ , vượt_qua thách_thức , kiên_trì phấn_đấu , bằng trí_tuệ , tài_năng và nghị_lực phi_thường của mình , đạt được những thành_tựu to_lớn , có ý_nghĩa lịch_sử , tạo nên thế và lực mới cho đất_nước . 
Tuy_nhiên , đất_nước ta vẫn còn phải đương_đầu với không ít khó_khăn , thách_thức , vẫn còn những hạn_chế , yếu_kém : kinh_tế phát_triển chưa bền_vững ; các lĩnh_vực văn_hoá , xã_hội còn nhiều bất_cập , một_số mặt còn bức_xúc ; phân_hoá giàu_nghèo ngày_một tăng ; tệ quan_liêu , tham_nhũng , lãng_phí , tội_phạm , tệ_nạn xã_hội , suy_thoái đạo_đức , lối sống chưa được ngăn_chặn , đẩy_lùi ; thiên_tai , dịch_bệnh diễn_biến phức_tạp ; các thế_lực thù_địch vẫn tăng_cường âm_mưu , thủ_đoạn phá_hoại chế_độ , phá_hoại thành_quả cách_mạng và phá_hoại khối đại_đoàn_kết toàn dân_tộc . 
Những yếu_tố trên tác_động lẫn nhau , làm hạn_chế việc phát_huy thành_quả của công_cuộc đổi_mới , làm giảm lòng tin trong một bộ_phận nhân_dân , ảnh_hưởng đến sự đồng_thuận xã_hội và phát_huy sức_mạnh đại_đoàn_kết toàn dân_tộc . 
Đây cũng là những khó_khăn , thách_thức của khối đại_đoàn_kết toàn dân_tộc trong thời_kỳ mới . 
Để sự_nghiệp đại_đoàn_kết toàn dân_tộc ngày_càng được củng_cố và phát_huy sức_mạnh vì mục_tiêu dân giàu , nước mạnh , dân_chủ , công_bằng , văn_minh , theo tôi , cả hệ_thống chính_trị của đất_nước phải thực_hiện tốt những nội_dung như sau : 
Thứ nhất,các tổ_chức đảng , cấp_uỷ đảng quan_tâm lãnh_đạo việc quán_triệt , nâng_cao nhận_thức và phát_huy trách_nhiệm của các tổ_chức trong hệ_thống chính_trị và toàn xã_hội về sự_nghiệp đại_đoàn_kết toàn dân_tộc . 
Tiếp_tục cụ_thể_hoá , thể_chế hoá quan_điểm , chủ_trương , đường_lối của Đảng thành những chính_sách , pháp_luật , nhất_là những chính_sách , pháp_luật , quy_định liên_quan đến từng giai_cấp , tầng_lớp nhân_dân ; tiếp_tục đẩy_mạnh và thực_hiện có hiệu_quả , thiết_thực , đi vào chiều sâu " Cuộc vận_động Học_tập và làm theo tấm gương đạo_đức Hồ_Chí_Minh " ; ngăn_chặn suy_thoái phẩm_chất , đạo_đức , lối sống , đẩy_lùi tệ tham_nhũng , lãng_phí , tiêu_cực , quan_liêu xa_rời quần_chúng của một bộ_phận cán_bộ , đảng_viên ; tiếp_tục đổi_mới phương_thức lãnh_đạo của Đảng đối_với Mặt_trận Tổ_quốc Việt_Nam và các đoàn_thể nhân_dân , tôn_trọng nguyên_tắc hiệp_thương dân_chủ trong tổ_chức và hoạt_động của Mặt_trận Tổ_quốc Việt_Nam , tôn_trọng tính tự_chủ , ủng_hộ mọi hoạt_động tự_nguyện , tích_cực , sáng_tạo và chân_thành lắng_nghe ý_kiến đóng_góp của Mặt_trận và các đoàn_thể ; thực_hiện tốt vai_trò Đảng vừa là người lãnh_đạo , vừa là thành_viên của Mặt_trận Tổ_quốc Việt_Nam ; xây_dựng , củng_cố , kiện_toàn đội_ngũ cán_bộ Mặt_trận và các đoàn_thể , nhất_là cán_bộ chủ_chốt ngang tầm với yêu_cầu nhiệm_vụ trong thời_kỳ mới . 
Thứ hai,mở rộng dân_chủ , tăng_cường sự đồng_thuận xã_hội đồng_thời giữ vững kỷ_cương xã_hội trên tất_cả các lĩnh_vực chính_trị , kinh_tế , văn_hoá , xã_hội ... ở tất_cả các cấp , các ngành . 
Các cơ_quan nhà_nước , các cấp chính_quyền cần chăm_lo phát_huy và bảo_đảm quyền dân_chủ của nhân_dân theo pháp_luật . 
Đồng_thời ngăn_chặn và xử_lý nghiêm_minh những biểu_hiện vi_phạm quyền dân_chủ của nhân_dân , cũng như những biểu_hiện lợi_dụng dân_chủ để vi_phạm pháp_luật , kích_động nhân_dân , gây rối trật_tự công_cộng , ảnh_hưởng đến sự ổn_định chính_trị , xã_hội và chia_rẽ khối đại_đoàn_kết dân_tộc . 
Cần nhận_thức và xử_lý đúng_đắn mối quan_hệ giữa dân_chủ và tập_trung ; dân_chủ với kỷ_luật , kỷ_cương , pháp_luật ; dân_chủ với trách_nhiệm , nghĩa_vụ công_dân , dân_chủ phải có lãnh_đạo và lãnh_đạo bằng phương_pháp dân_chủ , trên cơ_sở phát_huy dân_chủ . 
Thực_hiện tốt hơn nữa Quy_chế dân_chủ ở cơ_sở , từng bước giải_quyết những vấn_đề xã_hội bức_xúc để phòng và chống âm_mưu " diễn_biến_hoà_bình " , chống lại các thủ_đoạn của các thế_lực thù_địch nhằm tranh_giành quần_chúng , chia_rẽ mối quan_hệ giữa Đảng với nhân_dân , chia_rẽ khối đại_đoàn_kết dân_tộc . 
Bảo_đảm lợi_ích của các giai_cấp , tầng_lớp xã_hội và kết_hợp hài_hoà lợi_ích cá_nhân , lợi_ích tập_thể và toàn xã_hội , coi đó là yếu_tố quan_trọng nhất , là điều_kiện tiên_quyết để tổ_chức và động_viên nhân_dân tham_gia tích_cực vào các phong_trào thi_đua yêu nước , nhằm củng_cố và mở_rộng khối đại_đoàn_kết toàn dân_tộc . 
Thứ ba,chăm lo đối_với các giai_tầng xã_hội . 
Quan_tâm giáo_dục , đào_tạo , bồi_dưỡng , phát_triển giai_cấp công_nhân cả về số_lượng và chất_lượng . 
Xây_dựng , phát_huy vai_trò của giai_cấp nông_dân , chủ_thể của quá_trình phát_triển nông_nghiệp , nông_thôn . 
Xây_dựng đội_ngũ trí_thức lớn_mạnh , có chất_lượng cao , đáp_ứng yêu_cầu phát_triển đất_nước . 
Tạo điều_kiện xây_dựng , phát_triển đội_ngũ doanh_nhân lớn_mạnh , có trách_nhiệm xã_hội cao . 
Làm tốt công_tác giáo_dục chính_trị , tư_tưởng , truyền_thống , lý_tưởng , đạo_đức và lối sống , tạo điều_kiện học_tập , lao_động , giải_trí , phát_triển thể_lực , trí_tuệ cho thế_hệ trẻ . 
Nâng_cao trình_độ mọi mặt và đời_sống vật_chất , tinh_thần của phụ_nữ . 
Phát_huy truyền_thống Bộ_đội Cụ Hồ , tích_cực tham_gia xây_dựng và bảo_vệ Đảng , Nhà_nước , chế_độ xã_hội_chủ_nghĩa , bảo_vệ nhân_dân của cựu_chiến_binh . 
Quan_tâm chăm_sóc sức_khoẻ , tạo điều_kiện để người cao_tuổi hưởng_thụ văn_hoá , được tiếp_cận thông_tin , sống vui , sống khoẻ , sống hạnh_phúc . 
Thứ tư , xây_dựng khối đại_đoàn_kết các dân_tộc , có cơ_chế , chính_sách , tạo chuyển_biến rõ_rệt trong phát_triển kinh_tế , văn_hoá , xã_hội vùng dân_tộc thiểu_số . 
Tăng_cường kiểm_tra , giám_sát , đánh_giá kết_quả thực_hiện các chủ_trương , chính_sách dân_tộc của Đảng và Nhà_nước ở các cấp . 
Chống kỳ_thị dân_tộc , nghiêm_trị những âm_mưu , hành_động chia_rẽ , phá_hoại khối đại_đoàn_kết toàn dân_tộc . 
Thứ năm , tiếp_tục hoàn_thiện chính_sách , pháp_luật về tín_ngưỡng , tôn_giáo phù_hợp với quan_điểm của Đảng . 
Phát_huy những giá_trị văn_hoá , đạo_đức tốt_đẹp của các tôn_giáo ; động_viên các tổ_chức tôn_giáo , chức_sắc , tín_đồ sống tốt đời , đẹp đạo , tham_gia đóng_góp tích_cực cho công_cuộc xây_dựng và bảo_vệ Tổ_quốc . 
Quan_tâm và tạo điều_kiện cho các tổ_chức tôn_giáo sinh_hoạt theo hiến_chương , điều_lệ của tổ_chức tôn_giáo đã được Nhà_nước công_nhận , đúng quy_định của pháp_luật . 
Chủ_động phòng_ngừa , kiên_quyết đấu_tranh với những hành_vi lợi_dụng tôn_giáo để chia_rẽ , phá_hoại khối đại_đoàn_kết toàn dân_tộc . 
Thứ_sáu , đồng_bào định_cư ở nước_ngoài là một bộ_phận không tách_rời của cộng_đồng dân_tộc Việt_Nam . 
Nhà_nước cần có cơ_chế , chính_sách để hỗ_trợ , giúp_đỡ đồng_bào ổn_định cuộc_sống ở nước định_cư , phát_triển kinh_tế , góp_phần tăng_cường tình hữu_nghị giữa nhân_dân ta với nhân_dân các nước ; tạo điều_kiện để đồng_bào giữ_gìn và phát_huy bản_sắc văn_hoá dân_tộc , hướng về Tổ_quốc , đóng_góp xây_dựng đất_nước . 
Thứ_bảy , phát_huy vai_trò của Mặt_trận Tổ_quốc và các đoàn_thể nhân_dân trong xây_dựng khối đại_đoàn_kết toàn dân_tộc ; tiếp_tục tăng_cường tổ_chức , đổi_mới nội_dung , phương_thức hoạt_động , khắc_phục tình_trạng hành_chính_hoá , phát_huy vai_trò nòng_cốt tập_hợp , đoàn_kết nhân_dân xây_dựng cơ_sở chính_trị của chính_quyền nhân_dân ; phát_huy tốt hơn nữa vai_trò giám_sát và phản_biện xã_hội khi tham_gia xây_dựng và vận_động quần_chúng nhân_dân thực_hiện các chủ_trương , chính_sách , pháp_luật của Đảng và Nhà_nước ; đặc_biệt , cần thông_qua các hình_thức và việc_làm thiết_thực để phát_huy tinh_thần yêu nước , lòng tự_hào dân_tộc , ý_chí tự_lực , tự_cường , ý_thức trách_nhiệm và quyền làm chủ của nhân_dân , hướng mạnh hơn nữa các hoạt_động về cơ_sở , cộng_đồng dân_cư . 
