Quan_điểm của Đảng về đấu_tranh phòng , chống tham_nhũng 
Sau 30 năm đổi_mới , đất_nước ta đã đạt được những thành_tựu to_lớn , có ý_nghĩa lịch_sử ; tuy_nhiên cũng còn không ít hạn_chế , yếu_kém cần phải tập_trung giải_quyết , khắc_phục để đưa đất_nước phát_triển nhanh và bền_vững . 
Tham_nhũng , lãng_phí vẫn diễn_ra nghiêm_trọng ở nhiều ngành , nhiều cấp , nhiều lĩnh_vực với phạm_vi rộng , tính_chất phức_tạp , gây hậu_quả xấu về nhiều mặt , làm giảm_sút lòng tin của nhân_dân , là một trong những nguy_cơ lớn đe_doạ sự tồn_vong của Đảng và chế_độ ta . 
Nhận_thức rõ thực_trạng tham_nhũng và những nguy_cơ mà vấn_nạn này gây ra , Đảng ta đã ban_hành nhiều nghị_quyết , chỉ_thị , và thành_lập Ban chỉ_đạo đấu_tranh phòng , chống tham_nhũng . 
Nghị_quyết số 14-NQ / TW của Bộ Chính_trị ngày 15-5-1996 nêu rõ : Đấu_tranh chống tham_nhũng là một bộ_phận cấu_thành quan_trọng trong toàn_bộ sự_nghiệp đấu_tranh cách_mạng của Đảng và nhân_dân ta hiện_nay . 
Nó góp_phần giữ vững vai_trò lãnh_đạo của Đảng , tăng_cường hiệu_quả quản_lý_nhà_nước , xây_dựng Đảng và bộ_máy nhà_nước trong_sạch , vững_mạnh , thực_hiện quyền dân_chủ của nhân_dân ... 
Đấu_tranh chống tham_nhũng phải gắn liền và phục_vụ cho đổi_mới kinh_tế - xã_hội , giữ vững ổn_định chính_trị , tăng_cường đại_đoàn_kết toàn dân , thực_hiện thắng_lợi hai nhiệm_vụ chiến_lược là xây_dựng CNXH và bảo_vệ Tổ_quốc Việt_Nam XHCN . 
Đấu_tranh với tiêu_cực , tham_nhũng , trước_hết là cuộc đấu_tranh với những biểu_hiện suy_thoái về tư_tưởng chính_trị , đạo_đức , lối sống với những biểu_hiện khác nhau về sự phai_nhạt lý_tưởng , sa vào chủ_nghĩa_cá_nhân , cơ_hội , thực_dụng , chạy theo danh_lợi , tiền_tài , kèn_cựa địa_vị , cục_bộ , tuỳ_tiện , vô_nguyên_tắc của một bộ_phận không nhỏ cán_bộ , đảng_viên . 
Đó là cuộc đấu_tranh đầy cam_go , phức_tạp , đòi_hỏi có sự lãnh_đạo toàn_diện và tuyệt_đối của Đảng . 
Đại_hội X xác_định , phòng , chống tham_nhũng lànhiệm vụ trọng_tâm của công_tác xây_dựng Đảng , là nhiệm_vụ trực_tiếp , thường_xuyên của cả hệ_thống chính_trị và toàn xã_hội và cần thành_lập các ban chỉ_đạo phòng , chống tham_nhũng ở Trung_ương và địa_phương đủ mạnh , có thực_quyền , hoạt_động có hiệu_quả . 
Hội_nghị Trung_ương 3 khoá X ban_hành Nghị_quyết về Tăng_cường sự lãnh_đạo của Đảng đối_với công_tác phòng , chống tham_nhũng , lãng_phí , đã xác_định rõ mục_tiêu của công_tác phòng , chống tham_nhũng , lãng_phí là : ngăn_chặn , từng bước đẩy_lùi tham_nhũng , lãng_phí ; tạo bước chuyển_biến rõ_rệt để giữ vững ổn_định chính_trị , phát_triển kinh_tế - xã_hội ; củng_cố lòng tin của nhân_dân ; xây_dựng Đảng , Nhà_nước trong_sạch , vững_mạnh ; đội_ngũ cán_bộ , công_chức kỷ_cương , liêm_chính . 
Các giải_pháp để thực_hiện như sau : tăng_cường tuyên_truyền , giáo_dục , nâng_cao nhận_thức và ý_thức trách_nhiệm của đảng_viên , cán_bộ , công_chức và nhân_dân về công_tác phòng , chống tham_nhũng . 
Đảng_viên , nhất_là cán_bộ lãnh_đạo , phải nêu gương về đạo_đức , lối sống và kiên_quyết chống tham_nhũng ; nâng_cao tính tiên_phong , gương_mẫu của tổ_chức Đảng và đảngviên , tăng_cường vai_trò của chi_bộ đảng trong quản_lý , giáo_dục đảng_viên ; tiếp_tục hoàn_thiện công_tác cán_bộ phục_vụ công_tác phòng , chống tham_nhũng ; bảo_đảm công_khai , minh_bạch trong hoạt_động của các cơ_quan , tổ_chức , đơn_vị ; tiếp_tục hoàn_thiện cơ_chế , chính_sách về quản_lý kinh_tế - xã_hội ; nâng_cao chất_lượng , hiệu_quả công_tác kiểm_tra , thanh_tra , kiểm_toán , điều_tra , truy_tố , xét_xử hành_vi tham_nhũng ; thực_hiện tốt công_tác truyền_thông về phòng , chống tham_nhũng ; xây_dựng , kiện_toàn các cơ_quan , đơn_vị chuyên_trách về phòng , chống tham_nhũng được thành_lập theo Luật phòng , chống tham_nhũng ; tăng_cường giám_sát của nhân_dân và cơ_quan_dân_cử ; tăng_cường hợp_tác quốc_tế về phòng , chống tham_nhũng . 
Một trong những nội_dung quan_trọng Hội_nghị Trung_ương 9 đề ra nhằm tiếp_tục thực_hiện thắng_lợi Nghị_quyết Đại_hội X của Đảng , xây_dựng Đảng , hệ_thống chính_trị và phát_huy dân_chủ xã_hội là làm tốt công_tác phòng , chống tham_nhũng : Tạo chuyển_biến mạnh_mẽ trong thực_hành tiết_kiệm , phòng , chống tham_nhũng , lãng_phí , quan_liêu . 
Tiếp_tục đẩy_mạnh thực_hiện Nghị_quyết Trung_ương 3 khoá X về phòng , chống tham_nhũng , lãng_phí . 
Tập_trung rà_soát , bổ_sung , hoàn_thiện cơ_chế , chính_sách ; thực_hiện nghiêm các quy_định của Đảng , Nhà_nước về phòng , chống tham_nhũng , lãng_phí . 
Tăng_cường công_tác kiểm_tra , thanh_tra , kiểm_toán , giám_sát ; phối_hợp thật tốt giữa các cơ_quan kiểm_tra , thanh_tra , kiểm_toán , giám_sát , nhất_là khi giải_quyết các trường_hợp có dấu_hiệu tham_nhũng , lãng_phí . 
Kiên_quyết xử_lý nghiêm kỷ_luật đảng , kỷ_luật hành_chính và xử_lý bằng pháp_luật các vụ_việc tham_nhũng , tịch_thu tài_sản tham_nhũng . 
Kiện_toàn hệ_thống các cơ_quan chuyên_trách về phòng , chống tham_nhũng . 
Phát_huy vai_trò của nhân_dân , các tổ_chức chính_trị - xã_hội , của báo_chí trong đấu_tranh phòng , chống tham_nhũng , lãng_phí , quan_liêu ; có chính_sách bảo_vệ người dũng_cảm đấu_tranh chống tham_nhũng , lãng_phí . 
Hội_nghị Trung_ương 4 khoá XI đã ban_hành Nghị_quyết về Một_số vấn_đề cấp_bách về xây_dựng Đảng hiện_nay , trong đó chú_trọng tăng_cường công_tác kiểm_tra , giám_sát , thanh_tra , kiểm_toán , điều_tra , truy_tố , xét_xử để nâng_cao hiệu_quả công_tác phòng , chống tham_nhũng , lãng_phí . 
Sớm tổng_kết toàn_diện công_tác đấu_tranh phòng , chống tham_nhũng , lãng_phí , thực_hành tiết_kiệm ; bổ_sung , sửa_đổi Luật Phòng , chống tham_nhũng . 
Kiện_toàn và tăng_cường trách_nhiệm , nâng_cao hiệu_quả hoạt_động của cơ_quan phòng , chống tham_nhũng . 
Xét_xử nghiêm những vụ án tham_nhũng , trước_hết là những vụ nghiêm_trọng , phức_tạp , được nhân_dân quan_tâm . 
Để tiếp_tục thực_hiện Nghị_quyết Hội_nghị Trung_ương 3 khoá X về Tăng_cường sự lãnh_đạo của Đảng đối_với công_tác phòng , chống tham_nhũng , lãng_phí , Hội_nghị Trung_ương 5 khoá XI đề ra 6 giải_pháp : nâng_cao vai_trò , trách_nhiệm của các cấp_uỷ , tổ_chức đảng , chính_quyền , người đứng đầu cơ quan , tổ_chức , đơn_vị trong phòng , chống tham_nhũng , lãng_phí ; tiếp_tục hoàn_thiện thể_chế về quản_lý kinh_tế - xã_hội để phòng , chống tham_nhũng , lãng_phí ; tiếp_tục hoàn_thiện và thực_hiện nghiêm cơ_chế , chính_sách về công_tác tổ_chức , cán_bộ để phòng , chống tham_nhũng , lãng_phí ; tiếp_tục hoàn_thiện thể_chế và tăng_cường công_tác kiểm_tra , thanh_tra , kiểm_toán , điều_tra , truy_tố , xét_xử để nâng_cao hiệu_quả công_tác phòng , chống tham_nhũng , lãng_phí ; tăng_cường vai_trò giám_sát của cơ_quan_dân_cử và nhân_dân trong phòng , chống tham_nhũng , lãng_phí ; đổi_mới , nâng_cao năng_lực của cơ_quan lãnh_đạo , chỉ_đạo và cơ_quan thường_trực , tham_mưu về công_tác phòng , chống tham_nhũng . 
Ở Trung_ương , thành_lập Ban Chỉ_đạo Trung_ương về phòng , chống tham_nhũng trực_thuộc Bộ Chính_trị , do đồng_chí Tổng_Bí_thư làm Trưởng ban . 
Ở địa_phương , tỉnh_uỷ , thành_uỷ trực_tiếp lãnh_đạo công_tác phòng , chống tham_nhũng và có trách_nhiệm phối_hợp với Ban Chỉ_đạo Trung_ương về phòng , chống tham_nhũng khi có vụ_việc tham_nhũng nghiêm_trọng xảy_ra ở địa_phương . 
Hội_nghị Trung_ương 8 khoá XI của Đảng tiếp_tục đề ra mục_tiêu , nhiệm_vụ và giải_pháp phát_triển kinh_tế - xã_hội năm 2014-2015 , trong đó , đề_cao các giải_pháp về phòng , chống tham_nhũng , thực_hành tiết_kiệm , chống lãng_phí làđẩy mạnh thực_hiện cải_cách tư_pháp ; tăng_cường kỷ_luật , kỷ_cương , công_khai , minh_bạch hoạt_động của cơ_quan , cán_bộ , công_chức nhà_nước , thanh_tra , kiểm_tra , giám_sát , kiểm_toán , xử_lý nghiêm các vi_phạm ; đẩy_mạnh cải_cách chế_độ công_vụ , đề_cao trách_nhiệm trong thực_thi công_vụ , nhất_là trách_nhiệm của người đứng đầu ; nâng_cao hiệu_quả công_tác giải_quyết khiếu_nại , tố_cáo , xử_lý kịp_thời tại các cơ_sở , hạn_chế phát_sinh các khiếu_nại vượt cấp , đông người ; giải_quyết dứt_điểm các vụ_việc khiếu_kiện tồn_đọng , kéo dài . 
Để không ngừng tăng_cường kỷ_cương , kỷ_luật của Đảng và giữ_gìn phẩm_chất chính_trị , đạo_đức cách_mạng , tính tiên_phong gương_mẫu của cán_bộ , đảng_viên , nâng_cao năng_lực lãnh_đạo và sức chiến_đấu của tổ_chức đảng , qua các kỳ đại_hội , từ Đại_hội IX đến Đại_hội XI của Đảng , Bộ Chính_trị đã ban_hành Quy_định về Những điều đảng_viên không được làm , trong đó quy_định rõ những hành_vi nghiêm_cấm đảng_viên không được làm , như : quan_liêu , thiếu trách_nhiệm , bao_che , báo_cáo sai sự_thật , để cơ_quan , đơn_vị , địa_phương do mình trực_tiếp phụ_trách xảy_ra tình_trạng mất đoàn_kết , tham_nhũng , lãng_phí , thất_thoát tài_sản và các tiêu_cực khác hoặc đưa , nhận , môi_giới hối_lộ ; môi_giới làm thủ_tục hành_chính hoặc lợi_dụng vị_trí công_tác để môi_giới hưởng thù_lao dưới mọi hình_thức trái quy_định , đưa , nhận hoa_hồng hoặc môi_giới đưa , nhận hoa_hồng trái quy_định ... 
Cụ_thể_hoá quan_điểm , chỉ_đạo của Đảng , Nhà_nước đã ban_hành hệ_thống pháp_luật làm cơ_sở pháp_lý trong đấu_tranh phòng , chống tham_nhũng . 
Với sự quyết_tâm , nỗ_lực của các tổ_chức Đảng , Nhà_nước , Mặt_trận Tổ_quốc và cả hệ_thống chính_trị , công_tác phòng , chống tham_nhũng , lãng_phí đã có những chuyển_biến tích_cực cả về nhận_thức , hành_động và đạt được những kết_quả bước_đầu , nhất_là trong phòng_ngừa , công_khai , minh_bạch_hoá , cải_cách thủ_tục hành_chính , quản_lý tài_sản công . 
Trên một_số lĩnh_vực , tham_nhũng , lãng_phí đã từng bước được kiềm_chế . 
