Ý_nghĩa lịch_sử và giá_trị bền_vững của Đề_cương văn_hoá Việt_Nam 
Đề_cương văn_hoá Việt_Nam là một văn_kiện quan_trọng của Đảng , do Tổng_Bí_thư Trường_Chinh soạn_thảo năm 1943 . 
Đề_cương ra_đời như ngọn đèn_pha soi_rọi cho nền văn_hoá cách_mạng phát_triển trong sự_nghiệp đấu_tranh giành độc_lập , tự_do cho dân_tộc . 
70 năm qua , Đề_cương Văn_hoá Việt_Nam vẫn giữ nguyên giá_trị lịch_sử và hiện_thực sâu_sắc , chỉ_đạo tiến_trình phát_triển văn_hoá ở nước ta hiện_nay . 
Ở nước ta vào đầu những năm 40 thế_kỷ XX , tình_hình kinh_tế , văn_hoá , xã_hội rất rối_ren và phức_tạp . 
Thực_dân Pháp đã biến Việt_Nam thành thuộc_địa kiểu cũ , nhưng nước Pháp lại thua trận rơi vào tay phátxít Đức và phátxít Nhật nhảy vào Đông_Đương ( 9-1940 ) . 
Nhân_dân ta lầm_than trong tình_cảnh một_cổ_hai_tròng . 
Vì thế , vùng dậy đấu_tranh , đuổi giặc , cứu nước có ý_nghĩa sống_còn đối_với toàn dân_tộc . 
Vấn_đề huy_động lực_lượng cho một cuộc cách_mạng làm thay_đổi vận_mệnh dân_tộc trở_nên bức_thiết hơn bao_giờ hết . 
Nhưng , để làm được điều đó , trước_tiên cần phải có một bước mở_đầu về lý_luận làm tiền đề . 
Bởi , chỉ có như vậy mới thức_tỉnh được quần_chúng , định_hướng được nguồn_lực , quy_tụ được sức_mạnh . 
Đối_tượng phù_hợp nhất cho bước mở_đầu này , không_thể là ai khác ngoài tầng_lớp trí_thức đương_thời . 
Nhưng bản_thân tầng_lớp này , như thực_tế lịch_sử cho_thấy , lại đang bị chia_rẽ bởi những khuynh_hướng văn_hoá - tư_tưởng khác nhau . 
Ngay sau khi phátxít Nhật nhảy vào Đông_Dương , một bộ_phận trí_thức tỏ_ra  thức_thời  - một mặt họ chủ_trương bài Pháp , quay sang chê_bai và miệt_thị văn_hoá phương Tây , mặt_khác lại tỏ rõ lòng tin mù_quáng vào thuyết  đồng_văn , đồng_chủng  , ca_ngợi hết lời phong_tục , tập_quán và tinh_thần  võ_sĩ_đạo  của văn_hoá Nhật . 
Trào_lưu  cạo trọc đầu  , nói tiếng Nhật bồi , ... nhanh_chóng trở_thành  mốt  . 
Một_số người trong số này còn cam_tâm làm tay_sai cho Nhật , lún sâu vào con đường phản nước , hại dân . 
Trong khi đó , một bộ_phận trí_thức khác thì ngược lại , tỏ rõ lòng trung_thành với  cố_nhân  , tung_hô khẩu_hiệu  Pháp - Việt phục_hưng  , hết_lòng ca_ngợi công_lao  khai_sáng  của Pháp , nhiệt_thành chứng_minh cho sự  đồng_quy  giữa tôn_chỉ  cần_lao , gia_đình , Tổ_quốc  của văn_hoá Pháp với truyền_thống Nho_giáo trước đó của văn_hoá Việt_Nam . 
Một_số trí_thức cực_đoan dưới sự hậu_thuẫn của Pháp , đã chuyển sang công_khai chống lại Đảng Cộng_sản Đông_Dương , phủ_nhận và bôi_nhọ lịch_sử dân_tộc . 
Còn phần_lớn trí_thức Việt_Nam lúc bấy_giờ , dù giàu lòng tự_tôn dân_tộc , đặc_biệt khát_khao về dân_chủ và tự_do , nhưng do chưa được thức_tỉnh về con đường giải_phóng dân_tộc nên , hoặc là còn đang mò_mẫm tìm đường , hoặc là  án_binh_bất_động  , nghe_ngóng , chờ thời . 
Nhiều người trong số họ tìm thú_vui trong những  nghiên_cứu  vô thưởng , vô phạt hay tự thoả_mãn với những tìm_tòi siêu_thực , bí_hiểm , ... 
Trong bối_cảnh ấy , để thức_tỉnh được tầng_lớp trí_thức đang bị chia_rẽ , qua đó thức_tỉnh được quần_chúng nhân_dân , Đảng phải có một đường_lối văn_hoá thực_sự đúng_đắn , khoa_học và phù_hợp . 
Đường_lối này phải bảo_đảm tính chính_xác , khách_quan , thu_phục được tầng_lớp trí_thức , thống_nhất được nhận_thức của họ . 
Nó cũng phải bảo_đảm tính lôgíc , ngắn_gọn và dung_dị để dễ_dàng truyền_bá tới quảng_đại quần_chúng trong điều_kiện Đảng chưa ra hoạt_động công_khai . 
Đặc_biệt , đường_lối này cũng phải thể_hiện rõ nguyên_tắc tính_đảng , tính chiến_đấu nhằm hiệu_triệu toàn dân theo Đảng bước vào một mặt_trận đầy cam_go , nhưng sẽ quyết_định tương_lai của toàn dân_tộc - mặt_trận văn_hoá . 
Trên thực_tế , Đề_cương văn_hoá đáp_ứng đầy_đủ các yêu_cầu trên đây và còn hơn thế nữa . 
Điều đó tự nó quy_định ý_nghĩa và giá_trị to_lớn về nhiều mặt của văn_kiện đặc_biệt này đối_với tiến_trình cách_mạng Việt_Nam . 
Đề_cương văn_hoá Việt_Nam ( 1943 ) sở_dĩ có sức lan_toả mạnh_mẽ và giá_trị bền_vững , bởi bản_thân nội_dung và cấu_trúc của nó được tạo_dựng và hoàn_chỉnh với một phương_pháp tiếp_cận thực_sự khoa_học . 
Dù là một văn_kiện nhỏ , với dung_lượng chỉ khoảng 1300 từ , nhưng Đề_cương lại là một công_trình khoa_học thực_sự , lần đầu_tiên trình_bày văn_hoá Việt_Nam và những vấn_đề có liên_quan như một hệ_thống cấu_trúc với một phương_pháp tiếp_cận nhất_quán . 
Khác với tính_chất phiến_diện , một chiều thường thấy trong các công_trình nghiên_cứu trước đó , Đề_cương văn_hoá đã trình_bày văn_hoá như một hệ_thống bao_gồm nhiều mặt , nhiều yếu_tố , nhiều quá_trình khác nhau , nhưng có liên_quan chặt_chẽ với nhau : giữa tư_tưởng , học_thuật và nghệ_thuật ; giữa văn_hoá , kinh_tế và chính_trị ; giữa các nguyên_tắc dân_tộc , đại_chúng và khoa_học ; giữa lịch_sử , nguy_cơ và triển_vọng , ... 
Đề_cương văn_hoá đã đặt các mặt , các yếu_tố , các quá_trình trên đây trong mối quan_hệ qua_lại tất_yếu với nhau , qua đó , làm nổi_bật hệ_thống các quy_luật đã và đang chi_phối sự vận_động và phát_triển của văn_hoá Việt_Nam . 
Với luận_điểm  ... nền_tảng kinh_tế của một xã_hội và chế_độ kinh_tế dựng trên nền_tảng ấy quyết_định toàn_bộ văn_hoá của xã_hội kia  ( 1 ) , Đề_cương văn_hoá đã thực_sự đem lại một bước_tiến mới về chất so với các phương_pháp tiếp_cận đương_thời về văn_hoá Việt_Nam . 
Ở đó , với tư_cách là một bộ_phận của kiến_trúc_thượng_tầng , văn_hoá phải phản_ánh hiện_thực và do cơ_sở kinh_tế quyết_định . 
Đây chính là một nội_dung căn_bản của một trong những quy_luật cơ_bản nhất của chủ_nghĩa_duy_vật lịch_sử . 
Với phương_pháp tiếp_cận này , Đề_cương văn_hoá đã trình_bày và cắt_nghĩa khá chính_xác theo lập_trường mácxít những vấn_đề cốt_lõi nhất của văn_hoá Việt_Nam đương_đại : từ lịch_sử có tính giai_đoạn đến tính_chất của từng giai_đoạn lịch_sử trong tiến_trình phát_triển văn_hoá Việt_Nam ; từ những nguy_cơ hiện_hữu đến những nguyên_tắc vận_động của nó ; từ tiền_đồ đến mục_đích trước_mắt cũng như những việc cần_kíp của những nhà_văn_hoá , ... 
Không dừng lại ở đó , với sức_mạnh của công_cụ nhận_thức khoa_học , Đề_cương văn_hoá đã tiến xa hơn khi vạch ra lộ_trình của cuộc vận_động văn_hoá Việt_Nam với những hình_thức , bước đi và mục_tiêu phù_hợp với điều_kiện lịch_sử . 
Theo đó , mặc_dù khẳng_định  Nền văn_hoá mà cuộc cách_mạng văn_hoá Đông_Dương phải thực_hiện sẽ là văn_hoá xã_hội_chủ_nghĩa  ( 2 ) , nhưng trên cơ_sở phân_tích điều_kiện kinh_tế , chính_trị , xã_hội lúc bấy_giờ , Đề_cương văn_hoá đã xác_định tính_chất của nền văn_hoá mới mà Đảng ta chủ_trương  chưa phải là văn_hoá xã_hội_chủ_nghĩa hay văn_hoá Xôviết  ( 3 ) . 
Đây là một nhận_định rất đúng_đắn , cho_phép ngăn_ngừa ngay từ đầu những biểu_hiện chủ_quan , duy_ý_chí mang tính_chất  tả_khuynh  . 
Cũng theo lôgíc ấy , dựa chắc vào nguyên_tắc lấy hiện_thực lịch_sử làm tiền đề , Đề_cương văn_hoá đã xác_định dân_tộc_hoá , đại_chúng_hoá và khoa_học_hoá là ba nguyên_tắc vận_động cho cuộc vận_động văn_hoá Việt_Nam đương_đại . 
Khẳng_định phải dân_tộc_hoá vì văn_hoá Việt_Nam khi đó dưới ách áp_bức của phátxít , thực_dân đã và đang bị nô_dịch và chia_rẽ nặng_nề . 
Đó là một nền văn_hoá thiếu hẳn tinh_thần độc_lập , tự_do và thống_nhất dân_tộc . 
Đặt nguyên_tắc khoa_học_hoá lên vị_trí ưu_tiên vì một nền văn_hoá muốn thực_sự mang tính_cách_mạng , trước_hết nó phải có một nền_tảng khoa_học chắc_chắn làm tiền đề . 
Trong khi đó , ở một nước nông_nghiệp lạc_hậu thì chủ_nghĩa_kinh_nghiệm thường lấn_át tri_thức khoa_học và khoa_học trong một nước bị đô_hộ thì khó mà được ưu_tiên phát_triển . 
Đại_chúng_hoá là một nguyên_tắc của vận_động văn_hoá vì quần_chúng là cội_nguồn của sức_mạnh , là chủ_thể đích_thực của mọi giá_trị văn_hoá . 
Nhưng trên thực_tế lúc đó , văn_hoá lại đang trở_thành , hoặc là thứ xa_xỉ mà quần_chúng không_thể với tới , hoặc là những sản_phẩm độc_hại , phản giá_trị mà quần_chúng không_thể thụ_hưởng . 
Có_thể nói , ba nguyên_tắc nêu trên là cơ_bản nhất , không_thể tách_rời nhau , phản_ánh đúng nhất thực_trạng và nhu_cầu bức_thiết của cuộc vận_động văn_hoá Việt_Nam lúc bấy_giờ . 
Đồng_thời , đây cũng là ba khẩu_hiệu hành_động , kêu_gọi đội_ngũ trí_thức tập_hợp lực_lượng , xây_dựng một nền văn_hoá mới cho tương_lai của dân_tộc . 
Điều đặc_sắc nhất của Đề_cương văn_hoá là ở chỗ , mặc_dù là công_trình về văn_hoá nhưng lại không chủ_yếu bàn về văn_hoá nói_chung , không quá chú_trọng đến các vấn_đề về học_thuật hay câu từ mà tư_tưởng xuyên_suốt là vấn_đề về văn_hoá giải_phóng và giải_phóng văn_hoá Việt_Nam khỏi xiềng_xích của văn_hoá trung_cổ và nô_dịch . 
Đề_cương văn hóanhiều lần được bổ_sung , hoàn_thiện cùng tiến_trình phát_triển của cách_mạng Việt_Nam . 
Tổng_Bí_thư Trường_Chinh là người khởi_thảo Đề_cương văn_hoá Việt_Nam đồng_thời , cũng là người tiếp_tục bổ_sung và hoàn_thiện đường_lối văn_hoá của Đảng cho phù_hợp với yêu_cầu của mỗi giai_đoạn cách_mạng . 
Trong các bài Mấy nguyên_tắc lớn của cuộc vận_động văn_hoá mới Việt_Nam lúc này ( 1943 ) ; Một con quỷ đội_lốt mácxít ( 1945 ) và đặc_biệt là trong báo_cáo trình_bày tại Hội_nghị văn_hoá toàn_quốc lần thứ hai ( 7-1948 ) với tiêu_đề Chủ_nghĩa_Mác và văn_hoá Việt_Nam , Tổng_Bí_thư Trường_Chinh đã làm rõ hàng_loạt vấn_đề mà Đề_cương văn_hoá chưa có_điều_kiện trình_bày hoặc trình_bày một_cách chưa đầy_đủ , chưa thuyết_phục , như : khái_niệm mở_rộng về văn_hoá ; về nội_dung , tính_chất , mối quan_hệ giữa các nguyên_tắc ; về Tờrốtkít ở Việt_Nam ; về nội_dung và hình_thức của nền văn_hoá mới cũng như vấn_đề kế_thừa có chọn_lọc các nền văn_hoá khác nhau trên thế_giới để làm_giàu nền văn_hoá Việt_Nam . 
Cũng với tinh_thần cầu_thị , sau báo_cáo Chủ_nghĩa_Mác và văn_hoá Việt_Nam , đường_lối văn_hoá còn tiếp_tục được mở_rộng điều_chỉnh và hoàn_thiện bằng hàng_loạt các chủ_trương , nghị_quyết về văn_hoá và văn_nghệ của Đảng . 
Trong thời_kỳ đổi_mới , với quan_điểm xây_dựng văn_hoá là nền_tảng tinh_thần xã_hội , Hội_nghị lần thứ năm Ban chấp_hành Trung_ương Đảng ( khoá VIII ) đã ra  Nghị_quyết về xây_dựng và phát_triển nền văn_hoá Việt_Nam tiên_tiến , đậm_đà bản_sắc dân_tộc  ... 
70 năm đã trôi qua kể từ khi Đề_cương văn_hoá ra_đời , cách_mạng Việt_Nam đã trải_qua một chặng đường dài với những giai_đoạn chuyển_đổi theo định_hướng XHCN . 
Nghiên_cứu sự ra_đời và quá_trình bổ_sung , phát_triển của Đề_cương văn_hoá , chúng_ta đúc_rút được những bài_học quý_báu : 
Thứ nhất , bài_học về sự không ngừng bổ_sung , phát_triển chủ_trương , đường_lối cho phù_hợp với yêu_cầu thực_tế . 
Đường_lối , chủ_trương , chính_sách , ... có_thể có_hạn_chế , sai_lầm , cũng như một con_người khó có_thể tránh khỏi những những hạn_chế , khuyết_điểm . 
Vấn_đề là ở chỗ , thái_độ đối_với khuyết_điểm , hạn_chế đó như thế_nào . 
Từ_chối nhận khuyết_điểm , hạn_chế , sai_lầm sẽ không có cơ_may sửa_chữa để phát_triển . 
Nhưng thừa_nhận khuyết_điểm , sai_lầm rồi cho_qua_chuyện mà không thực_sự quyết_tâm sửa_chữa thì đó là một nguy_cơ thực_sự của một đảng cầm_quyền . 
Bài_học này dù không mới , nhưng chưa bao_giờ cũ , nhất_là trong bối_cảnh hiện_nay . 
Thứ hai , bài_học về mối quan_hệ giữa  chống  và  xây  trong đấu_tranh tư_tưởng , lý_luận . 
Thực_tế cho_thấy , trong quá_trình phát_triển cách_mạng , nhất_là ở những thời_điểm chuyển_đổi có tính_chất bước_ngoặt thì các thế_lực thù_địch ra_sức tấn_công Đảng ta trên mặt_trận văn_hoá , tư_tưởng . 
Cuộc đấu_tranh chống lại những tư_tưởng thù_địch là tất_yếu và hết_sức quyết_liệt . 
Nhưng vấn_đề là ở chỗ , trong khi luận_chiến chống lại những tư_tưởng thù_địch , chúng_ta phải luôn coi việc xây_dựng , hoàn_thiện , làm mới hệ_tư_tưởng của Đảng là chính , là nhân_tố giữ vai_trò quyết_định cho thắng_lợi của cuộc đấu_tranh trên lĩnh_vực này . 
 Chống  mà không  xây  , thì chúng_ta sẽ bị tụt_hậu về mặt lý_luận , do đó , sẽ gặp nhiều khó_khăn trong đấu_tranh chống lại kẻ_thù tư_tưởng của Đảng . 
Thứ ba , bài_học về việc giải_quyết mối quan_hệ giữa kinh_tế và văn_hoá trong quá_trình phát_triển . 
Đã có thời vì quá đề_cao  văn_hoá tập_thể  nên chúng_ta đã lảng_tránh kinh_tế_thị_trường , coi đó như là  cha đẻ  của chủ_nghĩa_cá_nhân vị kỷ . 
Nhưng đã có lúc , hình_như chúng_ta lại quá nhấn_mạnh kinh_tế_thị_trường mà bài_xích  chủ_nghĩa tập_thể  , coi đó như là rào_cản của mọi sự phát_triển . 
Thực_ra , đó là hai thái_cực của cùng một sai_lầm , bệnh cực_đoan . 
Thực_tiễn cho_thấy rằng , sự  thiếu_hụt văn_hoá  không_chỉ là sản_phẩm của tình_trạng kinh_tế lạc_hậu , kém phát_triển mà_còn là  cái giá phải trả  của sự phát_triển kinh_tế nhưng không được định_hướng về mặt văn_hoá . 
Đơn_giản bởi_vì , văn_hoá vừa là mục_tiêu , vừa là động_lực phát_triển kinh_tế - xã_hội . 
Lịch_sử sẽ tiếp_tục phát_triển với những bước quanh_co , phức_tạp , nhưng tinh_thần của Đề_cương văn_hoá Việt_Nam vẫn còn nguyên các giá_trị lịch_sử và đương_đại sâu_sắc . 
Đề_cương văn_hoá Việt_Nam vẫn là một cương_lĩnh chỉ_đạo tiến_trình phát_triển văn_hoá ở nước ta hiện_nay . 
Tuy_nhiên , cũng cần hiểu rằng , giá_trị đó phải được vận_dụng và cụ_thể_hoá trong điều_kiện mới hiện_nay 
�_thể_hoá trong điều_kiện mới hiện_nay 
