Những tác_động của các thể_chế quốc_tế đến nhà_nước quốc_gia trong bối_cảnh toàn_cầu_hoá 
Hầu_hết các nước trên thế_giới , bất_kể là nước phát_triển , đang phát_triển , chậmphát triển cũng đang trải_qua quá_trình hội_nhập kinh_tế quốc_tế ở các mức_độ khác nhauvàchịu những ảnh_hưởng , tác_động từ quá_trình hội_nhập , toàn_cầu_hoá . 
Từ quá_trình này , nền kinh_tế liên_kết giữa các quốc_gia , dòng dịch_chuyển thực_sự của hoạt_động tài_chính và công_nghiệp đã và đang xoá nhòacác đường biên_giới quốc_gia trên bản_đồ . 
Những đường biên_giới này đã và đang biếnmất trên phạm_vi rộng_lớn , theo đó quyền lựccủa các nhà_nước quốc_gia đối_với các vấn_đề như tỷgiá hối_đoái , mức thuế , chính_sách_công_nghiệp , tỷlệ thất_nghiệp và nhiều vấn_đề khác cũng bị suy_giảm . 
Đi cùng với hội_nhập kinh_tế thế_giới và toàn_cầu_hoá là sự xuất_hiện ngày_càng nhiều những vấn_đề có tính toàn_cầu . 
Những vấn_đề bức_xúc đối vớicác quốc_gia và cộng_đồng quốc_tế như : bệnh dịch ; môi_trường ; tội_phạm xuyên biên_giới ; khủng_bố ... 
Đối_với các vấn_đề này , các quốc_gia không_thể đơn_phương giải_quyết được mà cần có sự hợp_tác , tham_gia của nhiều nước . 
Theo xu_hướng này , xuất_hiện ngày_càng nhiều các tổ_chức , thể_chế quốc_tế liên_kết giữa các quốc_gia một_cách chính_thức hoặc không chính_thức để giải_quyết những vấn_đề vượt khỏi phạm_vi quốc_gia hoặc thiếu sự quản_trị của quốc_gia . 
Sự phát_triển của sự tương_tác toàn_cầu đã tạo nên một tình_huống phụ_thuộc lẫn nhau , sự phụ_thuộc này mang một tính_chất mới và được các nhà nghiên_cứu gọi là  sự tương thuộc phức_hợp  ( Complex_Interdepedence ) ( 1 ) . 
Sự tương thuộc , một mặt , tạo ra nhiều lợi_ích cho các quốc_gia nhưng mặt_khác cũng lấy đi khả_năng của phần_lớn nhà_nước quốc_gia khi đưa ra quyết_định của mình . 
Như vậy , toàn_cầu_hoá không có nghĩa là sự chuyển_hoá của các nhà_nước quốc_gia mà_còn là quá_trình các nhà_nước quốc_gia ngày_càng bị giới_hạn trong việc theo_đuổi các chính_sách tự_chủ . 
Thay vào đó , sự hình_thành các liên_minh khu_vực về kinh_tế và chính_trị với việc thiết_lập các cấu_trúc quyền_lực mới của các thể_chế quốc_tế đã dần xoá_bỏ các đường biên_giới lãnh_thổ và làm suy giảmquyền tự_trị của các quốc_gia , thông_qua việctrao quyền kiểm_soát cho các chủ_thể siêu_quốc_gia - các thể_chế quốc_tế . Để có_thể góp_phần làm sáng_tỏ thêm những vấn_đề liên_quan đến chủ_đề này , cần có sự xem_xét cụ_thể hơn mối quan_hệ giữa các thể_chế quốc_tế và nhà_nước quốc_gia trong bối_cảnh hiện_nay . 
Thứ nhất , các thể_chế quốc_tế có quyền ban_hành và thực_thi luật về những vấn_đề nhất_định và làm suy_giảm quyền tự_trị pháp_lý của nhà_nước quốc_gia 
Một mặt , các thể_chế quốc_tế là sản_phẩm của chủ_quyền quốc_gia vì chúng được tạo nên thông_qua sự cam_kết tự_nguyện giữa các quốc_gia thành_viên , nhưng mặt_khác nó mâu_thuẫn căn_bản với những hiểu_biết có tính quy_ước về chủ_quyền quốc_gia vànhững cam_kết , hiệp ướcnày đã làm suy_giảm quyền tự_trị pháp_lý của các thành_viên ( 2 ) .Chẳng hạn , Liên_minh châu Âu hiện đã có những cơ_chế ảnh_hưởng sâu_rộng nhất trong số các hệ_thống hội_nhập khu_vực hiện_nay , trong đó Uỷ_ban châu Âu vừa là cơ_quan hành_pháp vừa là cơ_quan_hành_chính của EU . 
Uỷ_ban này có quyền đưa ra sáng_kiến , có nghĩa là quyền đưa ra dự_thảo luật của EU , đồng_thời thực_hiện nhiệm_vụ giám_sát quan_trọng xem các quốc_gia thành_viên thực_hiện luật_định của EU . 
Từ đó có_thể khiển_trách một quốc_gia thành_viên bằng các yêu_cầu chấm_dứt vi_phạm , hoặc đưa vấn_đề ra Toà_án Công_lý châu Âu . 
Toà_án này cũng đóng vai_trò giám_sát việcthực thi_pháp luật của các quốc_gia thành_viên . 
Cơ_chế thực_thi pháp_luật của EU thông_qua hai nguyên_tắc : quyền_lực tối_cao và ảnh_hưởng trực_tiếp . 
Nguyên_tắc quyền_lực tối_cao cho rằng , luật_pháp của EU đứng trên luật_pháp quốc_gia ; nguyên_tắc ảnh_hưởng trực_tiếp có nghĩa là pháp_luật EU có_thể áp_dụng trực_tiếp cho công_dân các quốc_gia thành_viên mà không cần can_thiệp trước bởi chính_phủ của họ . 
Trong một bước_tiến quan_trọng để nâng_cao hiệu_quả của toà_án , EU đã trao cho toà_án quyền có_thể áp_đặt những chế_tài lên các quốc_gia thành_viên không tuân_thủ các quy_định của Toà_án . 
Như vậy , các thể_chế quốc_tế có_thể thực_hiện sự áp_đặt đối_với các quốc_gia thiếu quản_lý hay chưa tuân_thủ hệ_thống quốc_tế ; chúng có_thể sử_dụng lực_lượng và quyền_lực được trao bởi nhà_nước thành_viên để đạt mục_tiêu của mình . 
Ở mức_độ nhất_định , các luật_lệ , chuẩn_mực và thủ_tục được hình_thành bởi các thể_chế quốc_tế sẽ thay_thế ở mức_độ nào đó luật_pháp quốc_gia . 
Thứ hai , thể_chế quốc_tế tạo ra những áp_lực cải_cách , ảnh_hưởng đến cấu_trúc chính_trị các nước muốn gia_nhập 
Do có những điều_kiện cho việc gia_nhập thể_chế quốc_tế , nên các nước muốn gia_nhập phải có đủ điều_kiện và được sự ủng_hộ của các thành_viên . 
Chúng được gọi là những điều_kiện chính_trị trong nước cho việc gia_nhập thể_chế quốc_tế . 
Chính những  điều_kiện của nước thành_viên sẽ có những ảnh_hưởng quan_trọng đến cấu_trúc chính_trị trong nước của nước muốn gia_nhập  ( 3 ) . 
Để có_thể trở_thành thành_viên của thể_chế quốc_tế , các nước buộc phải thay_đổi các quy_định , luật_lệ trong nước , tạo hành_lang pháp_lý theo những cam_kết chung và phù_hợp với pháp_luật , chuẩn_mực và thông_lệ quốc_tế . 
Mặt_khác , cần phải có sự ủng_hộ trong nước đối_với những quy_định , luật_lệ đi cùng với sự gia_nhập ( 4 ) . 
Đây là điều không_thể tránh vì khi liên_kết và cam_kết thực_hiện những luật_lệ , quy_định chung , tham_gia vào một sân_chơi chung , các quốc_gia đều phải tuân_thủ luật chơi chung chứ không_thể chỉ áp_dụng theo luật của riêng mình . 
Bản_thân nhà_nước cũng bị áp_lực phải thay_đổi cách_thức tổ_chức , quản_lý , điều_hành đối_với các lĩnh_vực . 
Các hình_thức quản_lý , điều_hành xã_hội theo kiểu truyền_thống của nhà_nước cũng không còn phù_hợp trong thời_đại  thếgiới phẳng  . 
Theo đó , quyền_lực của nhà_nước cũng thay_đổi theo xu hướngnhà nước không còn là chủ_thể độc_tôn , có quyền quyết_định duy_nhất đối_với xã_hội . 
Quá_trình ra quyết_định của nhà_nước cũng không_thể bó_hẹp và khép_kín trong nhóm các nhà lãnh_đạo như trước đây , mà có sự tham_gia và ảnh_hưởng của nhiều chủ_thể , nhiều yếu_tố khác nhau trong và ngoài nước . 
Thứ ba , các thể_chế quốc_tế tạo thuận_lợi cho những thay_đổi , cải_cách chính_trị của nhà_nước quốc_gia 
Việc tham_gia vào các thể_chế liên_quốc_gia buộc các nước phải tuân_thủ các luật_lệ , chuẩn_mực và điều đó đưa đến những hệ_quả chính_trị . 
Các thể_chế có_thể hỗ_trợ các quốc_gia thay_đổi chính_sách trong nước cho phù_hợp với xu_thế chung . 
Các thể_chế quốc_tế cũng có_thể giúp các nhà lãnh_đạo khởi_động , khuyến_khích các nhóm lợi_ích có_thể đề_xuất các chính_sách mới . 
Có_thể nói , đối_với nhiều vấn_đề  các thể_chế quốc_tế có_thể tạo nên mức_độ chính_đáng và làm cho những thay_đổi khó_khăn trong nước dễ_dàng hơn thông_qua việc trao cho nhà_nước thành_viên một  nhãn_hiệu  chính_trị ( 5 ) . 
Các nhà nghiên_cứu quan_hệ quốc_tế , khi bàn về chức_năng và lợi_ích của các thể_chế quốc_tế đã cho rằng , các nước sẽ được hưởng lợi từ các thể_chế này . 
Các quốc_gia thường có quyết_định gia_nhập chỉ khi lợi_ích dòng lớn hơn lợi_ích có được khi họ ở bên ngoài các thể_chế . 
Việc gia_nhập liên_minh là tự_nguyện , các tác_động từ sự gia_nhập có_thể là cả tích_cực và tiêu_cực , nên việc lựa_chọn gia_nhập chỉ được quyết_định khi gia_nhập sẽ chịu tác_động ít tiêu_cực hơn những gì họ phải gánh_chịu nếu tồn_tại bên ngoài các thể_chế này . 
Tuy cái giácủa việc gia_nhập thành_viên liên_minh thường không hề nhỏ , nhưng vị_trí thành_viên cũng có_thể mang lại rất nhiều lợi_ích , đặc_biệt là trong những thời_kỳ khó_khăn . 
Thứ tư , các thể_chế quốc_tế ở một khía_cạnh nhất_định làm suy_giảm tính chính_danh của nhà_nước quốc_gia 
Các thể_chế quốc_tế có_thể làm suy_yếu các chính_phủ quốcgiabởi sự thu_hẹp các nguồn_lực nằm dưới sự quản_lý của nhà_nước quốc_gia để kiểm_soát tình_hình kinh_tế - xã_hội và làm giảm tính chính danh,quyền lực của nhà_nước đối vớicông chúng . 
Nhìn tổng_thể những nước công_nghiệp phát_triển trong những thậpniênqua có_thể thấy sự xói_mòn lòng tin của công_chúng đối_với nhà_nước . 
Tuy có những nguyên_nhân từ chính các quốc_gia nhưng có một thực_tế là toàn_cầu_hoá , các ảnh_hưởng từ thể_chế quốc_tế , quốc_tế_hoá truyền_thông , hoạt_động tiếp_thị và xuất_khẩu văn_hoá và sự khó kiểm_soát thông_tin ... đang làm suy_yếu các giá_trị truyền_thống của nhà_nước quốc_gia , từ đó làm suy_giảm sự ủng_hộ đối_với các hành_động ở quy_mô quốc_gia . 
 Ảnh_hưởng của các thay_đổi này được biết đến qua việc các nhà lãnh_đạo quốc_gia đang dần đánh mất quyền kiểm_soát những nguồn_lực quyết_định sự phồn_vinh của một quốc_gia , cũng như những phương_tiện giúp đạt được những nhận_thức chung của dân_chúng về sự thịnh_vượng của nước_nhà . 
Trong nhận_thức chung về trật_tự chính_trị tương_lai này , sự giảm_sút vai_trò của các nhà_nước quốc_gia - dân_tộc đang là một xu_hướng thực_tế  ( 6 ) . 
Trong thể_chế quốc_tế , tư_cách thành_viên liên_minh có_thể mang lại nhiều lợi_ích nhưng nó thường đòi_hỏi phải trả cái giá lớn về quyền tự chủhoạch định chính_sách của quốc gia,dẫn tới sự suy_giảm quyền_lực của chính_phủ quốc_gia đối_với đất_nước ( đặc_biệt đối_với quản_lý kinh_tế vĩ_mô ) và tới việc quyết_định cấu_trúc chính_trị của họ . 
Không phải là các chính_phủ không có khả_năng điều_hành mà họ phải quản_lý nền chính_trị quốc_gia trước những áp_lực ngày_càng tăng những áp_lực theo cách phải thích_ứng với của lực_lượng kinh_tế xuyên quốc_gia . 
Thứ năm , các thể_chế quốc_tế làm giảm chi_phí giải_quyết các vấn_đề về hợp_tác giữa các nước 
Theo cách nhìn của lý_thuyết thể_chế mới , một trong những lý_do chính cho sự tồn_tại của các thể_chế quốc_tế là làm giảm chi_phí giao_dịch và cung_cấp thông_tin , tạo điều_kiện thuận_lợi cho hợp_tác đa_phương ( 7 ) . 
Các thể_chế quốc_tế tạo thuận_lợi cho việc hình_thành và thực_hiện các hiệp_ước . 
Các thể_chế quốc_tế còn đóng vai_trò là chủ_thể giám_sát sự tuân_thủ hiệp_ước của các quốc_gia thành_viên và áp_đặt sự tuân_thủ thông_qua các chiến_lược thương_lượng . 
Đây là những hoạt_động khá nổi_bật của các thể_chế như IMF , WB và WTO trong thời_gian qua , đặc_biệt với vai_trò là người cung_cấp thông_tin có tính chuyên_môn , tư_vấn . 
Các thể_chế quốc_tế làm cho sự nhượng_bộ lẫn nhau giữa các quốc_gia dễ_dàng hơn . 
Sự thương_lượng giữa các quốc_gia sẽ thuận_lợi hơn vì các thể_chế quốc_tế có_thể được coi là một phần của sự sắp_xếp . 
Liên_minh châu Âu ngày_càng tăng cườngtrật tự có tính chuẩn_tắc sự đồng_thuận giữa các quốc_gia và thiết_lập những cấu_trúc chính_trị quốc_tế . 
Sự phát_triển các tổ_chức quốc_tế tạo ra mộtthể chếcó khả_năng quyết_định và tác_động tới hoạt độngquản trị của các quốc_gia thành_viên . 
Trong xu_hướng này , không một nhà_nước thành_viên nào nằm ngoài sự hợp_tác . 
Vấn_đề đặt ra cho các thể_chế quốc_tế hiện_nay là , các thể_chế quốc_tế tác_động đến chính_sách quốc_gia như thế_nào ? 
Liệu các thể_chế liên_quốc_gia có_thể giải_quyết những vấn_đề giữa các nước với nhau ? 
Trên thực_tế , ngay_cả các thể_chế quốc_tế yếu cũng có_thể ảnh_hưởng đến các nước . 
Để tạo thuận_lợi cho sự tuân_thủ các cam_kết quốc_tế của nhà_nước , các thể_chế quốc_tế tìm cách tạo nên khả_năng các nhóm ủng_hộ sự tuân_thủ trong nước . 
Xuất_phát từ cơ_chế bầu_cử , các thể_chế quốc_tế sẽ làm thay_đổi môi_trường trong nước ít_nhất theo hai cách : ( 1 ) tăng_cường các ảnh_hưởng chính_trị ; ( 2 ) làm tăng vị_thế quốc_tế của nhóm cử_tri ủng_hộ sự tuân_thủ . 
Những kênh tác_động gián_tiếp này quan_trọng đối_với tất_cả các thể_chế quốc_tế , chúng tạo ra tính khả_thi và con đường quan_trọng cho các thể_chế yếu tác_động tới chính_phủ các nước . 
Nó có tính khả_thi khi các nhóm trong nước có lợi_ích lớn trong việc tuân_thủ hiệp_ước của liên_minh và sẽ là nạn_nhân của sự không tuân_thủ của chính_phủ nước họ . 
Ngoài các khía_cạnh đã được phân_tích ở trên , còn các vấn_đề đối_với các thể_chế quốc_tế nữa là : ( 1 ) có_thể các thể_chế này có tác_động rất nhỏ hoặc không có ảnh_hưởng , đặc_biệt là đối_với các nước đang phát_triển hoặc các nước nghèo ; ( 2 ) các thể_chế thường do các nước phát_triển giàu_mạnh nắm_giữ , được hình_thành bởi và vì lợi_ích của các nước lớn , giàu_có ; ( 3 ) các thể_chế quốc_tế bị chi_phối bởi các nhà kinh_doanh và đầu_tư tư_nhân ; ( 4 ) những vấn_đề động_lực của các thể_chế và sự giám_sát của các nước thành đối_với hoạt_động của thể_chế quốc_tế . 
�c_tế . 
