Công_tác phát_triển đảng_viên là người có đạo ở các tỉnh đồng_bằng sông Hồng 
Đồng_bằng sông Hồng gồm 11 tỉnh và thành_phố ( 1 ) , dân_cư đông_đúc với hơn 20 triệu dân , chỉ chiếm 4,5 % diện_tích nhưng dân_số chiếm 1/4 dân_số cả nước . 
Đây là vựa_lúa lớn thứ hai Việt_Nam và là vùng có tốc_độ phát_triển công_nghiệp_hoá rất nhanh ; luôn đóng vai_trò quan_trọng vào sự_nghiệp phát_triển kinh_tế - xã_hội chung của nước . 
Đồng_bằng sông Hồng là vùng có đông đồng_bào các tôn_giáo sinh_sống . 
Các tôn_giáo chính là Phật_giáo , Công_giáo , Tin_lành , ngoài_ra còn nhiều tôn_giáo khác nhưng số_lượng tín_đồ ít . 
Trong vùng có nơi tôn_giáo được du_nhập từ rất sớm , như : Phật_giáo du_nhập cách đây hàng nghìn năm , hình_thành nên nhiều hệ , phái và nhất_là hệ_thống Phật_giáo dân_gian lan_toả hầu_hết khắp mọi làng quê ; Công_giáo du_nhập cách đây hàng trăm năm và hình_thành nên nhiều trung_tâm như Bùi_Chu , Phát_Diệm , Hà_Nội ... 
Các tỉnh có tỷ_lệ tín_đồ các tôn_giáo cao là Bắc_Ninh 30,3 % , Ninh_Bình : 25 % , Nam_Định : 24 % , Hà_Nam : 25 % , Hưng_Yên : 19 % , ... 
Tỉnh Nam_Định có một_số huyện số giáo_dân Công_giáo chiếm tỷ_lệ khá cao , như huyện Nghĩa_Hưng : 48,9 % ; huyện Hải_Hậu : 41,3 % ; Xuân_Trường : 30,2 % ; Giao_Thuỷ : 26,9 % ; có 11 xã có tỷ_lệ giáo_dân trên 90 % ; có xã gần như tôn_giáo toàn_tòng , như xã Trực_Hùng thuộc huyện Trực_Ninh có 99,6 % ; xã Nghĩa_Sơn thuộc huyện Nghĩa_Hưng có 99,8 % số dân theo đạo , vv . . ( 2 ) . 
Trong thời_gian qua , các cấp_uỷ và chính_quyền các địa_phương trong vùng đã triển_khai thực_hiện đồng_bộ các chính_sách phát_triển kinh_tế - xã_hội , xây_dựng hệ_thống chính_trị , đảm_bảo an_ninh , quốc_phòng . 
Công_tác tôn_giáo được quan_tâm và có nhiều chuyển_biến tích_cực . 
Nhận_thức của đội_ngũ cán_bộ , đảng_viên về vị_trí , vai_trò và nội_dung cốt_lõi của công_tác tôn_giáo được nâng lên . 
Các thành_viên trong hệ_thống chính_trị , theo chức_năng của mình đều đã chú_trọng thực_hiện công_tác tôn_giáo . 
Hoạt_động tín_ngưỡng , tôn_giáo cơ_bản bảo_đảm theo quy_định của pháp_luật . 
Tuyệt_đại_đa_số đồng_bào có đạo đã thực_hiện tốt chính_sách đại_đoàn_kết dân_tộc , chính_sách tôn_giáo , tạo được sự đồng_thuận , tăng_cường đoàn_kết trong các tôn_giáo , góp_phần thúc_đẩy phát_triển kinh_tế - xã_hội ở địa_phương . 
Tuy_nhiên , tình_hình tôn_giáo ở một_số địa_phương cũng có những diễn_biến khá phức_tạp . 
Một_số hoạt_động tôn_giáo và việc xây_dựng , sửa_chữa , mở_rộng cơ_sở thờ_tự chưa tuân_thủ đúng pháp_luật . 
Ở một_số nơi , hoạt_động tôn_giáo mang tính phô_trương , quyên_góp nhiều tiền_của , của đồng_bào có đạo ; hoạt_động mê_tín có chiều_hướng gia_tăng , xuất_hiện một_số " đạo lạ " , với những hiện_tượng trái thuần_phong_mỹ_tục của dân_tộc . 
Bên cạnh đó , một_số phần_tử lợi_dụng tôn_giáo để lôi_kéo , kích_động đồng_bào có đạo chống Đảng , Nhà_nước , phá_hoại khối đại_đoàn_kết toàn dân_tộc . 
Trước tình_hình đó , cùng với việc thực_hiện tốt công_tác tôn_giáo , việc nâng_cao vai_trò , năng_lực lãnh_đạo và sức chiến_đấu của các tổ_chức đảng trong vùng đồng_bào có đạo trở_thành yêu_cầu cấp_thiết . 
Nhận_thức rõ điều đó , trong những năm qua , nhất_là từ khi có Quy_định số 123-QĐ / TW ngày 28-9-2004 của Bộ Chính_trị ( khoá IX ) " Quy_định một_số điểm về kết_nạp đảng_viên đối_với người có đạo và đảng_viên có đạo tham_gia sinh_hoạt tôn_giáo " , cấp_uỷ đảng đã chú_trọng công_tác giáo_dục , bồi_dưỡng , phát_triển đảng_viên là người có đạo và đã đạt được những kết_quả quan_trọng . 
Thực_hiện Quy_định số 123 và Hướng_dẫn số 40-HD / BTCTW ngày 8-4-2005 của Ban Tổ_chức Trung_ương , các tỉnh_uỷ , thành_uỷ đã xây_dựng kế_hoạch và tổ_chức quán_triệt , triển_khai thực_hiện , đồng_thời chỉ_đạo các ban tham_mưu cụ_thể_hoá quy_định cho phù_hợp với tình_hình , đặc_điểm địa_phương . 
Các cấp_uỷ , các đoàn_thể nhân_dân phối_hợp chặt_chẽ với các ngành làm tốt công_tác tuyên_truyền , vận_động quần_chúng có đạo thực_hiện tốt chủ_trương của Đảng , chính_sách , pháp_luật của Nhà_nước ; đẩy_mạnh các phong_trào thi_đua , thông_qua đó phát_hiện , lựa_chọn , bồi_dưỡng để tạo nguồn phát_triển đảng_viên . 
Qua khảo_sát đối_với 1.338 cán_bộ , đảng_viên cho_thấy , có 95 % người được hỏi cho rằng , các cấp_uỷ đảng đã làm tốt và khá tốt công_tác bồi_dưỡng nhận_thức về đảng cho quần_chúng ưu_tú có đạo trước khi kết_nạp ; 94,1 % người được hỏi cho rằng đã thực_hiện tốt và khá tốt việc hướng_dẫn cho người có đạo các thủ_tục kết_nạp đảng ; 90 % người được hỏi cho rằng đã thực_hiện tốt và khá tốt việc lấy ý_kiến nhận_xét của đoàn_thể nơi làm_việc và chi_uỷ nơi cư_trú đối_với người có đạo vào Đảng . 
Theo số_liệu khảo_sát , có 94,5 % cán_bộ , đảng_viên được hỏi cho rằng đã thực_hiện tốt và khá tốt việc phân_công đảng_viên giúp_đỡ quần_chúng có đạo vào Đảng ; 92,2 % cho rằng việc xem_xét , quyết_nghị của các chi_bộ trong kết_nạp đảng_viên là người có đạo đã tiến_hành tốt và khá tốt ; 89 % cho rằng , lễ kết_nạp đảng_viên là người có đạo được tiến_hành trang_trọng , tuân_thủ các quy_định về quy_trình , thủ_tục . 
Nhìn_nhận của quần_chúng đối_với công_tác phát_triển đảng_viên tuy có phần ít " lạc_quan " hơn so với đánh_giá của cán_bộ , đảng_viên nhưng nhìn_chung cũng khá tích_cực : có 77,3 % người được hỏi cho rằng cấp_uỷ , chính_quyền , đoàn_thể đã thường_xuyên coi_trọng công_tác phát_triển đảng_viên là người có đạo ; 52,9 % cho rằng cấp_uỷ cơ_sở làm tốt công_tác giáo_dục , quản_lý đảng_viên và 66,5 % cho rằng cấp_uỷ cơ_sở đã làm tốt công_tác tuyên_truyền , bồi_dưỡng người có đạo ưu_tú vào Đảng . 
Qua thực_tế các phong_trào ở địa_phương , các cấp_uỷ đã phát_hiện nhiều tín_đồ , chức_sắc trong vùng tập_trung đông đồng_bào tôn_giáo tiến_bộ , để lựa_chọn tạo nguồn , bồi_dưỡng phát_triển đảng_viên . 
Đồng_thời , tạo điều_kiện thuận_lợi để đảng_viên có đạo tham_gia sinh_hoạt tôn_giáo , tạo sự phấn_khởi , tin_tưởng , đồng_thuận của đồng_bào có đạo , góp_phần thực_hiện nhiệm_vụ phát_triển của địa_phương . 
Với sự quan_tâm của các cấp_uỷ đảng và cả hệ_thống chính_trị , trong những năm qua số_lượng đảng_viên là người có đạo không ngừng được tăng lên . 
Trong 8 năm , từ khi thực_hiện Quy_định 123 đến 31-3-2012 , các đảng_bộ vùng đồng_bằng sông Hồng kết_nạp được 2.806 quần_chúng có đạo vào Đảng . 
Trong đó , đảng_viên là tín_đồ là 2.801 người , chiếm 99,82 % ; 2 chức_việc , 3 chức_sắc ( cụ_thể là Công_giáo có 2.718 tín_đồ , trong đó có 2 chức_việc ; đạo_Phật có 85 tín_đồ , trong đó có 3 chức_sắc , nhà tu hành ; đạo_Tin_lành có 2 tín_đồ ; tôn_giáo khác có 1 tín_đồ ) . 
Trong đó , một_số tỉnh có nhiều người có đạo được kết_nạp Đảng như Nam_Định : 1.014 người ; Ninh_Bình : 455 người ; Thành_phố Hà_Nội : 428 người ; Hà_Nam : 287 người ; Thái_Bình : 192 người ; Hải_Dương : 125 người ( 3 ) . 
Về nhận_xét đánh_giá của cán_bộ , đảng_viên về kết_quả công_tác phát_triển đảng_viên là người có đạo ở địa_phương so với 10 năm trước đây , 70 % người được hỏi cho rằng " tốt hơn " , 17 % cho rằng " như cũ " . 
Việc tăng_cường công_tác kết_nạp đảng_viên là người có đạo , đã góp_phần làm thay_đổi cơ_cấu đội_ngũ đảng_viên , xây_dựng và củng_cố tổ_chức đảng , xoá thôn ( xóm ) " trắng " đảng_viên , chi_bộ ; giảm số chi_bộ ghép và số_lượng đảng_viên phải sinh_hoạt ghép . 
Số đảng_viên là người có đạo mới được kết_nạp đều là những công_dân sống " tốt đời , đẹp đạo " , tiêu_biểu trong các phong_trào thi_đua yêu nước , văn_hoá và được quần_chúng tín_nhiệm ; gương_mẫu chấp_hành đường_lối , chính_sách của Đảng , pháp_luật của Nhà_nước , phát_triển kinh_tế , xoá đói giảm nghèo , nhiệt_tình hưởng_ứng phong_trào thi_đua yêu nước , tích_cực tham_gia hoạt_động xã_hội . 
Khi tham_gia sinh_hoạt tôn_giáo , đại_đa_số đảng_viên có đạo giữ_gìn tư_cách đảng_viên ; thể_hiện vai_trò nòng_cốt trong tập_hợp quần_chúng tín_đồ , thực_hiện đúng quyền tự_do tín_ngưỡng tôn_giáo theo quy_định của pháp_luật . 
Tuy_nhiên , công_tác phát_triển đảng_viên là người có đạo ở các tỉnh , thành_phố vùng đồng_bằng sông Hồng thời_gian qua cũng còn những hạn_chế nhất_định : 
( i ) Một_số cấp_uỷ chưa chưa thật_sự quyết_liệt trong lãnh_đạo , chỉ_đạo ; chưa quán_triệt sâu_sắc Quy_định 123 và Hướng_dẫn 40 nên còn lúng_túng trong tổ_chức thực_hiện . 
Theo kết_quả điều_tra , có tới 858/1.338 cán_bộ , đảng_viên ( 64,1 % ) các địa_phương có đông đồng_bào tôn_giáo khẳng_định chi_bộ không tổ_chức sinh_hoạt chuyên_đề về phát_triển đảng_viên là người có đạo . 
Mặt_khác , một bộ_phận cán_bộ , đảng_viên nhận_thức chưa đầy_đủ về việc phát_triển đảng_viên là người có đạo , có 56,2 % cán_bộ , đảng_viên cho rằng chức_sắc , nhà tu hành có_thể kết_nạp vào Đảng , còn 43,5 % cho rằng không_thể trở_thành đảng_viên . 
( ii ) Công_tác tạo nguồn kết_nạp chưa được quan_tâm thường_xuyên . 
Một_số cấp_uỷ cơ_sở chưa có kế_hoạch cụ_thể về phát_triển đảng_viên theo từng quý , năm mà chủ_yếu là chỉ_tiêu trong nhiệm_kỳ . 
Sự phối_hợp giữa các thành_viên trong hệ_thống chính_trị ở cơ_sở trong việc giáo_dục , rèn_luyện quần_chúng ưu_tú là người có đạo để trở_thành đảng_viên thiếu chặt_chẽ , chưa thường_xuyên . 
( iii ) Kết_quả thực_hiện công_tác kết_nạp người có đạo vào Đảng còn khiêm_tốn ; chưa đồng_đều ; tỷ_lệ chức_sắc , chức_việc tôn_giáo được kết_nạp vào đảng còn thấp . 
Nhìn_chung , tỷ_lệ người có đạo được kết_nạp vào Đảng so với số_lượng người theo đạo và so với tổng_số đảng_viên chưa tương_xứng . 
Ở một_số địa_phương , tỷ_lệ kết_nạp đảng_viên là người có đạo thấp như Vĩnh_Phúc 0,48 % , Bắc_Ninh 0,3 % ( tỷ_lệ chung toàn Đảng là 1,72 % ) ; vẫn còn một_số thôn , xóm " trắng " đảng_viên , hoặc số đảng_viên ít không đủ thành_lập chi_bộ . 
Tỷ_lệ kết_nạp chức_việc , chức_sắc trong các tôn_giáo thấp , chỉ chiếm 0,18 % , nên tầm ảnh_hưởng và sức lan_toả của đảng_viên có đạo đối_với đồng_bào tôn_giáo còn hạn_chế . 
Nguyên_nhân của tình_hình trên , trước_hết là do đội_ngũ cán_bộ , đảng_viên , nhất_là đội_ngũ cấp_uỷ_viên các cấp còn chưa thống_nhất nhận_thức về công_tác phát_triển đảng_viên là người có đạo . 
Kết_quả khảo_sát cho_thấy , có 74,4 % cán_bộ , đảng_viên được hỏi cho rằng kết_nạp đảng_viên là người có đạo sẽ góp_phần nâng_cao năng_lực lãnh_đạo và sức chiến_đấu của Đảng , đáp_ứng yêu_cầu , nhiệm_vụ trong giai_đoạn mới , nhưng cũng còn 25,6 % cho rằng , việc kết_nạp đảng_viên là người có đạo không có tác_dụng . 
Tương_tự , có 29,1 % cán_bộ , đảng_viên được hỏi có suy_nghĩ , kết_nạp đảng_viên là người có đạo không giúp tăng_cường sự lãnh_đạo của Đảng trong vùng đồng_bào có đạo ; 41,7 % cho rằng không giúp tạo nguồn cán_bộ tại_chỗ vùng đồng_bào có đạo ; 27,4 % khẳng_định không góp_phần tăng_cường đoàn_kết dân_tộc . 
Chỉ có 56,2 % cán_bộ , đảng_viên cho rằng chức_sắc , nhà tu hành có_thể vào Đảng , còn 43,5 % cho rằng không_thể trở_thành đảng_viên . 
Kết_quả khảo_sát đó phù_hợp với đánh_giá của người dân khi có tới 30,9 % số người được hỏi cho rằng , nhận_thức về tôn_giáo của một bộ_phận cán_bộ , đảng_viên và đồng_bào có đạo về chính_sách tôn_giáo của Đảng còn hạn_chế là một trọng những nguyên_nhân khiến việc vào Đảng của người có đạo gặp khó_khăn . 
Bên cạnh đó , rào_cản về giáo luật , lễ_nghi của tôn_giáo , thái_độ thiếu hợp_tác , phối_hợp của một_số chức_sắc , chức_việc tôn_giáo cũng như sự mặc_cảm của bản_thân và gia_đình quần_chúng có đạo cũng gây khó_khăn cho công_tác phát_triển đảng_viên là người có đạo . 
Khi được hỏi về những khó_khăn khi vào Đảng của người có đạo , có 24,9 % số người dân được hỏi cho rằng , do thái_độ không ủng_hộ của chức_sắc , nhà tu hành ; 23,5 % cho rằng do giáo luật và lễ_nghi tôn_giáo không cho_phép ; 31,6 % cho rằng do sức_ép , cản_trở từ gia_đình . 
Ngoài những nguyên_nhân trên còn có nguyên_nhân khách_quan : do thiếu việc làm , nhiều người dân có đạo , trong đó hầu_hết là thanh_niên phải rời quê_hương đi làm_ăn xa . 
Có tới 52 % số người dân được hỏi cho rằng , vì phần_lớn phải đi làm_ăn xa nên việc tạo nguồn để phát_triển đảng_viên gặp khó_khăn . 
Bên cạnh đó là nguyên_nhân từ những vướng_mắc về thủ_tục , tiêu_chuẩn ... chưa được kịp_thời tháo_gỡ . 
Để tiếp_tục nâng_cao hiệu_quả của công_tác phát_triển đảng_viên là người có đạo ở vùng đồng_bằng sông Hồng , cần tập_trung thực_hiện một_số giải_pháp sau : 
Một là , các cấp_uỷ đảng cần nhận_thức đầy_đủ , thống_nhất quan_điểm , mục_đích , yêu_cầu , nội_dung , biện_pháp của công_tác phát_triển đảng_viên là người có đạo , từ đó quan_tâm lãnh_đạo , chỉ_đạo thực_hiện tốt Quy_định 123 của Bộ Chính_trị . 
Đây là giải_pháp được đông_đảo cán_bộ , đảng_viên đánh_giá là quan_trọng nhất ( 71,1 % số người được hỏi ) . 
Trên cơ_sở đó , cần cụ_thể_hoá chủ_trương của Đảng thành các chỉ_thị , nghị_quyết và các văn_bản hướng_dẫn phù_hợp với tình_hình , đặc_điểm của từng địa_phương , từng tôn_giáo . 
Phải xác_định rõ kết_nạp đảng_viên là người có đạo phải gắn liền với xây_dựng lực_lượng cốt_cán trong vùng đồng_bào có đạo ; củng_cố , nâng_cao năng_lực lãnh_đạo và sức chiến_đấu của các tổ_chức đảng . 
Bởi vậy , cần quán_triệt phương_châm coi_trọng chất_lượng , không chạy theo số_lượng , bảo_đảm chặt_chẽ về tiêu_chuẩn , quy_trình , thủ_tục , thực_hiện tốt công_tác bảo_vệ chính_trị nội_bộ theo quy_định . 
Điều đó phù_hợp với tâm_tư , nguyện_vọng của đồng_bào có đạo . 
Kết_quả khảo_sát cho_thấy , đại_đa_số quần_chúng đều cho rằng , người có đạo được kết_nạp đảng cần bảo_đảm những tiêu_chuẩn ( xếp theo thứ_tự ưu_tiên ) : Luôn chấp_hành tốt mọi chủ_trương , đường_lối của Đảng , chính_sách , pháp_luật của Nhà_nước ; có đạo_đức trong_sáng , lối sống lành_mạnh ; có khả_năng đoàn_kết , thuyết_phục và vận_động nhân_dân ; sẵn_sàng phục_vụ Tổ_quốc ; có uy_tín trong cộng_đồng tôn_giáo và dám đấu_tranh với các biểu_hiện tiêu_cực , sai_trái . 
Hai là , thực_hiện tốt chủ_trương , chính_sách tôn_giáo của Đảng , Nhà_nước về tôn_giáo và công_tác tôn_giáo . 
Thông_qua đó , củng_cố lòng tin của đồng_bào có đạo với Đảng , Nhà_nước cũng như tạo môi_trường , điều_kiện thuận_lợi cho công_tác phát_triển đảng_viên trong đồng_bào có đạo . 
Bởi vậy , để thực_hiện tốt công_tác phát_triển đảng_viên là người có đạo , các cấp_uỷ đảng , chính_quyền địa_phương , nhất_là cơ_sở cần tiếp_tục tăng_cường quán_triệt và tổ_chức thực_hiện tốt chủ_trương , chính_sách của Đảng và Nhà_nước về tôn_giáo ; xem_xét công_nhận và quản_lý hoạt_động của các tổ_chức tôn_giáo trên địa_bàn bảo_đảm đúng quy_định của pháp_luật . 
Các đoàn_thể nhân_dân cần tuyên_truyền , giáo_dục tín_đồ trong các tôn_giáo hiểu rõ và thực_hiện tốt đường_lối , chính_sách của Đảng và Nhà_nước , kịp_thời nắm_bắt tình_hình và tâm_tư , nguyện_vọng của các tín_đồ trong tôn_giáo về nhu_cầu tôn_giáo để có chủ_trương phù_hợp với tình_hình thực_tế công_tác tôn_giáo ở địa_phương . 
Đồng_thời , nắm chắc thông_tin những tôn_giáo và hình_thức sinh_hoạt tôn_giáo được Nhà_nước công_nhận để tiện cho việc theo_dõi , bồi_dưỡng , giáo_dục quần_chúng là những tín_đồ tôn_giáo vào Đảng . 
Ba là , coi_trọng và thực_hiện tốt công_tác tạo nguồn kết_nạp Đảng . 
Các cấp_uỷ đảng , nhất_là cấp cơ_sở cần thúc_đẩy các phong_trào thi_đua yêu nước ; tiếp_tục đẩy_mạnh hai phong_trào lớn " Xây_dựng chùa tinh tiến " và " Xây_dựng xứ họ_đạo tiên_tiến , gia_đình Công_giáo gương_mẫu " gắn với phong_trào xây_dựng nông_thôn mới với những nội_dung cụ_thể , thiết_thực để thu_hút đông_đảo đồng_bào có đạo , nhất_là thanh_niên tham_gia . 
Từ đó , phát_hiện các nhân_tố tích_cực , tiêu_biểu để bồi_dưỡng kết_nạp đảng . 
Các cấp_uỷ đảng cơ_sở cần giao nhiệm_vụ cho đảng_viên giúp_đỡ quần_chúng , tạo điều_kiện để quần_chúng hăng_hái tham_gia các phong_trào và phấn_đấu là quần_chúng ưu_tú . 
Đặc_biệt , các chi_bộ cần chủ_động trao_đổi và giao nhiệm_vụ cho các đảng_viên là người có đạo tuyên_truyền , vận_động , giúp_đỡ quần_chúng là con_em , họ_hàng , người_thân của mình phấn_đấu vào Đảng . 
Mặt_trận Tổ_quốc và các đoàn_thể , nhất_là Đoàn_Thanh_niên cần xây_dựng chương_trình hành_động về kết_nạp đảng_viên là người có đạo ; tạo điều_kiện thuận_lợi để đoàn_viên , hội_viên , đặc_biệt là đối_với các đoàn_viên đã hoàn_thành nghĩa_vụ_quân_sự về sinh_hoạt tại địa_phương , thông_qua đó giáo_dục , bồi_dưỡng những người ưu_tú giới_thiệu cho tổ_chức Đảng . 
Đồng_thời , quan_tâm tuyên_truyền , vận_động , bồi_dưỡng những chức_sắc , chức_việc trong các tôn_giáo để tạo nguồn , lựa_chọn những người ưu_tú , đủ tiêu_chuẩn giới_thiệu cho Đảng xem_xét , bồi_dưỡng , kết_nạp . 
Bốn là , nâng_cao chất_lượng xây_dựng tổ_chức cơ_sở đảng và hệ_thống chính_trị cơ_sở trong vùng có đông đồng_bào tôn_giáo . 
Chất_lượng tổ_chức cơ_sở đảng và đảng_viên tốt sẽ tạo điều_kiện cho công_tác vận_động , thuyết_phục , nêu gương với quần_chúng nhân_dân nói_chung và với đồng_bào có đạo nói_riêng . 
Đặc_biệt , cần thường_xuyên bồi_dưỡng đội_ngũ cấp_uỷ_viên , bí_thư cấp_uỷ về kỹ_năng , nghiệp_vụ xây_dựng Đảng và kiến_thức , nghiệp_vụ công_tác tôn_giáo . 
Cần tập_trung củng_cố , tăng_cường sự phối_hợp , đổi_mới phương_thức hoạt_động để nâng_cao chất_lượng và hiệu_quả công_tác của hệ_thống chính_trị ở cơ_sở vùng có đông đồng_bào theo đạo . 
Thực_hiện tốt công_tác quản_lý_nhà_nước đối_với các hoạt_động tôn_giáo , tạo điều_kiện để các hoạt_động tôn_giáo diễn_ra bình_thường theo pháp_luật , đồng_thời , kịp_thời phát_hiện , ngăn_chặn những hành_vi vi_phạm pháp_luật hoặc lợi_dụng tôn_giáo vì mục_đích xấu . 
Mặt_trận Tổ_quốc và các tổ_chức chính_trị xã_hội cần đổi_mới nội_dung , phương_thức hoạt_động để thu_hút , tập_hợp được đông_đảo đoàn_viên , hội_viên là người có đạo ; thường_xuyên nắm_bắt tâm_tư , nguyện_vọng chính_đáng của đồng_bào có đạo , kịp_thời phản_ánh với cấp_uỷ , chính_quyền để chỉ_đạo giải_quyết những khó_khăn , vướng_mắc , bức_xúc ở cơ_sở . 
Trên cơ_sở các phong_trào thi_đua chung của cả nước , các đoàn_thể vận_dụng cho phù_hợp với đặc_điểm , tình_hình từng địa_phương , từng tôn_giáo để cổ_vũ , động_viên đoàn_viên tích_cực tham_gia , qua đó có_điều_kiện để lựa_chọn những quần_chúng là tín_đồ , chức_sắc ưu_tú để giới_thiệu cho các tổ_chức đảng xem_xét , kết_nạp . 
Năm là , thường_xuyên kiểm_tra , đốn đốc việc thực_hiện Quy_định 123 , đồng_thời xem_xét sửa_đổi , bổ_sung một_số nội_dung trong các quy_định , hướng_dẫn của Trung_ương cho phù_hợp . 
Cùng với việc xây_dựng kế_hoạch phát_triển đảng_viên là người có đạo , các cấp_uỷ cần thường_xuyên theo_dõi , kiểm_tra , đôn_đốc các cấp_uỷ cấp_dưới trong việc thực_hiện các quy_định , hướng_dẫn của Trung_ương . 
Trong sơ_kết , tổng_kết công_tác xây_dựng Đảng , nhất_thiết phải có đánh_giá về công_tác phát_triển đảng_viên là người có đạo . 
Đồng_thời , định_kỳ tiến_hành sơ_kết công_tác này để rút kinh_nghiệm chỉ_đạo và đề ra các giải_pháp cho phù_hợp với tình_hình thực_tế . 
Để tháo_gỡ những khó_khăn , vướng_mắc về kết_nạp đảng_viên là người có đạo , cần tổng_kết , đánh_giá và trên cơ_sở đó sửa_đổi , bổ_sung một_số nội_dung trong Quy_định 123 và Hướng_dẫn 40 cho phù_hợp với thực_tiễn . 
Chẳng_hạn , nên sửa_đổi quy_định để đảng_viên có_thể tham_gia làm chức_việc , hội đoàn tôn_giáo nếu được tín_đồ tín_nhiệm , được cấp_uỷ cơ_sở đề_nghị và được ban thường_vụ huyện_uỷ và tương_đương đồng_ý ; chỉnh_sửa theo hướng hướng_dẫn chi_tiết , rõ_ràng hơn về quy_trình xem_xét , kết_nạp đảng_viên là người có đạo ; bổ_sung nội_dung cụ_thể về cơ_chế quản_lý , phân_công nhiệm_vụ đối_với đảng_viên tham_gia sinh_hoạt tôn_giáo , tạo điều_kiện để đảng_viên là người có đạo phát_huy vai_trò cầu_nối gắn_bó giữa quần_chúng có đạo với Đảng , góp_phần xây_dựng khối đại_đoàn_kết dân_tộc vì mục_tiêu xây_dựng quê_hương , đất_nước ngày_càng giàu_mạnh , văn_minh . 
