Thực_trạng xây_dựng nông_thôn mới ở đồng_bằng sông Cửu_Long 
Xây_dựng nông_thôn mới ở đồng_bằng sông Cửu_Long thời_gian qua đạt được nhiều kết_quả nhưng vẫn còn tồn_tại một_số hạn_chế do các  nút thắt  gây ra . 
Để tháo_gỡ những  nút thắt  trong xây_dựng nông_thôn mới ở khu_vực , nhất_là về cơ_sở_hạ_tầng , phát_triển sản_xuất , tạo chuyển_biến đột_phá thúc_đẩy phát_triển chung ; sớm hình_thành hệ_thống các xã đạt chuẩn nông_thôn mới ở các tỉnh , thành_phố , cần thực_hiện một_số giải_pháp trọng_yếu . 
1 . 
Những kết_quả đạt được 
Thứ nhất , nhiều xã đã về đích , bình_quân đạt các tiêu_chí ở mức cao hơn bình_quân cả nước , xoá được  xã trắng tiêu_chí  trong xây_dựng nông_thôn mới . 
Đến cuối năm 2013 , đã có 18 xã đạt chuẩn nông_thôn mới . 
Bình_quân các xã đã đạt 9,23 tiêu_chí , tăng 3,19 tiêu_chí so với năm 2011 ( bình_quân cả nước đạt 8,36 tiêu_chí ) . 
Trong đó : 
Có 18 xã đạt 19 tiêu_chí , chiếm 1,4 % 
Số xã đạt 15 - 18 tiêu_chí là 4,7 % 
Số xã đạt 10 - 14 tiêu_chí là 36 % 
Số xã đạt 5 - 9 tiêu_chí là 53 % 
Số xã đạt dưới 5 tiêu_chí còn 132 xã bằng 10 % . 
Thứ hai , nhận_thức của phần_lớn cán_bộ và người dân về chương_trình đã có chuyển_biến rõ_nét , đời_sống văn_hoá tinh_thần của người dân ở nông_thôn không ngừng được nâng_cao . 
Xây_dựng nông_thôn mới đã trở_thành phong_trào rộng khắp trong nhân_dân , kể_cả đồng_bào các dân_tộc ở vùng_sâu , vùng_xa . 
Đội_ngũ cán_bộ , nhất_là cán_bộ cơ_sở đã có bước trưởng_thành lớn trong nhận_thức , khả_năng vận_động quần_chúng và trình_độ tổ_chức , quản_lý xây_dựng nông_thôn mới . 
Nhiều nơi , công_tác tuyên_truyền về xây_dựng nông_thôn mới được tổ_chức sáng_tạo với nhiều hình_thức phong_phú , như thông_qua các phong_trào văn_nghệ quần_chúng ( đờn ca tài_tử , cải_lương ) , tuyên_truyền lưu_động , gần_gũi với bà_con nông_dân , người dân đã nhận_thức rõ hơn về nông_thôn mới , góp_phần huy_động nguồn_lực từ người dân đóng_góp cho xây_dựng nông_thôn mới . 
Phong_trào chung sức xây_dựng nông_thôn mới và toàn dân đoàn_kết xây_dựng đời_sống văn_hoá đã được đông_đảo cán_bộ , đảng_viên và quần_chúng nhân_dân hưởng_ứng . 
Đến cuối năm 2013 , khu_vực đồng_bằng sông Cửu_Long có khoảng 95 % số hộ gia_đình và 97 % số xã , ấp đạt tiêu_chí văn_hoá . 
Thứ ba , phát_triển sản_xuất với nhiều mô_hình có hiệu_quả , nâng_cao thu_nhập , thực_hiện giảm nghèo và đảm_bảo an_sinh_xã_hội . 
Các thành_phần kinh_tế tham_gia đầu_tư vào sản_xuất , từng bước hình_thành các vùng sản_xuất tập_trung chuyên_canh , phát_huy lợi_thế sản_phẩm chủ_lực của vùng như lúa , trái_cây , thuỷ_sản ... 
Nhiều mô_hình liên_kết sản_xuất có hiệu_quả được hình_thành và phát_triển như : mô_hình  cánh_đồng lớn  trong sản_xuất lúa nâng_cao lợi_nhuận cho nông_dân từ 2,2 - 2,7 triệu đồng / ha so với ngoài mô_hình ; nhiều mô_hình sản_xuất kinh_doanh tổng_hợp ; mô_hình trang_trại , hợp_tác_xã ... được hình_thành và hoạt_động có hiệu_quả . 
Tại khu_vực đồng_bằng sông Cửu_Long có khoảng 2 nghìn trang_trại , trên 1 nghìn hợp_tác_xã ( khoảng 11 nghìn xã_viên ) , gần 5 nghìn tổ_hợp tác ( khoảng 600 nghìn tổ_viên ) , trong đó có gần 100 tổ_hợp tác tham_gia sản_xuất theo tiêu_chuẩn Global_GAP . 
Nổi_bật là các tỉnh An_Giang , Đồng_Tháp , Kiên_Giang , Tiền_Giang ... đã bước_đầu tạo ra hướng đi mới cho nông_nghiệp trên cơ_sở chú_trọng triển_khai các mô_hình liên_kết sản_xuất theo chuỗi giá_trị đối_với các sản_phẩm chủ_lực ( lúa gạo , rau_màu , cây_ăn_trái , thuỷ_sản ) , trọng_tâm là sản_xuất gắn với chế_biến , tiêu_thụ , như : chuỗi giá_trị lúa , gạo , chuỗi giá_trị rau_màu ( cà_tím , đậu_bắp giống Nhật , mô_hình trồng bắp - nuôi bò ) , chuỗi giá_trị thuỷ_sản ( cá_tra , tôm_càng xanh ) , cây_ăn_trái theo tiêu_chuẩn VietGAP , GlobalGAP ... cho thu_nhập từ 80-120 triệu đồng / ha . 
Góp_phần đưa thu_nhập bình_quân đầu người của khu_vực lên trên 34,6 triệu đồng , tăng hơn 2,3 triệu đồng so với năm 2012 . 
Hộ nghèo còn 7,24 % , giảm 2 % bình_quân chung cả nước là 9,6 % , hộ cận nghèo là 6,5 % . 
Thứ tư , hạ_tầng nông_thôn đã có bước phát_triển rõ_rệt , nhất_là về giao_thông , điện , thay_thế cầu tạm ... tạo điều_kiện thuận_lợi cho phát_triển sản_xuất và lưu_thông_hàng_hoá . 
Các địa_phương đã ưu_tiên tập_trung nguồn_lực cho phát_triển kết_cấu_hạ_tầng , nhất_là giao_thông , thuỷ_lợi ; cùng với sự đồng_tình , hưởng_ứng của cán_bộ và người dân , trở_thành phong_trào sâu_rộng trong toàn vùng , đã làm thay_đổi vượt_bậc về hạ_tầng , góp_phần tạo động_lực trong phát_triển sản_xuất , cải_thiện điều_kiện sống của cư_dân nông_thôn . 
Toàn vùng cơ_bản hoàn_thành mục_tiêu xây_dựng cụm , tuyến dân_cư và nhà_ở vùng ngập lũ . 
Nhiều địa_phương có những cách làm sáng_tạo trong huy_động nguồn_lực ngoài ngân_sách như tỉnh Cà_Mau đã huy_động các nguồn_lực xã_hội để hoàn_thành đề_án 1.588 cầu giao_thông nông_thôn ; tỉnh Bến_Tre đã huy_động nguồn_lực từ trong dân và các nhà tài_trợ để xây_dựng hàng nghìn cây cầu bê_tông nông_thôn mà không sử_dụng vốn ngân_sách ; tỉnh Hậu_Giang đã huy_động được hơn 1.200 tỷ đồng , trong đó dân đóng_góp chiếm 43,4 % để nâng số xã có đường ô_tô về đến trung_tâm đạt 96 % , v.v ... qua đó , góp_phần hạn_chế sự phụ_thuộc vào ngân_sách đầu_tư cho hạ_tầng . 
Thứ năm , huy_động được nguồn_lực lớn thực_hiện chương_trình . 
Tổng_kinh_phí thực_hiện Chương_trình Mục_tiêu quốc_gia xây_dựng nông_thôn mới trong 03 năm đạt 124.340 tỷ đồng ; trong đó ngân_sách Trung_ương 1.832 tỷ đồng ( chiếm 1,5 % ) , ngân_sách địa_phương 4.982 tỷ đồng ( chiếm 4 % ) , vốn tín_dụng 58.932 tỷ đồng ( 47,4 % ) , vốn lồng_ghép 31.968 tỷ đồng ( chiếm 25,7 % ) , doanh_nghiệp tài_trợ 5.313 tỷ đồng ( chiếm 4,3 % ) , đóng_góp của dân_cư 21.345 tỷ đồng ( chiếm 17,2 % ) . 
Nhiều địa_phương có cách làm sáng_tạo trong việc huy_động nguồn_lực như huyện Phước_Long , tỉnh Bạc_Liêu phát_động phong_trào  Toàn dân xây_dựng_gia_đình nông_thôn mới  , vận_động nhân_dân đóng_góp ngày_công lao_động , hiến đất ( trên 346.250m2 ) để làm đường . 
Thứ_sáu , công_tác đảm_bảo an_ninh trật_tự ở nông_thôn ngày_càng ổn_định . 
Nhận_thức của các cấp_uỷ đảng , chính_quyền cơ_sở ở các địa_phương về tầm quan_trọng của việc bảo_đảm an_ninh trật_tự là một trong những nhiệm_vụ quan_trọng , có ý_nghĩa quyết_định trong việc củng_cố hệ_thống chính_trị và bảo_đảm cho sự phát_triển của kinh_tế - xã_hội địa_phương được nâng lên rõ_rệt . 
Vai_trò của Mặt_trận Tổ_quốc và các đoàn_thể chính_trị - xã_hội ngày_càng phát_huy mạnh_mẽ , chất_lượng hoạt_động ngày_càng cao . 
Hưởng_ứng phong_trào  Cả nước chung sức xây_dựng nông_thôn mới  , các địa_phương đã có những cách làm , mô_hình mới , sáng_tạo , linh_hoạt thu_hút được người dân tham_gia như : Cổng_chào xanh-sạch-đẹp ; mô_hình  Đèn trước ngõ , mõ trong nhà  ... góp_phần đảm_bảo an_ninh trật_tự ở nông_thôn . 
2 . 
Những  nút thắt  cần được tháo_gỡ 
Quá_trình xây_dựng nông_thôn mới ở đồng_bằng sông Cửu_Long vẫn còn nhiều vấn_đề đặt ra cần phải giải_quyết , nhằm tiến tới thực_hiện thành_công chương_trình này . 
Đồng_bằng sông Cửu_Long có diện_tích tự_nhiên lớn , hệ_thống sông_ngòi , kênh , rạch chằng_chịt , nền đất yếu ; cơ_cấu kinh_tế vẫn chủ_yếu dựa vào sản_xuất nông_nghiệp nhưng hiệu_quả chưa cao ; kết_cấu_hạ_tầng nhất là giao_thông , thuỷ_lợi , điện , nước sạch ... còn thiếu và yếu_kém ; mức_sống của một bộ_phận dân_cư , nhất_là đồng_bào dân_tộc còn thấp , thường_xuyên chịu ảnh_hưởng của lũ_lụt , đang là những tác_động làm chậm_tiến trình thực_hiện xây_dựng nông_thôn mới ở các tỉnh ĐBSCL . 
 Nút thắt  lớn nhất là nguồn vốn . 
Với 1.269 xã thực_hiện chương_trình xây_dựng nông_thôn mới , theo tính_toán , trung_bình mỗi xã phải đầu_tư khoảng 300 tỷ đồng để hoàn_thành 19 tiêu_chí , thì toàn khu_vực cần 380.700 tỷ đồng , gấp 3,06 lần số tiền được huy_động xây_dựng nông_thôn mới trong 3 năm 2011-2013 ( số tiền huy_động trong 3 năm là 124.340 tỉ đồng ) . 
 Nút thắt  thứ hai là nguồn nhân_lực phục_vụ chương_trình còn nhiều hạn_chế . 
Đến cuối năm 2013 đã có gần 70 % số cán_bộ làm công_tác xây_dựng nông_thôn mới được tập_huấn . 
Tuy_nhiên , công_tác tập_huấn còn hạn_chế . 
Qua khảo_sát , nhiều cán_bộ chủ_chốt cấp xã còn chưa nắm được đầy_đủ nội_dung , phương_pháp , cách làm trong xây_dựng nông_thôn mới . 
 Nút thắt  thứ ba là một số tiêu_chí còn chưa phù_hợp với thực_tiễn của khu_vực đồng_bằng sông Cửu_Long . 
Chẳng_hạn , tiêu_chí chợ nông_thôn , các địa_phương cho rằng không nhất_thiết một xã cần phải có một chợ để phục_vụ người dân . 
Thực_tế cho_thấy , đối_với nhiều xã chợ khu_vực đã phục_vụ tốt nhu_cầu của người dân . 
Hoặc tiêu_chí về giảm tỷ_lệ lao_động trong nông_nghiệp xuống 20 % , điều này bất_hợp_lý với các xã thuần nông , có nhu_cầu cao về lao_động trong nông_nghiệp ... 
Bên cạnh đó , tính bền_vững của các tiêu_chí còn chưa ổn_định . 
Thực_tế , có những tiêu_chí năm nay đạt nhưng những năm sau chưa hẵn đạt , chẳng_hạn tiêu_chí về an_ninh trật_tự ... 
 Nút thắt  thứ tư là kết_cấu_hạ_tầng của khu_vực yếu_kém . 
Các tiêu_chí lĩnh_vực này còn rất thấp . 
Chẳng_hạn , số xã đạt tiêu_chí về giao_thông chỉ đạt 10,5 % , tiêu_chí nước sạch là 10,6 % , cơ_sở vật_chất văn_hoá 5,9 % , chỉ bằng 50-60 % so với cả nước . 
Nguyên_nhân chính là do điều_kiện đặc_thù về tự_nhiên của vùng ( hệ_thống sông_ngòi , kênh_rạch chằng_chịt , nền đất yếu ... ) , hàng năm chịu ảnh_hưởng của lũ và thiếu vật_liệu xây_dựng tại_chỗ nên giá_thành đầu_tư cao . 
 Nút thắt  thứ năm là vấn_đề nâng_cao thu_nhập cho nông_dân còn nhiều khó_khăn . 
Đây là khu_vực có tiềm_năng lớn nhất cả nước về nông_nghiệp , nhưng vẫn còn phổ_biến tình_trạng manh_mún , nhỏ lẻ , đầu_ra bấp_bênh , còn cảnh  trúng mùa , rớt giá  . 
3 . 
Một_số giải_pháp 
Để tháo_gỡ những  nút thắt  trong xây_dựng nông_thôn mới ở khu_vực , nhất_là về cơ_sở_hạ_tầng , phát_triển sản_xuất , tạo chuyển_biến đột_phá thúc_đẩy phát_triển chung ; sớm hình_thành hệ_thống các xã đạt chuẩn nông_thôn mới ở các tỉnh , thành_phố ( tối_thiểu mỗi tỉnh có 1 xã đạt 19 tiêu_chí / năm ) , cần thực_hiện một_số giải_pháp chủ_yếu sau đây : 
Thứ nhất , nâng_cao nhận_thức của người dân về chương_trình xây_dựng nông_thôn mới . 
Phải làm cho người dân hiểu và tin rằng xây_dựng nông_thôn mới là mang lại lợi_ích cho chính họ . 
Từ đó phát_huy được sức_mạnh cộng_đồng , huy_động mọi nguồn_lực cho xây_dựng nông_thôn mới . 
Thực_hiện tốt công_tác tuyên_truyền dưới nhiều hình_thức đa_dạng , phong_phú kết_hợp với sự vào cuộc của hệ_thống chính_trị cơ_sở , đặc_biệt là tính gương_mẫu đi đầu của cán_bộ , đảng_viên ở cơ_sở . 
Việc tuyên_truyền phải thiết_thực , gắn với những hành_động cụ_thể , lựa_chọn các mô_hình tiêu_biểu để nhân rộng . 
Trong điều_kiện nguồn vốn còn hạn_chế , cần vận_động người dân chủ động tham_gia thực_hiện một_số tiêu_chí không cần nguồn kinh_phí hỗ_trợ như : tạo cảnh_quan môi_trường xanh - sạch - đẹp , khang_trang ... 
Thứ hai , tiếp_tục nghiên_cứu , điều_chỉnh các tiêu_chí cho phù_hợp với từng địa_phương , khu_vực . 
Xây_dựng nông_thôn mới là công_việc lâu_dài , do đó việc thực_hiện các tiêu_chí ở địa_phương cần có kế_hoạch và căn_cơ cụ_thể . 
Việc đánh_giá kết_quả xây_dựng nông_thôn mới phải dựa trên sự tiến_bộ xã_hội , dựa trên sự thay_đổi cả đời_sống vật_chất và tinh_thần của người dân , tránh việc chạy theo thành_tích mà thiếu thực_chất . 
Để xây_dựng nông_thôn mới đi vào thực_chất , các địa_phương cần rà_soát lại quy_hoạch , cần quan_tâm đến những vấn_đề bức_xúc trong dân để từ đó có sự lựa_chọn đầu_tư hoàn_thiện , những tiêu_chí có ý_nghĩa cấp_thiết làm thay_đổi đời_sống của người dân . 
Thứ ba , tập_trung huy_động mọi nguồn_lực cho xây_dựng nông_thôn mới . 
Trung_ương cần nâng mức phân_bổ vốn chương_trình mục_tiêu quốc_gia về xây_dựng nông_thôn mới để hỗ_trợ đầu_tư cho các mô_hình sản_xuất , nâng_cao thu_nhập cho người dân . 
Nên có cơ_chế đặc_thù cho khu_vực đồng_bằng sông Cửu_Long trong đầu_tư xây_dựng hệ_thống kết_cấu_hạ_tầng , do đặc_điểm của khu_vực này có suất đầu_tư cao hơn các khu_vực khác . 
Bên cạnh nguồn vốn từ ngân_sách , cần có các chính_sách đặc_thù thu_hút được các doanh_nghiệp đầu_tư vào lĩnh_vực nông_nghiệp , huy_động nguồn đóng_góp sức người , sức của từ người dân thông_qua việc đóng_góp ngày_công lao_động , hiến đất xây_dựng ... 
Thứ tư , phát_triển sản_xuất , nâng_cao thu_nhập cho người dân . 
Đẩy_mạnh quy_hoạch_vùng sản_xuất nông_sản hàng_hoá tập_trung gắn với đầu_tư đồng_bộ hạ_tầng sản_xuất , chế_biến để nâng_cao giá_trị nông_sản , nhất_là nông_sản xuất_khẩu . 
Chuyển_dịch cơ_cấu cây trồng , vật_nuôi , nhằm tăng hiệu_quả sản_xuất , nâng_cao thu_nhập của người dân . 
Tập_trung xây_dựng và phát_triển các mô_hình sản_xuất lớn có hiệu_quả như  cánh_đồng lớn  , các hợp_tác_xã kinh_doanh tổng_hợp , các trang_trại gắn với bao_tiêu sản_phẩm , áp_dụng các công_nghệ tiên_tiến vào sản_xuất nông_nghiệp ( sản_xuất theo mô_hình VietGAP , GlobalGAP , ... ) nhằm tạo chuyển_biến trong sản_xuất nông_nghiệp , từng bước hình_thành nền nông_nghiệp hàng_hoá lớn . 
Tăng_cường  liên_kết 4 nhà  theo chuỗi giá_trị , giải_quyết tốt vấn_đề thị_trường đầu_ra cho sản_phẩm . 
Thứ năm , tăng_cường sự lãnh_đạo của Đảng , sự quản_lý của Nhà_nước đối_với xây_dựng nông_thôn mới , phát_huy vai_trò của Mặt_trận Tổ_quốc , các đoàn_thể nhân_dân trong xây_dựng nông_thôn mới . 
Có cơ_chế phối_hợp chặt_chẽ và lồng_ghép có hiệu_quả các chương_trình mục_tiêu quốc_gia như chương_trình xoá đói giảm nghèo ... 
Hỗ_trợ đào_tạo , bồi_dưỡng cho cán_bộ cấp cơ_sở ở nông_thôn những nhận_thức về vai_trò của nông_nghiệp , nông_dân và nông_thôn , nâng_cao trình_độ nghiệp_vụ cho đội_ngũ này , bởi lẽ đây là đội_ngũ trực_tiếp làm công_tác xây_dựng nông_thôn mới . 
Thứ_sáu , thường_xuyên sơ_kết , tổng_kết chương_trình , qua đó rút ra những bài_học từ thực_tiễn , phát_hiện những mô_hình triển_khai có hiệu_quả từ đó tổ_chức nhân rộng . 
Công_tác sơ_kết , tổng_kết phải được tiến_hành nghiêm_túc , thực_chất , không chạy theo thành_tích , hình_thức để có_thể rút kinh_nghiệm cho những năm tiếp_theo . 
Đẩy_mạnh liên_kết vùng trong trong xây_dựng nông_thôn mới , nhất_là trong xúc_tiến thương_mại , giải_quyết vấn_đề thị_trường tiêu_thụ , trong xây_dựng kết_cấu_hạ_tầng kinh_tế - xã_hội . 
�_tầng kinh_tế - xã_hội . 
