Quyết_định về việc điều_chỉnh , bổ_sung chỉ_tiêu chương_trình mục_tiêu quốc_gia trên địa_bàn thành_phố năm 2009 
Chủ_tịch ủy ban nhân_dân thành_phố hồ chí minh 
Căn_cứ Luật Tổ_chức Hội_đồng_nhân_dân và Uỷ_ban_nhân_dân ngày 26 tháng 11 năm 2003 ; 
Căn_cứ Quyết_định số 1676/QĐ-TTg ngày 19 tháng 11 năm 2008 của Thủ_tướng Chính_phủ về việc giao dự_toán ngân_sách Nhà_nước năm 2009 ; 
Căn_cứ Quyết_định số 1547/QĐ-BKH ngày 19 tháng 11 năm 2008 của Bộ_trưởng Bộ Kế_hoạch và Đầu_tư về việc giao chỉ_tiêu kế_hoạch phát_triển kinh_tế - xã_hội năm 2009 và Quyết_định số 260/QĐ-BKH ngày 19 tháng 11 năm 2008 của Bộ_trưởng Bộ Kế_hoạch và Đầu_tư về việc giao chỉ_tiêu kế_hoạch đầu_tư phát_triển thuộc 
ngân_sách nhà_nước năm 2009 ; 
Căn_cứ Nghị_quyết số 05/2008/NQ-HĐND ngày 05 tháng 12 năm 2008 của Hội_đồng_nhân_dân thành_phố về dự_toán và phân_bổ ngân_sách năm 2009 và Nghị_quyết số 06/2008/NQ-HĐND ngày 05 tháng 12 năm 2008 của Hội_đồng_nhân_dân thành_phố về nhiệm kinh_tế - xã_hội năm 2009 ; 
Căn_cứ Công_văn số 14618/BTC-NSNN ngày 16 tháng 10 năm 2009 của Bộ Tài_chính về việc bổ_sung kinh_phí thực_hiện dự_án Phòng , chống dịch sốt_xuất_huyết và Công_văn số 14925/BTC-NSNN ngày 22 tháng 10 năm 2009 của Bộ Tài_chính về việc bổ_sung kinh_phí thực_hiện dự_án Phòng , chống bệnh tăng huyết_áp và dự_án Phòng , chống bệnh đái_tháo_đường ; 
Xét đề_nghị của Giám_đốc Sở Kế_hoạch và Đầu_tư tại Tờ_trình số 8397/TTr - SKHĐT ngày 28 tháng 12 năm 2009, 
Quyết_định : 
Điều 1 . Điều_chỉnh kinh_phí của các dự_án thuộc chương_trình mục_tiêu quốc_gia về dân_số , kế_hoạch_hoá gia_đình và chương_trình mục_tiêu quốc_gia vệ_sinh an_toàn thực_phẩm năm 2009 do Sở Y_tế quản_lý và giao bổ_sung chỉ_tiêu chương_trình mục_tiêu quốc_gia trên địa_bàn thành_phố năm 2009 cho dự_án Phòng , chống dịch sốt_xuất_huyết ; dự_án Phòng , chống bệnh tăng huyết_áp và dự_án Phòng , chống bệnh đái_tháo_đường thuộc chương_trình mục_tiêu quốc_gia phòng , chống một_số bệnh_xã_hội , bệnh dịch nguy_hiểm và HIV / AIDS với tổng_kinh_phí là 5.769,7 triệu đồng ( Năm tỷ bảy trăm sáu mươi chín triệu bảy trăm ngàn đồng ) cho Sở Y_tế ( đính kèm danh_mục chương_trình mục_tiêu quốc_gia giao cho Sở Y_tế ) . 
Điều 2 . Sau khi nhận được chỉ_tiêu điều_chỉnh , bổ_sung ban_hành kèm theo Quyết_định này , Giám_đốc Sở Y_tế , Thủ_trưởng các Sở - ngành có liên_quan tiến_hành phân_bổ , giao chỉ_tiêu cho các đơn_vị trực_thuộc theo đúng chỉ_tiêu kế_hoạch được giao ; tổ_chức thực_hiện và báo_cáo tiến_độ định_kỳ hàng quý gửi Sở Kế_hoạch và Đầu_tư , Sở Tài_chính để tổng_hợp , báo_cáo Bộ Kế_hoạch và Đầu_tư , Bộ Tài_chính và Uỷ_ban_nhân_dân thành_phố ; trường_hợp có yêu_cầu cần điều_chỉnh , bổ_sung , phải trình Uỷ_ban_nhân_dân thành_phố xem_xét , quyết_định . 
Điều 3 . Quyết_định này có hiệu_lực thi_hành kể từ ngày ký . 
Các nội_dung khác không đề_cập vẫn giữ nguyên như Quyết_định số 08/2009/QĐ-UBND ngày 22 tháng 01 năm 2009 và Quyết_định số 54/2009/QĐ-UBND ngày 21 tháng 7 năm 2009 của Uỷ_ban_nhân_dân thành_phố về việc điều_chỉnh chương_trình mục_tiêu quốc_gia trên địa_bàn thành_phố năm 2009 . 
Điều 4 . Chánh_Văn_phòng Uỷ_ban_nhân_dân thành_phố , Giám_đốc Sở Kế_hoạch và Đầu_tư , Giám_đốc Sở Tài_chính , Giám_đốc Kho_bạc Nhà_nước thành_phố , Giám_đốc Sở Y_tế , Thủ_trưởng các Sở - ngành có liên_quan chịu trách_nhiệm thi_hành Quyết_định này . 
