Quyết_định ban_hành quy_định cấp giấy_phép xây_dựng và quản_lý việc xây_dựng công_trình theo giấy_phép trên địa_bàn thành_phố hà nội 
Ủy ban nhân_dân thành_phố hà nội 
Căn_cứ Luật Tổ_chức HĐND và UBND ngày 26/11/2003 ; 
Căn_cứ Luật Xây_dựng ; Luật sửa_đổi , bổ_sung một_số điều của các Luật liên_quan đến đầu_tư xây_dựng_cơ_bản ; Nghị_định số 209/2004/NĐ-CP ngày 16/12/2004 của Chính_phủ về quản_lý chất_lượng công_trình ; Nghị_định số 08/2005/NĐ-CP ngày 24/01/2005 của Chính_phủ về quy_hoạch xây_dựng ; Nghị_định số 180/2007/NĐ-CP ngày 07/12/2007 quy_định chi_tiết và hướng_dẫn thực_hiện một_số điều của Luật Xây_dựng về xử_lý vi_phạm trật_tự xây_dựng đô_thị ; Nghị_định số 12/2009/NĐ-CP ngày 12/02/2009 của Chính_phủ về quản_lý dự_án đầu_tư xây_dựng công_trình ; Nghị_định số 83/2009/NĐ-CP về sửa_đổi , bổ_sung một_số điều_Nghị_định số 12/2009/NĐ-CP ngày 12/02/2009 của Chính_phủ về quản_lý dự_án đầu_tư xây_dựng công_trình ; 
Căn_cứ Pháp_lệnh Thủ_đô Hà_Nội ; Nghị_định số 92/2005/NĐ-CP ngày 12/7/2005 của Chính_phủ quy_định chi_tiết một_số điều của Pháp_lệnh Thủ_đô Hà_Nội ; 
Căn_cứ Quyết_định số 89/2007/QĐ-TTg ngày 18/6/2007 của Thủ_tướng Chính_phủ thí_điểm thành_lập Thanh_tra xây_dựng quận , huyện và Thanh_tra xây_dựng phường , xã , thị_trấn tại thành_phố Hà_Nội và thành_phố Hồ_Chí_Minh ; 
Căn_cứ Thông_tư số 03/2009/TT-BXD ngày 26/3/2009 của Bộ Xây_dựng quy_định chi_tiết một_số nội_dung của Nghị_định số 12/2009/NĐ-CP ngày 12/02/2009 của Chính_phủ ; 
Theo đề_nghị của Giám_đốc Sở Xây_dựng tại văn_bản số 8648/SXD-QLCP ngày 02/11/2009, 
Quyết_định : 
Điều 1 . Ban_hành kèm theo Quyết_định này Quy_định cấp giấy_phép xây_dựng và quản_lý xây_dựng công_trình theo giấy_phép xây_dựng trên địa_bàn thành_phố Hà_Nội . 
Điều 2 . Quyết_định này có hiệu_lực sau 15 ngày kể từ ngày ký và thay_thế Quyết_định số 79/2007/QĐ-UB ngày 11/7/2007 ban_hành Quy_định cấp Giấy_phép xây_dựng các công_trình trên địa_bàn thành_phố Hà_Nội ; Thông_báo số 427/TB-UBND ngày 26/12/2007 về việc tạm dừng thực_hiện một điểm của Khoản 12 Điều 7 Quy_định cấp phép xây_dựng các công_trình trên địa_bàn Thành_phố Hà_Nội ban_hành kèm theo Quyết_định số 79/2007/QĐ-UB ngày 11/7/2007 và Điều 1 , Khoản V , Điểm 2 , Tiết_2.1 Quyết_định số 51/2008/QĐ-UBND ngày 16/12/2008 về việc phân_cấp quản_lý_nhà_nước một_số lĩnh_vực kinh_tế - xã_hội trên địa_bàn thành_phố Hà_Nội giai_đoạn 2009 - 2010 của Uỷ_ban_nhân_dân thành_phố Hà_Nội . 
Điều 3 . Chánh_Văn_phòng UBND Thành_phố ; Giám_đốc các Sở : Xây_dựng , Quy_hoạch Kiến_trúc , Văn_hoá Thể_thao và Du_lịch , Thông_tin Truyền_thông ; Thủ_trưởng các Sở , Ban , Ngành , Thành_phố , Chủ_tịch UBND các quận , huyện , thị_xã , phường , xã , thị_trấn và các tổ_chức , cá_nhân có liên_quan chịu trách_nhiệm thi_hành Quyết_định này . 
