Điện : Uỷ_ban_nhân_dân thành_phố Hà_Nội Do có sự quan_tâm của toàn xã_hội và sự chỉ_đạo sát_sao của các cấp , các ngành , công_tác bảo_đảm vệ_sinh an_toàn thực_phẩm thời_gian gần đây đã có tiến_bộ nhất_định ; số vụ ngộ_độc thực_phẩm giảm đi rõ_rệt , nhiều hành_vi vi_phạm như : sản_xuất , vận_chuyển , nhập_khẩu , buôn_bán nguyên_liệu và sản_phẩm thực_phẩm không bảo_đảm vệ_sinh an_toàn thực_phẩm , rau , quả tươi không rõ nguồn_gốc , thực_phẩm giả thực_phẩm kém chất_lượng ... đã được ngăn_chặn , phát_hiện và xử_lý kịp_thời . 
Tuy_nhiên , đây mới chỉ là những kết_quả bước_đầu , tình_hình vệ_sinh an_toàn thực_phẩm vẫn chưa tốt và còn diễn_biến rất phức_tạp nhất là dịp Tết nguyên_đán sắp tới , nhu_cầu tiêu_thụ thực_phẩm của nhân_dân tăng cao , việc sản_xuất và buôn_bán , chế_biến các loại thực_phẩm trên thị_trường cũng sẽ tăng tương_ứng , từ đó gia_tăng nguy_cơ không bảo_đảm chất_lượng , vệ_sinh an_toàn thực_phẩm . 
Để triển_khai những ngày cao_điểm bảo_đảm vệ_sinh an_toàn thực_phẩm vì sức_khoẻ cộng_đồng và đón mừng xuân mới Canh Dần 2010 , Thủ_tướng Chính_phủ yêu_cầu : 
1 . Uỷ_ban_nhân_dân các tỉnh , thành_phố trực_thuộc Trung_ương : 
- Chỉ_đạo tăng_cường kiểm_tra , thanh_tra việc chấp_hành các quy_định vệ_sinh an_toàn thực_phẩm của các cơ_sở sản_xuất , kinh_doanh thực_phẩm có nguy_cơ cao như thịt và các sản_phẩm từ thịt , thuỷ_sản tươi_sống , trứng , sữa_tươi , rau , quả tươi và một_số loại thực_phẩm thường dùng dịp Tết như mứt , xí_muội ( ô_mai ) , hạt dưa , các loại nước_chấm , ... ; giám_sát chặt_chẽ việc lưu_thông các mặt_hàng trên , đặc_biệt tại các chợ đầu_mối và cơ_sở thương_mại tập_trung . 
Xử_lý nghiêm và thông_báo kịp_thời , rộng_rãi trên các phương_tiện thông_tin_đại_chúng các hành_vi vi_phạm và các sản_phẩm không bảo_đảm chất_lượng , không bảo_đảm vệ_sinh an_toàn thực_phẩm để người tiêu_dùng biết . 
- Tăng_cường vai_trò của các đoàn_thể xã_hội trong việc tuyên_truyền , vận_động các hộ_sản xuất , kinh_doanh , chế_biến thực_phẩm , chấp_hành các quy_định về vệ_sinh an_toàn thực_phẩm và tham_gia phổ_biến kiến_thức , thực_hành vệ_sinh an_toàn thực_phẩm cho người tiêu_dùng . 
- Chủ_tịch Uỷ_ban_nhân_dân các tỉnh biên_giới chỉ_đạo các ngành chức_năng : Quản_lý thị_trường , Nông_nghiệp và Phát_triển nông_thôn , Công_an , Biên_phòng ... phối_hợp với các cơ_quan_chuyên_môn trong ngành Y_tế tăng_cường công_tác kiểm_soát chặt_chẽ thực_phẩm nhập qua biên_giới , kiên_quyết ngăn_chặn việc nhập_khẩu , lưu_hành trên thị_trường Việt_Nam các sản_phẩm thực_phẩm nhập lậu , thực_phẩm không rõ nguồn_gốc , thực_phẩm không bảo_đảm vệ_sinh an_toàn . 
2 . Bộ Y_tế : 
- Chủ_trì , phối_hợp với các Bộ , ngành chỉ_đạo và hướng_dẫn triển_khai công_tác vệ_sinh an_toàn thực_phẩm , kiểm_tra , thanh_tra toàn_diện về vệ_sinh an_toàn thực_phẩm tại các tỉnh , thành_phố trọng_điểm . 
- Phối_hợp với các Bộ , ngành rà_soát và có các giải_pháp kiểm_soát chặt_chẽ chất_lượng , vệ_sinh an_toàn thực_phẩm đối_với các mặt_hàng thực_phẩm nhập_khẩu trong phạm_vi được phân_công . 
- Thường_xuyên cập_nhật , cảnh_báo , xử_lý kịp_thời các nguy_cơ mất an_toàn vệ_sinh thực_phẩm . 
- Phối_hợp với Bộ Thông_tin và Truyền_thông triển_khai và hướng_dẫn các cơ_quan thông_tin , truyền_thông tuyên_truyền đầy_đủ , kịp_thời các biện_pháp bảo_đảm vệ_sinh an_toàn thực_phẩm , chú_trọng việc thông_tin , giới_thiệu các mô_hình thực_hiện tốt công_tác bảo_đảm an_toàn vệ_sinh thực_phẩm , các sản_phẩm thực_phẩm an_toàn . 
3 . Bộ Nông_nghiệp và Phát_triển nông_thôn : 
- Chỉ_đạo , phối_hợp với các cơ_quan truyền_thông tuyên_truyền , giáo_dục nông_dân , các cơ_sở trồng_trọt , chăn_nuôi , các tổ_chức , cá_nhân thu_gom , sơ_chế , giết_mổ , chế_biến , bảo_quản nông_sản , thuỷ_sản thực_phẩm thực_hiện tốt các quy_định về an_toàn thực_phẩm . 
- Tăng_cường công_tác kiểm_tra , xử_lý nghiêm các hành_vi vi_phạm các quy_định về vệ_sinh an_toàn thực_phẩm trong sản_xuất , chế_biến thực_phẩm , tập_trung vào các thực_phẩm có mức tiêu_thụ cao trong dịp Tết như rau , quả , thịt gia_súc , gia_cầm , thuỷ_sản tươi_sống . 
4 . Bộ Công_Thương : 
- Chỉ_đạo tăng_cường kiểm_tra , kiểm_soát , đấu_tranh chống các hành_vi vi_phạm về sản_xuất , vận_chuyển , buôn_bán thực_phẩm giả , thực_phẩm không bảo_đảm vệ_sinh an_toàn thực_phẩm . 
- Tăng_cường phối_hợp với lực_lượng Hải_quan , Bộ_đội biên_phòng và các đơn_vị liên_quan , đặc_biệt tại các tỉnh biên_giới , kiên_quyết ngăn_chặn việc nhập_khẩu lậu nguyên_liệu và sản_phẩm thực_phẩm , thực_phẩm giả , thực_phẩm không bảo_đảm chất_lượng và xử_lý triệt_để , nghiêm_minh các hành_vi vi_phạm . 
5 . Bộ Quốc_phòng , Bộ Công_an : 
Chỉ_đạo các lực_lượng Công_an , Bộ_đội biên_phòng phối_hợp với lực_lượng Hải_quan và các cơ_quan của địa_phương kiểm_soát , ngăn_chặn và xử_lý kiên_quyết việc nhập_khẩu thực_phẩm trái_phép qua biên_giới . 
6 . Đài_Truyền_hình Việt_Nam , Đài Tiếng_nói Việt_Nam , Thông_tấn_xã Việt_Nam và các phương_tiện thông_tin_đại_chúng ở Trung_ương và địa_phương : 
- Tăng thời_lượng phát_sóng , thực_hiện tuyên_truyền , phổ_biến kiến_thức về vệ_sinh an_toàn thực_phẩm , tạo ý_thức cho người dân biết tự bảo_vệ sức_khoẻ , tính_mạng của mình và không gây nguy_cơ bệnh dịch , thiệt_hại về người , sức_khoẻ cho cộng_đồng dân_cư . 
- Thông_báo kịp_thời , rộng_rãi trên các phương_tiện thông_tin_đại_chúng các hành_vi vi_phạm và các sản_phẩm không bảo_đảm chất_lượng , không bảo_đảm vệ_sinh an_toàn thực_phẩm để người tiêu_dùng biết . 
- Đẩy_mạnh việc thông_tin tuyên_truyền về các mô_hình thực_hiện tốt công_tác bảo_đảm an_toàn vệ_sinh thực_phẩm , các sản_phẩm thực_phẩm an_toàn tới cộng_đồng kết_hợp với việc phổ_biến các nguy_cơ ảnh_hưởng đến sức_khoẻ và tính_mạng khi sử_dụng thực_phẩm không bảo_đảm vệ_sinh an_toàn . 
7 . Đề_nghị Mặt_trận Tổ_quốc Việt_Nam , các đoàn_thể và các tổ_chức xã_hội phối_hợp với các cơ_quan_chức_năng , chính_quyền địa_phương triển_khai có hiệu_quả các hoạt_động bảo_đảm vệ_sinh an_toàn thực_phẩm trong dịp Tết nguyên_đán Canh Dần 2010 . 
Giao Bộ Y_tế theo_dõi , tổng_hợp và báo_cáo Thủ_tướng Chính_phủ kết_quả thực_hiện công_tác bảo_đảm vệ_sinh an_toàn thực_phẩm trong dịp Tết nguyên_đán Canh Dần 2010 . 
