Chỉ_thị về triển_khai thực_hiện luật trách_nhiệm bồi_thường của nhà_nước trong ngành tư_pháp 
Luật Trách_nhiệm bồi_thường của Nhà_nước ( sau đây gọi chung là Luật ) được Quốc_hội thông_qua ngày 18 tháng 6 năm 2009 , có hiệu_lực từ ngày 01 tháng 01 năm 2010 . 
Đây đạo_luật đầu_tiên ở nước ta quy_định đầy_đủ , đồng_bộ tất_cả các vấn_đề liên_quan đến chế_độ trách_nhiệm bồi_thường của Nhà_nước đối_với các thiệt_hại do cán_bộ , công_chức gây ra trong khi thi_hành công_vụ như đối_tượng được bồi_thường ; cơ_quan có trách_nhiệm giải_quyết bồi_thường ; phạm_vi trách_nhiệm bồi_thường của Nhà_nước ; căn_cứ phát_sinh trách_nhiệm bồi_thường ; các loại thiệt_hại và mức thiệt_hại được bồi_thường ; thủ_tục giải_quyết bồi_thường ; kinh_phí bồi_thường và trách_nhiệm hoàn_trả của người thi_hành công_vụ đã gây ra thiệt_hại . 
Luật đã quy_định rõ Nhà_nước có trách_nhiệm bồi_thường đối_với các thiệt_hại do cán_bộ , công_chức gây ra trong ba lĩnh_vực hoạt_động là quản_lý hành_chính , tố_tụng và thi_hành án . 
Trong đó , bồi_thường nhà_nước trong lĩnh_vực hoạt_động quản_lý hành_chính và thi_hành án có liên_quan trực_tiếp đến hoạt_động quản_lý_nhà_nước của các Bộ , ngành và Uỷ_ban_nhân_dân các cấp . 
Cũng theo quy_định của Luật , Nhà_nước không_chỉ có trách_nhiệm bồi_thường thiệt_hại do các hành_vi chủ_động của cán_bộ , công_chức gây ra mà_còn phải bồi_thường đối_với cả các thiệt_hại do việc cán_bộ , công_chức không thực_hiện công_vụ mà theo quy_định của pháp_luật , cán_bộ , công_chức phải làm . 
Việc thực_thi Luật không_chỉ góp_phần bảo_vệ quyền và lợi_ích hợp_pháp của tổ_chức , cá_nhân bị cán_bộ , công_chức nhà_nước có hành_vi trái pháp_luật , gây ra thiệt_hại trong khi thi_hành công_vụ mà_còn góp_phần nâng_cao tinh_thần trách_nhiệm , ý_thức công_vụ của đội_ngũ cán_bộ , công_chức nhà_nước . 
Để thi_hành Luật này và thực_hiện có hiệu_quả nhiệm_vụ giúp Chính_phủ thống_nhất quản_lý_nhà_nước về công_tác bồi_thường trong hoạt_động quản_lý hành_chính và thi_hành án ; phối_hợp với Viện_kiểm_sát nhân_dân tối_cao , Toà_án nhân_dân tối_cao quản_lý_nhà_nước đối_với công_tác bồi_thường thiệt_hại trong hoạt_động tố_tụng , Bộ_trưởng Bộ Tư_pháp chỉ_thị : 
1 . Thủ_trưởng các đơn_vị thuộc Bộ , Cục_trưởng Cục Thi_hành án dân_sự cấp tỉnh , Chi_cục_trưởng Chi_cục Thi_hành án dân_sự cấp huyện , trong phạm_vi chức_năng , nhiệm_vụ , quyền_hạn của mình có trách_nhiệm sau đây : 
a ) Quán_triệt tinh_thần và nội_dung của Luật Trách_nhiệm bồi_thường của Nhà_nước , Chỉ_thị số 1565/CT-TTg ngày 06 tháng 10 năm 2009 của Thủ_tướng Chính_phủ về triển_khai thi_hành Luật này và các văn_bản hướng_dẫn thi_hành đến cán_bộ , công_chức của đơn_vị bằng các hình_thức và biện_pháp thích_hợp để cán_bộ , công_chức nhận_thức được ý_nghĩa , vai_trò , tác_dụng của Luật , nắm rõ các hành_vi mà nếu cán_bộ , công_chức vi_phạm gây ra thiệt_hại thì Nhà_nước sẽ phải bồi_thường và cá_nhân phải bồi_hoàn cho Nhà_nước ; 
b ) Phân_công cán_bộ theo_dõi công_tác giải_quyết bồi_thường để kịp_thời thực_hiện thủ_tục giải_quyết bồi_thường khi người bị thiệt_hại có đơn yêu_cầu bồi_thường ; 
c ) Đôn_đốc , chỉ_đạo việc giải_quyết bồi_thường thuộc trách_nhiệm của đơn_vị mình , bảo_đảm thực_hiện bồi_thường công_bằng , khách_quan , đúng pháp_luật và thống_nhất ; 
d ) Phối_hợp với Vụ Pháp_luật dân_sự - kinh_tế trong việc giải_quyết các vấn_đề pháp_lý phát_sinh trong quá_trình tổ_chức thực_hiện việc bồi_thường và quản_lý_nhà_nước về công_tác bồi_thường . 
2 . Vụ Pháp_luật dân_sự - kinh_tế 
Đôn_đốc các đơn_vị có liên_quan tổ_chức thực_hiện tốt Quyết_định số 3193/QĐ-BTP ngày 09 tháng 11 năm 2009 của Bộ_trưởng Bộ Tư_pháp về việc ban_hành Kế_hoạch thực_hiện Chỉ_thị số 1565/CT-TTg ngày 06 tháng 10 năm 2009 của Thủ_tướng Chính_phủ về triển_khai thi_hành Luật Trách_nhiệm bồi_thường của Nhà_nước và có trách_nhiệm sau đây : 
a ) Chủ_trì , phối_hợp với các đơn_vị có liên_quan xây_dựng các văn_bản quy_phạm pháp_luật để hướng_dẫn thi_hành pháp_luật về bồi_thường nhà_nước , trình Bộ_trưởng Bộ Tư_pháp ban_hành theo thẩm_quyền hoặc trình cơ_quan nhà_nước có thẩm_quyền ban_hành ; 
b ) Chủ_trì , phối_hợp với Vụ Tổ_chức cán_bộ , Tổng_cục Thi_hành án dân_sự và các đơn_vị liên_quan tham_mưu , đề_xuất đầu_mối giúp Bộ_trưởng Bộ Tư_pháp thực_hiện quản_lý_nhà_nước về công_tác bồi_thường theo quy_định của pháp_luật ; 
c ) Chủ_trì , phối_hợp với các đơn_vị liên_quan xây_dựng tài_liệu , chương_trình tập_huấn , định_kỳ tổ_chức bồi_dưỡng kiến_thức về pháp_luật bồi_thường nhà_nước , kỹ_năng giải_quyết bồi_thường cho các cán_bộ , công_chức trực_tiếp làm công_tác giải_quyết bồi_thường , bảo_đảm việc giải_quyết bồi_thường được thực_hiện đúng pháp_luật , thống_nhất trong phạm_vi cả nước ; 
d ) Trước_mắt , trong khi chưa xác_định đầu_mối giúp Bộ_trưởng Bộ Tư_pháp quản_lý_nhà_nước về công_tác bồi_thường , chủ_trì , phối_hợp với các đơn_vị thuộc Bộ theo_dõi , thống_kê các hành_vi trái pháp_luật của cán_bộ , công_chức gây ra thiệt_hại thuộc phạm_vi quản_lý của Ngành Tư_pháp ; nắm_bắt những khiếm_khuyết , hạn_chế của hệ_thống pháp_luật , phát_hiện những vướng_mắc , khó_khăn trong hoạt_động thi_hành công_vụ để kiến_nghị với Bộ_trưởng về các giải_pháp cải_cách hành_chính , nâng_cao trách_nhiệm của cán_bộ , công_chức trong khi thi_hành công_vụ , bảo_đảm hiệu_lực , hiệu_quả trong hoạt_động của các cơ_quan do Bộ quản_lý ; 
đ ) Phối_hợp với các đơn_vị thuộc Bộ xác_định nhu_cầu kinh_phí hàng năm để bảo_đảm công_tác bồi_thường . 
3 . Tổng_cục Thi_hành án dân_sự 
a ) Căn_cứ vào Luật Thi_hành án dân_sự và các văn_bản liên_quan , rà_soát các quyết_định , hành_vi công_vụ trong hoạt_động thi_hành án dân_sự thuộc phạm_vi trách_nhiệm bồi_thường của Nhà_nước để kịp_thời hướng_dẫn , đôn_đốc công_chức làm công_tác thi_hành án dân_sự thực_thi công_vụ đúng pháp_luật , phòng tránh các hành_vi trái pháp_luật gây ra thiệt_hại . 
b ) Hướng_dẫn việc phân_công , bố_trí công_chức trực_tiếp làm công_tác giải_quyết bồi_thường ở các cơ_quan , đơn_vị thi_hành án dân_sự . 
Phối_hợp với Vụ Pháp_luật dân_sự , kinh_tế tổ_chức bồi_dưỡng , tập_huấn kỹ_năng , nghiệp_vụ giải_quyết bồi_thường cho công_chức trực_tiếp làm công_tác bồi_thường . 
c ) Theo_dõi , đôn_đốc , chỉ_đạo việc giải_quyết bồi_thường , bảo_đảm thực_hiện bồi_thường công_bằng , khách_quan , đúng pháp_luật và thống_nhất tại các cơ_quan thi_hành án dân_sự . 
d ) Xác_định nhu_cầu kinh_phí hàng năm để lập dự_toán ngân_sách cho công_tác giải_quyết bồi_thường thuộc trách_nhiệm của Tổng_cục và các đơn_vị trực_thuộc . 
đ ) Trước_mắt , trong khi chưa xác_định đầu_mối giúp Bộ_trưởng Bộ Tư_pháp quản_lý_nhà_nước về công_tác bồi_thường , phối_hợp với Vụ Pháp_luật dân_sự - kinh_tế thực_hiện nhiệm_vụ quản_lý_nhà_nước về công_tác bồi_thường trong hoạt_động thi_hành án dân_sự . 
4 . Vụ Phổ_biến , giáo_dục pháp_luật 
a ) Chủ_trì , phối_hợp với các đơn_vị liên_quan , các Sở Tư_pháp và tổ_chức pháp_chế thuộc Bộ , cơ_quan ngang Bộ và cơ_quan thuộc Chính_phủ trong việc thực_hiện tuyên_truyền , phổ_biến nội_dung của Luật Trách_nhiệm bồi_thường của Nhà_nước cũng như các văn_bản hướng_dẫn thi_hành trong toàn Ngành Tư_pháp . 
b ) Chủ_trì , phối_hợp với Bộ Thông_tin và Truyền_thông tổ_chức tuyên_truyền , phổ_biến Luật Trách_nhiệm bồi_thường của Nhà_nước và các văn_bản hướng_dẫn thi_hành trên phạm_vi toàn_quốc . 
5 . Báo Pháp_luật_Việt_Nam 
Chủ_trì , phối_hợp với Vụ Phổ_biến , giáo_dục pháp_luật , Vụ Pháp_luật dân_sự - kinh_tế và các đơn_vị liên_quan chủ_động thực_hiện việc đưa tin , tuyên_truyền việc thực_hiện Luật Trách_nhiệm bồi_thường của Nhà_nước và các văn_bản hướng_dẫn thi_hành trên các ấn_phẩm của Báo Pháp_luật_Việt_Nam . 
6 . Vụ Kế_hoạch - tài_chính 
a ) Chủ_trì , phối_hợp với Tổng_cục Thi_hành án dân_sự , các đơn_vị có liên_quan lập dự_toán kinh_phí cho công_tác giải_quyết bồi_thường thuộc trách_nhiệm của Bộ Tư_pháp , báo_cáo Bộ Tài_chính để đưa vào cân_đối chung . 
b ) Bố_trí kinh_phí cho công_tác xây_dựng các văn_bản hướng_dẫn thi_hành Luật Trách_nhiệm bồi_thường của Nhà_nước do Bộ Tư_pháp chủ_trì soạn_thảo hoặc phối_hợp soạn_thảo ; công_tác tuyên_truyền , phổ_biến pháp_luật và kinh_phí cho hoạt_động quản_lý_nhà_nước về bồi_thường . 
7 . Sở Tư_pháp 
a ) Tham_mưu , đề_xuất với Uỷ_ban_nhân_dân cấp tỉnh trong việc tổ_chức thi_hành Luật theo Chỉ_thị số 1565/CT-TTg ngày 06 tháng 10 năm 2009 của Thủ_tướng Chính_phủ về triển_khai thi_hành Luật Trách_nhiệm bồi_thường của Nhà_nước và thực_hiện nhiệm_vụ quản_lý_nhà_nước về công_tác bồi_thường tại địa_phương . 
b ) Phối_hợp với Sở Thông_tin và Truyền_thông , cơ_quan báo_chí ở địa_phương tổ_chức việc tuyên_truyền , phổ_biến về các nội_dung cơ_bản của Luật Trách_nhiệm bồi_thường của Nhà_nước và các văn_bản hướng_dẫn tại địa_phương . 
c ) Phối_hợp với Bộ Tư_pháp và các cơ_quan hữu_quan tổ_chức tập_huấn kỹ_năng , nghiệp_vụ giải_quyết bồi_thường cho các cán_bộ , công_chức được giao nhiệm_vụ này để bảo_đảm thực_hiện việc giải_quyết bồi_thường công_bằng , khách_quan , đúng pháp_luật và thống_nhất . 
d ) Theo_dõi , thống_kê các hành_vi trái pháp_luật của cán_bộ , công_chức gây ra thiệt_hại thuộc phạm_vi do địa_phương quản_lý ; nắm_bắt những khiếm_khuyết , hạn_chế của hệ_thống pháp_luật , phát_hiện những vướng_mắc , khó_khăn trong hoạt_động thi_hành công_vụ để kiến_nghị với Uỷ_ban_nhân_dân cấp tỉnh và các cơ_quan nhà_nước có thẩm_quyền về các giải_pháp cải_cách hành_chính , nâng_cao trách_nhiệm của cán_bộ , công_chức trong khi thi_hành công_vụ , bảo_đảm hiệu_lực , hiệu_quả trong hoạt_động của các cơ_quan nhà_nước tại địa_phương . 
đ ) Phối_hợp với Sở Tài_chính xác_định nhu_cầu sử_dụng ngân_sách nhà_nước cho công_tác bồi_thường tại địa_phương . 
8 . Tổ_chức pháp_chế thuộc Bộ , cơ_quan ngang Bộ và cơ_quan thuộc Chính_phủ 
a ) Tham_mưu , đề_xuất với Bộ_trưởng , Thủ_trưởng cơ_quan ngang Bộ , cơ_quan thuộc Chính_phủ trong việc tổ_chức thi_hành Luật theo Chỉ_thị số 1565/CT-TTg ngày 06 tháng 10 năm 2009 của Thủ_tướng Chính_phủ về triển_khai thi_hành Luật Trách_nhiệm bồi_thường của Nhà_nước và thực_hiện nhiệm_vụ quản_lý_nhà_nước về công_tác bồi_thường thuộc lĩnh_vực do Bộ , ngành mình quản_lý . 
b ) Tổ_chức tuyên_truyền , phổ_biến Luật và các văn_bản hướng_dẫn thi_hành cho cán_bộ , công_chức trong Bộ , ngành để cán_bộ , công_chức nắm_bắt được những nội_dung cơ_bản của Luật , nhất_là những hành_vi cần phải tránh để hạn_chế đến mức thấp nhất khả_năng phải bồi_thường của Nhà_nước . 
c ) Phối_hợp với Bộ Tư_pháp tổ_chức tập_huấn kỹ_năng , nghiệp_vụ giải_quyết bồi_thường cho cán_bộ , công_chức trực_tiếp làm công_tác giải_quyết bồi_thường tại Bộ , ngành để bảo_đảm thực_hiện việc giải_quyết bồi_thường tại Bộ , ngành mình công_bằng , khách_quan , đúng pháp_luật và thống_nhất . 
d ) Theo_dõi , thống_kê các hành_vi trái pháp_luật của cán_bộ , công_chức gây ra thiệt_hại thuộc phạm_vi do Bộ , ngành quản_lý ; nắm_bắt những khiếm_khuyết , hạn_chế của hệ_thống pháp_luật , phát_hiện những vướng_mắc , khó_khăn trong hoạt_động thi_hành công_vụ để kiến_nghị với Bộ_trưởng , thủ_trưởng cơ_quan ngang Bộ , cơ_quan thuộc Chính_phủ và các cơ_quan nhà_nước có thẩm_quyền về các giải_pháp cải_cách hành_chính , nâng_cao trách_nhiệm của cán_bộ , công_chức trong khi thi_hành công_vụ , bảo_đảm hiệu_lực , hiệu_quả trong hoạt_động của các cơ_quan nhà_nước do Bộ , ngành mình quản_lý . 
đ ) Phối_hợp với các đơn_vị thuộc Bộ , cơ_quan ngang Bộ , cơ_quan thuộc Chính_phủ xác_định nhu_cầu sử_dụng ngân_sách nhà_nước cho công_tác bồi_thường tại Bộ , ngành mình . 
9 . Tổ_chức thực_hiện 
Thủ_trưởng các đơn_vị thuộc Bộ , Giám_đốc Sở Tư_pháp , Thủ_trưởng tổ_chức pháp_chế thuộc Bộ , cơ_quan ngang Bộ và cơ_quan thuộc Chính_phủ , Cục_trưởng Cục Thi_hành án dân_sự , Chi_Cục_trưởng Chi_cục Thi_hành án dân_sự có trách_nhiệm thực_hiện Chỉ_thị này . 
Vụ_trưởng Vụ Pháp_luật dân_sự - kinh_tế có trách_nhiệm theo_dõi , đôn_đốc , kiểm_tra việc thực_hiện Chỉ_thị và định_kỳ 6 tháng báo_cáo Lãnh_đạo Bộ ; hết năm 2010 , tổ_chức tổng_kết , đánh_giá việc thực_hiện Chỉ_thị và đề_xuất giải_pháp cho các năm tiếp_theo . 
