Quyết_định về việc ban_hành quy_định trình_tự , thủ_tục , thời_gian giải_quyết thủ_tục hành_chính về đất_đai trên địa_bàn tỉnh kiên giang 
Ủy ban nhân_dân tỉnh kiên giang 
Căn_cứ Luật Tổ_chức Hội_đồng_nhân_dân và Uỷ_ban_nhân_dân ngày 26 tháng 11 năm 2003 ; 
Căn_cứ Luật Ban_hành văn_bản quy_phạm pháp_luật của Hội_đồng_nhân_dân , Uỷ_ban_nhân_dân ngày 03 tháng 12 năm 2004 ; 
Căn_cứ Luật Đất_đai ngày 26 tháng 11 năm 2003 ; 
Căn_cứ Nghị_định số 181/2004/NĐ-CP ngày 29 tháng 10 năm 2004 của Chính_phủ về thi_hành Luật Đất_đai ; Nghị_định số 17/2006/NĐ-CP ngày 27 tháng 01 năm 2006 về sửa_đổi , bổ_sung một_số điều của các Nghị_định hướng_dẫn thi_hành Luật Đất_đai và Nghị_định số 187/2004/NĐ-CP về việc chuyển Công_ty nhà_nước thành_Công_ty cổ_phần ; Nghị_định số 84/2007/NĐ-CP ngày 25/5/2007 của Chính_phủ quy_định bổ_sung về việc cấp giấy chứng_nhận quyền sử_dụng đất , thu_hồi đất , thực_hiện quyền sử_dụng đất , trình_tự , thủ_tục bồi_thường , hỗ_trợ , tái_định_cư khi Nhà_nước thu_hồi đất và giải_quyết khiếu_nại về đất_đai ; 
Căn_cứ Thông_tư số 01/2005/TT-BTNMT ngày 13 tháng 4 năm 2005 của Bộ Tài_nguyên và Môi_trường hướng_dẫn thực_hiện một_số điều của Nghị_định số 181/2004/NĐ-CP ngày 29 tháng 10 năm 2004 của Chính_phủ về thi_hành Luật Đất_đai ; Thông_tư số 06/2007/TT-BTNMT ngày 15 tháng 6 năm 2007 của Bộ Tài_nguyên và Môi_trường về hướng_dẫn thực_hiện một_số điều của Nghị_định số 84/2007/NĐ-CP ngày 25 tháng 5 năm 2007 của Chính_phủ về quy_định bổ_sung về việc cấp giấy chứng_nhận quyền sử_dụng đất , thu_hồi đất , thực_hiện quyền sử_dụng đất , trình_tự , thủ_tục bồi_thường , hỗ_trợ , tái_định_cư khi Nhà_nước thu_hồi đất và giải_quyết khiếu_nại về đất_đai ; 
Căn_cứ Thông_tư liên_tịch số 14/2008/TTLT-BTC-BTNMT ngày 31 tháng 01 năm 2008 của Bộ Tài_chính và Bộ Tài_nguyên và Môi_trường hướng_dẫn thực_hiện một_số điều của Nghị_định số 84/2007/NĐ-CP ngày 25 tháng 5 năm 2007 của Chính_phủ về quy_định bổ_sung về việc cấp giấy chứng_nhận quyền sử_dụng đất , thu_hồi đất , thực_hiện quyền sử_dụng đất , trình_tự , thủ_tục bồi_thường , hỗ_trợ , tái_định_cư khi Nhà_nước thu_hồi đất và giải_quyết khiếu_nại về đất_đai ; 
Theo đề_nghị của Giám_đốc Sở Tài_nguyên và Môi_trường tại Tờ_trình số 172/TTr-STNMT ngày 29 tháng 9 năm 2008, 
Quyết_định : 
Điều 1 . Ban_hành Quy_định về trình_tự , thủ_tục , thời_gian giải_quyết thủ_tục hành_chính về đất_đai trên địa_bàn tỉnh Kiên_Giang sửa_đổi , bổ_sung và thay_thế Quyết_định số 40/2006/QĐ-UBND ngày 10 tháng 11 năm 2006 của Uỷ_ban_nhân_dân tỉnh Kiên_Giang về việc ban_hành về trình_tự , thủ_tục , thời_gian giải_quyết thủ_tục hành_chính về đất_đai trên địa_bàn tỉnh Kiên_Giang . 
Điều 2 . Giao trách_nhiệm cho Giám_đốc Sở Tài_nguyên và Môi_trường phối_hợp với Sở Xây_dựng , Sở Tài_chính , Sở Kế_hoạch và Đầu_tư và các sở ngành có liên_quan , Uỷ_ban_nhân_dân các huyện , thị_xã , thành_phố , tổ_chức triển_khai thực_hiện đúng quy_định về trình_tự , thủ_tục , thời_gian giải_quyết thủ_tục hành_chính về đất_đai kèm theo Quyết_định này . 
Điều 3 . Chánh_Văn_phòng Uỷ_ban_nhân_dân tỉnh ; Giám_đốc các sở , ngành có liên_quan ; Chủ_tịch Uỷ_ban_nhân_dân các huyện , thị_xã , thành_phố ; Chủ_tịch Uỷ_ban_nhân_dân các xã , phường , thị_trấn và các tổ_chức , hộ gia_đình , cá_nhân có liên_quan chịu trách_nhiệm thi_hành Quyết_định này . 
Quyết_định này có hiệu_lực thi_hành sau 10 ngày kể từ ngày ký và thay_thế Quyết_định số 40/2006/QĐ-UBND ngày 10 tháng 11 năm 2006 của Uỷ_ban_nhân_dân tỉnh Kiên_Giang về việc ban_hành về trình_tự , thủ_tục , thời_gian giải_quyết thủ_tục hành_chính về đất_đai trên địa_bàn tỉnh Kiên_Giang . 
