Không chứng_minh được thì bị_cáo ... phải chịu ( ! ? ) 
Trong lần đối_đáp thứ nhất , VKS phản_bác :  Luật_sư cho rằng bị_cáo_Oanh không_thể rút tiền ra chiếm_đoạt chỉ đúng khi doanh_nghiệp làm_ăn đúng_đắn , còn ở vụ án này giám_đốc Oanh trực_tiếp nắm tiền , chi_tiêu thế_nào không giải_trình được thì nay bị_cáo phải chịu trách_nhiệm  . 
Được toà cho tự bào_chữa , Oanh xin hội_đồng xét_xử ( HĐXX ) :  Nếu được tiếp_tục làm xong dự_án ở Lạc_Long_Quân thì bị_cáo dư sức trả nợ các khoản vay ngân_hàng  . 
Kiểm_sát_viên Đào_Hữu_Đăng cho_biết ngay : khi Oanh bị bắt , dự_án mới chỉ dừng ở giai_đoạn Kiến_trúc_sư_trưởng thành_phố Hà_Nội  giới_thiệu địa_điểm làm dự_án  . 
Còn các công_trình 120 Quán_Thánh , 164 Trần_Quang_Khải ... không được xem_xét để trả nợ cho Công_ty Tiếp_thị , theo đại_diện VKS , vì tài_sản này  nằm trên đất do Nhà_nước quản_lý  , ngay Tổng_công_ty Vật_tư nông_nghiệp cũng không có quyền định_đoạt mà đang phải xin ý_kiến Chính_phủ . 
Quá_trình tranh_luận , đại_diện VKS  phê_bình  người bào_chữa cho bị_cáo Huỳnh_Xuân_Hoàng đã  nhầm_lẫn  khi cãi về công_văn 99 ( do ông Hoàng ký nháy để Công_ty Tiếp_thị xin vay tại Ngân_hàng Đầu_tư phát_triển Hà_Nội ) . 
VKS đưa lý_do  phần này án sơ_thẩm không qui kết bị_cáo  do ngân_hàng chưa cho vay , vì vậy chính bị_cáo Hoàng_khi tự bào_chữa lại phải  thanh_minh  cho luật_gia của mình . 
Ngược lại , các luật_sư Chu_Khang , Nguyễn_Trọng_Tỵ ( bào_chữa cho Oanh ) , Trần_Thị_Phương_Đức ( bào_chữa cho Thuần ) , Hà_Đăng ( bào_chữa cho Quán , Nghĩa ) đều  chê_trách  cách đối_đáp  hết_sức chung_chung  và  không viện_dẫn các căn_cứ , điều_luật cụ_thể  của đại_diện VKS tối_cao ; đồng_thời yêu_cầu HĐXX lưu_ý  những gì luật_sư nêu ra mà VKS không tranh_luận , nghĩa_là VKS đã đồng_ý ...  . 
Nhiều  hạt sạn  trong quá_trình tố_tụng ? 
 Không hiểu luật_gia Trần_Đình_Triển lấy biên_bản giám_định ở đâu ra , vì trong hồ_sơ thể_hiện rõ là kết_luận giám_định ...  - đại_diện VKS thắc_mắc , đồng_thời băn_khoăn  luật_gia có đọc đầy_đủ kết_luận giám_định này chưa ?  . 
Đáp lại , luật_gia Trần_Đình_Triển lập_tức công_bố và gửi HĐXX một văn_bản biên_bản giám_định tài_chính với người giám_định là ông Lại_Đăng_An ( giám_định_viên tại phiên_toà ) . 
Theo ông Triển , thứ nhất , biên_bản này giống như một cáo_trạng buộc_tội hơn là một bản giám_định , với cách sử_dụng nhiều từ_ngữ rất nặng như  lỗ  ,  coi như lỗ  tới con_số hàng chục tỉ đồng khi xem_xét tình_hình Công_ty Tiếp_thị . 
Không_chỉ là biên_bản  không đúng pháp_luật  ; thứ hai , luật_gia tiết_lộ  trong vụ án này có tới một biên_bản và một kết_luận giám_định riêng_rẽ với cùng một người thực_hiện ( ông Lại_Đăng_An )  . 
Người bào_chữa cho bị_cáo Hà_nghi_ngờ  đây rất có_thể cũng là một ... vụ án  cần phải điều_tra , làm sáng_tỏ . 
Trong phần tự bào_chữa và nói lời sau cùng , Lã_Thị_Kim_Oanh vừa khóc vừa  cò_kè  xin HĐXX chấp_nhận từng khoản chi một . 
Đáng lưu_ý , bị_cáo  chợt nhớ ra  hai khoản : khoản 250 triệu đồng khi cùng kế_toán_trưởng Thuần  vác một bao_tải tiền lên chi cho Ban quản_lý các khu công_nghiệp Vĩnh_Phúc  ; khoản nữa gần 1,5 tỉ đồng chi_hội thảo , hội_nghị , chiêu_đãi chuyên_gia , lễ_tết các sếp ở các cơ_quan hữu_quan Hà_Nội để làm dự_án ở Đại_Mỗ-Tây_Mỗ ( Từ_Liêm ) . 
Hai bị_cáo Nguyễn_Quang_Hà , Phan_Văn_Quán vẫn khẳng_định bản_thân  không có tội  , còn những bị_cáo khác chỉ xin HĐXX xem_xét giảm nhẹ khi lượng hình . 
Theo thông_báo của chủ_toạ , HĐXX sẽ nghị_án hai ngày và công_bố phán_quyết cuối_cùng vào sáng thứ_hai ( 5-4 ) . 
�t cuối_cùng vào sáng thứ_hai ( 5-4 ) . 
